### ISSUE TITLE
The game 2048

### ISSUE THREAD

**Issue by Sagar19129** [ssitvit/Games-and-Go#100]
I want to make this game.
The famous 2048 game made in react, with a personal touch and animations.
In this game, the player must combine tiles containing the same numbers until they reach the number 2048. The tiles can contain only integer values starting from 2, and that are a power of two, like 2, 4, 8, 16, 32, and so on. Ideally, the player should reach the 2048 tile within the smallest number of steps.
I eagerly want to contribute for this.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week and go through the readme and contributing.md for successful merge. All the best to your work Sagar... !!!
