### ISSUE TITLE
[FEATURE] - 'Game On' Section Boxes Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#1000]
### Description

The design of each game box is nice but it can be improved by making each game's name box more like smooth corned box which will give more smooth and elegant look to overall box.

Simply, the change will be:
**Smooth corned name box of each game**

### Screenshots

_Current Design_

![i (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/d0062c7f-ceeb-427d-adc9-bef4a3ea329f)

_Expected Updated Design_

![i (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/e7a4e166-fc97-45ee-a01f-bc5e1d232e2b)

### Additional information

No

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this task to you. Kindly complete this within 2 days. Good luck!
