### ISSUE TITLE
[DOCS]: Make Responsive GSSOC Banner for Github Light/Dark Mode 💡✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#1014]
### Description

- The current GSSOC Banner present is documentation is like a static image with black background and white text, the image will not be adaptive to dark and light mode of github.
- So the documentation will look bad for Light Mode.
- Our idea is to make the GSSOC Banner responsive for Both Light & Dark mode of Github, this will way more improve the Documentation.

### Screenshots

|CURRENT - LIGHT|CURRENT - DARK|
|:--:|:--:|
|![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/76c2e0a1-23e5-4a6d-a665-06f548ce3a6d)|![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/7ad22f22-60f9-4c7f-b817-a5012bae4bb9)|

| DESIRED - LIGHT|DESIRED - DARK |
|:----:|:----:|
|![image](https://github.com/Anupkjha2601/food-recipes-website/assets/92252895/590cfc18-b194-4940-8684-75d803fac85e)| ![image](https://github.com/Anupkjha2601/food-recipes-website/assets/92252895/04aff50d-0b2e-4650-8d64-504155b17064)|

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this to you. Kindly complete within 2 days. Good luck!
