### ISSUE TITLE
[FEATURE] Flappy bubble_sofa game

### ISSUE THREAD

**Issue by kanishkasah20** [ssitvit/Games-and-Go#1015]
### Description

An animated and fun version of the popular 2048 game. Built with HTML, CSS and Javascript.

How to play
Move the bubbles with your mouse and add up the same numbers. After adding up two bubbles, two more drop and will not return if they fall over the sofa.

You can turn off the music and sound effects from the home page and also choose the quality of game.

### Screenshots

<img width="799" alt="Screenshot 2023-08-04 201522" src="https://github.com/ssitvit/Games-and-Go/assets/114860158/dda1a04b-c2cc-4cd4-bd38-4937d6b59386">

**Comment by kanishkasah20** [comment]
Please assign it to me under gssoc'23 @panwar8279

**Comment by panwar8279** [comment]
Hi @kanishkasah20 ,  I have assigned this issue to you. Kindly complete by tomorrow. Make sure you will make game in react. Good luck
