### ISSUE TITLE
[FEATURE] Bash a mole game

### ISSUE THREAD

**Issue by kanishkasah20** [ssitvit/Games-and-Go#1017]
### Description

🎮 Game Request
This is a simple arcade game in which you Whack the Moles.
Moles keep on coming and you have to kill them with your hammer.

Point down the features
Game points:
Whack as many moles as you can, within 60 seconds.

**Comment by kanishkasah20** [comment]
please assign this to me @panwar8279

**Comment by panwar8279** [comment]
Hi @kanishkasah20 , I have assigned this issue to you. Kindly complete within 2 days. Good luck!
