### ISSUE TITLE
[FEATURE] Eighth Queens Game 

### ISSUE THREAD

**Issue by Ayushkumargit7** [ssitvit/Games-and-Go#1018]
### Description

To add Eighth Queens Game made in ReactJs.

The eight queens puzzle is the problem of placing eight chess queens on an 8×8 chessboard so that no two queens threaten each other; thus, a solution requires that no two queens share the same row, column, or diagonal. There are 92 solutions. The problem was first posed in the mid-19th century. In the modern era, it is often used as an example problem for various computer programming techniques.

**Comment by Ayushkumargit7** [comment]
@panwar8279 
Please assign this issue.

**Comment by panwar8279** [comment]
Hi @Ayushkumargit7 , I have assigned this task to you. Kindly complete within 2 days. Good luck!
