### ISSUE TITLE
[Feature] - Color Consistency in Each Section

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#1022]
### How would you like to enhance the existing project.

Changing the color of headings of each section according to the theme of the section in order to create more detailed look of ech section. For example, the major color in about section are purple and blue, so we can set the heading to blue or purple to make it sync with the related section. Current color is brown which is making different in the section. Similar changes in the other sections too. 
This will bring more design detail in the each section and overall website.

### Describe breifly how would you implement the same.

By working on the styling of each section, I can improve the design.

# Samples

_**Current Design**_

![i (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/06114b65-23c5-4cac-b4ea-dd4d6f84c0ac)

![i (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/70b736f7-772e-4258-9941-16b2a4552fbf)

**_Expected Updated Design_**

![i (4)](https://github.com/ssitvit/Games-and-Go/assets/115794049/849838c7-26fc-44d1-9dfe-f36961547efd)

![i (3)](https://github.com/ssitvit/Games-and-Go/assets/115794049/231ba3f1-32e6-4aae-83fd-b372cf039f31)

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Kindly complete within 2 days.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
You have close this issue. 

> Kindly complete within 2 days.

**Comment by iamRabia-N** [comment]
@panwar8279 
Kindly confirm it whether I start work on this issue
