### ISSUE TITLE
[FEATURE] - Game On Section Content Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#1023]
### Description

Changing the font styling of each game's font which includes description and rules of each game. The current font styling is simple giving simple look. We can improve it by selecting more gamic font style.

### Screenshots

Current Design

![i (3)](https://github.com/ssitvit/Games-and-Go/assets/115794049/651a013b-dc50-4643-8310-3700b8cc8ef3)

Expected Updated Design

![i (5)](https://github.com/ssitvit/Games-and-Go/assets/115794049/9e50359b-dea3-424a-8fe7-cb737fc67144)

![i (7)](https://github.com/ssitvit/Games-and-Go/assets/115794049/775c88d7-9246-4b4e-9ecf-857fd09c5614)

### Additional information

No

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly enlarge updated design images to clearly see the difference.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this task to you. Kindly complete within 2 days. Good luck 1
