### ISSUE TITLE
[Bug]: 'GuessTheColor' Game Errors

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#1025]
### Give a brief about the bug discovered✍

There are many design bugs in this game. The major bug is the  heading is oversized to font size of 200% which is covering two times of scroll screen. Also, other items involved also too enhanced in sizing.

### What is the expected behavior?

Clear and elegant design of the game.

### Give a brief description to get the expect behaviour.

By working on the styling of this game, I can solves these bugs.

# Sample

**_Current Design_**
![i (4)](https://github.com/ssitvit/Games-and-Go/assets/115794049/429da6e7-72f6-4f82-991d-cca4e0ea2288)

![i (5)](https://github.com/ssitvit/Games-and-Go/assets/115794049/d5c6f5d7-5838-4f03-ad8a-55920dc47975)

**_Expected Updated Design_**

![i (6)](https://github.com/ssitvit/Games-and-Go/assets/115794049/498e8853-cd62-4865-aecc-eb4dcc69a0dc)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this task to you. Kindly complete within 2 day. Good luck!

**Comment by MeenuyD** [comment]
Hello, @panwar8279 I would like to work on this issue please assign it to me.
