### ISSUE TITLE
[FEATURE] LetterFusion Puzzler Game

### ISSUE THREAD

**Issue by Ayushkumargit7** [ssitvit/Games-and-Go#1027]
### Description

To add LetterFusion Puzzler game made using ReactJs.

The player is given six jumbled letters, and must arrange the letters in the jumble to form as many words of three or more letters as they can.

**Comment by Ayushkumargit7** [comment]
@panwar8279 
Please assign the above issue.

**Comment by panwar8279** [comment]
Hi @Ayushkumargit7 , I have assigned this task to you. Kindly complete within 2 days. Good luck!
