### ISSUE TITLE
Game: Labyrinth of Death

### ISSUE THREAD

**Issue by Durgesh4993** [ssitvit/Games-and-Go#1031]
### Description

You've been trapped in the Labyrinth of Death!

Unlock the gates or build a sword and slay the minotaur before he brings death upon everyone!

There are 3 parts to the sword and you may only attack after collecting all three parts.

After escaping the maze a white bar will appear, if it fills entirely, you win!

Every dead NPC removes points, every escaped npc adds points, the longer you take the less points. Finishing the game with full health or killing the minotaur provide a 1.5x Bonus.

To move: WASD / Arrow Keys / ZQSD / Click
To attack: spacebar / double click
To Pause: P

### Screenshots

Screenshots:

![image](https://github.com/ssitvit/Games-and-Go/assets/98798977/bed9a2e2-aed4-43a2-8499-f853b5997d94)

Demo vedio:

https://github.com/ssitvit/Games-and-Go/assets/98798977/091110b2-3cfb-4899-9f5a-d31f5c7073a1

**Comment by panwar8279** [comment]
Hi @Durgesh4993 , I have assigned this task to you. Kindly complete within 2 days. Good luck!
