### ISSUE TITLE
[FEATURE] Quiz Game App

### ISSUE THREAD

**Issue by Ayushkumargit7** [ssitvit/Games-and-Go#1033]
### Description

To add Quiz Game App made using React.js

User has to choose the correct option from the given options.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/114018461/dcbf4bae-17f1-4565-83a5-71dda1049656)

**Comment by Ayushkumargit7** [comment]
@panwar8279 
Please assign the issue .

**Comment by panwar8279** [comment]
Hi @Ayushkumargit7 , I have assigned this task to you. Kindly complete within 2 days. Good luck
