### ISSUE TITLE
[Feature Request]: Icons Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#1043]
### How would you like to enhance the existing project.

The current design of the icons is nice but it can be improved by working on their styling. 
The purpose of changing the icons styling is to make their design consistent with overall website design.

### Describe breifly how would you implement the same.

Working on the icons styling to improve their design.

## Sample Work

**Current Design**

![i (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/93973c19-3609-403a-885d-c864a94c8646)

**Expected Updated Design**

![i (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/edb22d60-9f24-4b5c-afda-cd3577dc0517)

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
No need to change styling.

**Comment by iamRabia-N** [comment]
Ok. Thank you for confirming.
