### ISSUE TITLE
[FEATURE] <Implement Code Quality Improvements in ErrorPage Component>

### ISSUE THREAD

**Issue by simrraann8** [ssitvit/Games-and-Go#1049]
### Description

This issue focuses on enhancing the code quality and maintainability of the ErrorPage component by implementing best practices and following consistent naming conventions. It involves updating class names, using CSS-in-JS for styling, ensuring accessibility, and fixing JSX attribute names. These improvements will make the codebase cleaner and more readable.

**Comment by panwar8279** [comment]
Hi @simrraann8 ,  I have assigned this issue to you. Kindly complete by tomorrow. Good luck!

**Comment by simrraann8** [comment]
Thanks @panwar8279
