### ISSUE TITLE
Issue Title: Add Carousel Effect in Games Section on Home Page

### ISSUE THREAD

**Issue by rishitachail** [ssitvit/Games-and-Go#105]
Issue Description:

Hello @Shreyaar12 

I am a contributor for GSSOC'23, and I would like to take on the task of adding a carousel effect to the games section on the home page of our website. This enhancement will improve the user experience by allowing multiple games to be displayed within a single section, utilizing a visually engaging and interactive carousel.

To implement the carousel effect, I propose the following guidelines:

Carousel Library: Select a suitable JavaScript carousel library, such as Slick Carousel or Owl Carousel, which provides robust features and is compatible with our existing website's tech stack.

Responsive Design: Ensure that the carousel adapts to different screen sizes, making it mobile-friendly and responsive across various devices.

Navigation and Controls: Implement intuitive navigation and control options, such as arrows or dots, to allow users to browse through the games within the carousel easily.

Game Item Layout: Define the layout for each game item within the carousel, including game image, title, description, and any additional relevant information.

Smooth Transitions: Apply smooth transitions and animations between game items as users navigate the carousel to provide a seamless and visually appealing experience.

By assigning me this task, I am confident that I can successfully implement the carousel effect, leveraging my knowledge of JavaScript and front-end development. I will ensure that the carousel aligns with the existing design aesthetics and functionality of our website.

Please let me know if there are any specific requirements, deadlines, or design guidelines I should follow for this task. I look forward to contributing to the improvement of our website's user experience.

Thank you for considering my request.

Best regards,
Rishita Chail

**Comment by raj03kumar** [comment]
Nice proposal. U forgot to edit the third line.
