### ISSUE TITLE
[FEATURE] Connect Four Game

### ISSUE THREAD

**Issue by Ayushkumargit7** [ssitvit/Games-and-Go#1060]
### Description

To add Connect Four Game made using ReactJs. 

Be the first player to connect 4 of the same colored discs in a row (either vertically, horizontally, or diagonally).
1)Red goes first in the first game.
2)Players must alternate turns, and only one disc can be dropped in each turn.
3)The game ends when there is a 4-in-a-row or a stalemate.
4)The starter of the previous game goes second on the next game.

There are two modes to play - 1)Player vs CPU.
                                               - 2)Player vs Player.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/114018461/f1ce78e4-67f5-4672-a4cd-1e9b6d4a6ef5)

![image](https://github.com/ssitvit/Games-and-Go/assets/114018461/67be9694-a58a-4fbe-8a3f-e8b66b5394ab)

![image](https://github.com/ssitvit/Games-and-Go/assets/114018461/d812e40f-cb81-4d6c-b64b-9e93dc40d6b4)

**Comment by Ayushkumargit7** [comment]
@panwar8279 
Please assign it.

**Comment by panwar8279** [comment]
Hi @Ayushkumargit7 , I have assigned this task to you. Kindly complete this by today. Good luck!
