### ISSUE TITLE
[Feature]: 'Typing Master' Game Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#1066]
### How would you like to enhance the existing project.

There are few bugs in the design of this game. 
First, background only fix to few sections of page, giving overall inconsistent design.
Secondly, button is invisible due to its styling.

Besides that, the design of overall game can be improved. The updated design shown below is a little sample. Color theme can be adjusted in the final output.

### Describe breifly how would you implement the same.

Working on the styling of the game to solve its design bugs and improve its design.

# Work Sample

**_Current Design_**

![i (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/e274febe-b0a7-4b7e-8b38-5dc439203738)

**_Expected Updated Design_**

![i (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/17f4979d-f9cc-46d7-bad1-6b4da4815b34)

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
I am able to complete the work of this issue within 2 hours.

**Comment by iamRabia-N** [comment]
> Hi @panwar8279 I am able to complete the work of this issue within 2 hours.

If assigned

**Comment by panwar8279** [comment]
Current design is good so don't want to change.
