### ISSUE TITLE
[Feature Request]: Search Area Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#1067]
### How would you like to enhance the existing project.

The color of search area is nice but it can be improved by making the search area text and icon more visible as currently they are partially suppressed by color selection. So, through this issue, I will improve the:
_**Visibility of search area text and icon**_

### Describe breifly how would you implement the same.

Working on the styling of search area to improve the design..

# Sample Work

_**Current Design**_
![i (3)](https://github.com/ssitvit/Games-and-Go/assets/115794049/ca2d2172-1e85-484f-97d1-60b9ca1e1317)

_**Expected Updated Design**_
![i (4)](https://github.com/ssitvit/Games-and-Go/assets/115794049/2484895b-266d-418f-a2a1-5f26ce90afdc)

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
I can complete this improvement within 2 hours if assigned.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this task to you. Kindly complete by today. Good luck!
