### ISSUE TITLE
I want to add the Simon Game

### ISSUE THREAD

**Issue by Babunshil** [ssitvit/Games-and-Go#107]
The Simon Game is a classic memory game that tests your ability to remember and repeat a sequence of colors and sounds. The game was built using HTML, CSS, and JavaScript

https://github.com/ssitvit/Games-and-Go/assets/106283743/eaa470ab-2485-4416-b958-5de8d48e9d48

**Comment by raj03kumar** [comment]
Assigning this issue to you. Kindly get it done in a week. Go through the necessary guidelines for successful merge. All the best Babun... !!!
