### ISSUE TITLE
[GSSoC'23]: Space invaders

### ISSUE THREAD

**Issue by singh-anushka** [ssitvit/Games-and-Go#108]
We start off with a few aliens and a spaceship(player) whom we have to kill before they reach the surface, by using our spaceship lasers. This basic game is made using HTML, CSS and Javascript.

As you shoot the aliens' points are scored. And if any of the aliens reach the surface then the game is over!
Kindly assign this issue to me.

**Comment by raj03kumar** [comment]
Kindly complete the work in a week and read the related guidelines as well. All the best to you Anushka

**Comment by PayalPadmalyaPrusty** [comment]
@raj03kumar I want to contribute.Please assign me
