### ISSUE TITLE
[GSSoC'23] : Jigsaw puzzle

### ISSUE THREAD

**Issue by singh-anushka** [ssitvit/Games-and-Go#109]
This is a basic simulation of a jigsaw puzzle made using HTML, CSS and Javascript. Firstly select the number of pieces you want your puzzle to be into. Then start solving!
Try to make the initial picture of the puzzle by joining the puzzle pieces. Auto-snap feature is also enabled to ensure that the pieces connected are right.

Kindly assign me this game.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within 7 days. ALL THE BEST

**Comment by PayalPadmalyaPrusty** [comment]
@raj03kumar I want to contribute.Please assign me
