### ISSUE TITLE
Make Homepage Responsive

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Games-and-Go#11]
Pacman landing on homepage to be made responsive

**Comment by afeefuddin** [comment]
Hey @Shreyaar12 , I want to work on this issue please assign me this issue,  if anyone else is not working

**Comment by vk20july** [comment]
@Shreyaar12 I want to work on this issue under GSSoC'23

**Comment by ShivendraTrivedi** [comment]
Hey there! I noticed the open issue "Make Homepage Responsive" in the repository. I'd like to take on this task and make the homepage responsive. Here's how I plan to do it:

1. I'll carefully analyze the current homepage code and its structure to understand how it's built.

2. Next, I'll identify the areas that need modification to achieve responsiveness. This might involve adjusting CSS styles, reorganizing elements, or using media queries.

3. To ensure compatibility across different devices and screen sizes, I'll apply responsive design techniques like fluid layouts, flexible grids, and responsive images.

**Comment by green-veggies** [comment]
I want to work on this project under GSSoC'23

**Comment by Shreyaar12** [comment]
@ShivendraTrivedi assigned it to you, kindly complete within 10 days

**Comment by ShivendraTrivedi** [comment]
@Shreyaar12 Yaa sure!

**Comment by ShivendraTrivedi** [comment]
Is it necessary to make 4 PR's (as mentioned in Readme), can't I successfully complete it and make generate only 1 PR.

**Comment by rv1830** [comment]
please assign this to me

**Comment by raj03kumar** [comment]
> @Shreyaar12 Yaa sure! and Is it necessary to make 4 PR's (as mentioned in Readme), can't I successfully complete it and make generate only 1 PR?

Ignore that
