### ISSUE TITLE
[GSSoC'23]: Black Jack

### ISSUE THREAD

**Issue by singh-anushka** [ssitvit/Games-and-Go#112]
This card game consists of 2 players; one player has 2 cards and the other player(dealer) has 3 cards (with one card hidden), and the dealer must draw a card until they get a sum of at least 17.

There are 2 cases of deciding a winner:
1. The player (not the dealer) has a sum of cards below 21 then if the sum of cards for the dealer is above 21 then; the player wins.
2. If the player has a sum of cards above 21 then no matter what the dealer has; the player loses.

Kindly assign me this issue.

**Comment by singh-anushka** [comment]
@raj03kumar I have almost completed this game. Can you please assign me this issue I'll submit the same by tomorrow morning.

**Comment by raj03kumar** [comment]
Good to know. Kindly follow all the guidelines and happy coding Anushka... !!!

**Comment by singh-anushka** [comment]
I am making this using HTML, CSS and Javascript

**Comment by raj03kumar** [comment]
> I am making this using HTML, CSS and Javascript

Use react framework and go through contributing.md for successful merge.

**Comment by singh-anushka** [comment]
Then can I complete it by next week or so?

**Comment by singh-anushka** [comment]
I actually completed that almost so. So now since I have to make it from scratch it will take time. But I really want to contribute. So give me some time, I'll definitely complete it and will make a really good pr for sure.

**Comment by raj03kumar** [comment]
> I actually completed that almost so. So now since I have to make it from scratch it will take time. But I really want to contribute. So give me some time, I'll definitely complete it and will make a really good pr for sure.

No Issues Anushka. Since you have lot's of task we will extend your time to your preference but don't stretch it for long. Get all things done till the first week of June.

**Comment by manasi-jain** [comment]
Hello @raj03kumar, I would like to request your attention regarding this issue. I have successfully completed the task and submitted a pull request. Kindly review it and consider assigning it to me under the GGSOC'23 project. Thank you!
