### ISSUE TITLE
[GSSoC'23]: Atari Breakout

### ISSUE THREAD

**Issue by singh-anushka** [ssitvit/Games-and-Go#114]
A single-player game where one needs to smash the bricks using a paddle and a ball. The player will have full control over the paddle in the horizontal direction. You need to smash all the bricks before all your life runs out, which happens when the ball hits the ground.
As the bricks are smashed the points are scored. Once all the bricks are smashed. Player wins.

Please assign me this issue.

**Comment by singh-anushka** [comment]
@raj03kumar This along with the blackjack game I'll complete it by tomorrow morning kindly assign me this game. So that I can generate a PR by tomorrow.

**Comment by raj03kumar** [comment]
All the best...
