### ISSUE TITLE
Change class to className

### ISSUE THREAD

**Issue by Avinash905** [ssitvit/Games-and-Go#121]
This project contains **class** instead of **className** in few files due to which there are errors displayed in browser console.

Please assign me this issue under **GSSOC'23** so that I can replace all **class** with **className**.

**Comment by sirajlekhak** [comment]
I am eager to contribute as a valuable team member and demonstrate my skills in GSSoC'23. If you would kindly assign me an issue, I would be delighted to work on it and showcase my abilities effectively within the program.

**Comment by Avinash905** [comment]
> This project contains **class** instead of **className** in few files due to which there are errors displayed in browser console.
> 
> Please assign me this issue under **GSSOC'23** so that I can replace all **class** with **className**.

@raj03kumar Could you please assign this issue to me under **GSSOC'23**

**Comment by Avinash905** [comment]
@admindebu I think the assigning of the issue is based on first come first serve, so could you please assign me the issue as I have raised the issue and asked me to assign it.

**Comment by Avinash905** [comment]
@admindebu It's been many days since you assigned this issue but it has not yet been resolved. So can you assign it to me?

**Comment by panwar8279** [comment]
@sirajlekhak , did you completed?
