### ISSUE TITLE
[GSSoC'23] Word Association Game.

### ISSUE THREAD

**Issue by Arka2708** [ssitvit/Games-and-Go#124]
A word association game that will have several levels, and based on that we'll be having questions, IN each question there will be 3-4 words and there will be 3 options, among those 3 options you have to find out the word that can be associated or common with all the words given above. if you are correct you are getting a point and if you are wrong, you will be getting negative points. I'm gonna use basic HTML, CSS, JS to build the game.

Assign me this project under GSSoC'23.

**Comment by admindebu** [comment]
Hi @Arka2708 , could you please elaborate on the features of the game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.
