### ISSUE TITLE
[GSSoC'23] Dicee-Game.

### ISSUE THREAD

**Issue by Babunshil** [ssitvit/Games-and-Go#129]
The game is designed to be played by two players, with each player taking turns to roll the dice. The game keeps track of the score, and the player with the highest score at the end of the game is declared the winner.

**Comment by raj03kumar** [comment]
Babun since your last PR is done without React. What tech stacks r u going to use here ?

**Comment by raj03kumar** [comment]
This project is made using React framework so just mere HTML CSS won't work in the codebase. Let us know if u are comfortable with React then we can proceed with you.

**Comment by Babunshil** [comment]
I have already made this using HTML CSS and JavaScript, I have started learning react , can i got some time so i can make the components using react

**Comment by Babunshil** [comment]
> @raj03kumar Could you please assign to me under gssoc'23

I am working on it

**Comment by AVUKU-PRAGATHESWARI** [comment]
I would like to work on the issue as a contributor of GSSoC23.
Please assign me the issue.
