### ISSUE TITLE
New Game : Drumkit Game

### ISSUE THREAD

**Issue by pearlrathour** [ssitvit/Games-and-Go#136]
Please assign this issue to me, I will contribute to this issue under GSSoC'23.

**Comment by crapbagaah** [comment]
I can contribute in making the DrumKit Game, please consider me and assign me the issue under GSSOC'23

**Comment by raj03kumar** [comment]
@pearlrathour Can you elaborate on this or give any demo pic or video.

**Comment by admindebu** [comment]
Hi @pearlrathour , could you please elaborate on the features of the game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.

**Comment by pearlrathour** [comment]
Drum and Kit Game is a rhythm-based game where players simulate playing a virtual drum kit using keyboard.
tech use:Html,css,javascript

![image](https://github.com/ssitvit/Games-and-Go/assets/99817664/3337dc62-89b4-4d45-8a68-468bf69b2593)

**Comment by sumitkr2000** [comment]
hey @raj03kumar if she is not working on it can I work on this issue? Please assign me this issue. I can work on it quickly.

**Comment by Ashasindhu** [comment]
If nobody working on this issue can i work on this issue under GSSoc 2023?

**Comment by sumitkr2000** [comment]
It's already merged. @Ashasindhu
