### ISSUE TITLE
2048

### ISSUE THREAD

**Issue by pearlrathour** [ssitvit/Games-and-Go#138]
Objective of the game is to merge tiles to reach the elusive 2048 tile and beyond in this addictive number puzzle game. Swipe in four directions to combine identical numbers, strategize your moves, and aim for the highest score. Can you conquer the board and become the ultimate 2048 master?

Please assign this issue to me, I will contribute to this issue under GSSoC'23. I can create it with the help of HTML, CSS, JS

**Comment by raj03kumar** [comment]
This is react project so if you can do it in react then i can assign it to you.

**Comment by pearlrathour** [comment]
Yes, I can do it in react js; please assign me.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within 10 days and go through the readme and contributing.md for successful merge. All the best to your work Pearl... !!!

**Comment by sumitkr2000** [comment]
hey @raj03kumar if she is not working on it can I work on this issue? Please assign me this issue. I can work on it quickly.
