### ISSUE TITLE
[GSSoC'23] : 6X6 BattleShips

### ISSUE THREAD

**Issue by AayushAryan007** [ssitvit/Games-and-Go#139]
I am creating this classic game called 6X6 Battleships using HTML, CSS and JavaScript which consist of 6 X 6 grid structure out of which you have to guess the correct block in which enemy ship must be hidden, if you guess right You hit the ship, else you miss.

(images attached below are just for the reference to the game ideology and structure, final project may vary according to the new designs)
![battle](https://github.com/ssitvit/Games-and-Go/assets/94699736/8731373b-a811-46a4-988a-7b2b95425522)
<img width="530" alt="game" src="https://github.com/ssitvit/Games-and-Go/assets/94699736/9a94023c-0f13-42e1-863e-6e01a0b1dff1">

**Comment by AayushAryan007** [comment]
Kindly assign this issue to me as I have already worked on few games based on java scrip and I am willing to put all efforts in this particular project.

**Comment by raj03kumar** [comment]
Assigned this issue to you kindly complete it within a week and go through the readme and contributing.md for successful merge. All the best to your work Aayush... !!!

**Comment by AayushAryan007** [comment]
@raj03kumar thank you for assigning me the issue.

**Comment by AayushAryan007** [comment]
Thank you for the merge and this opportunity.
