### ISSUE TITLE
[Enhancement] Fix the pacman animation in the homepage

### ISSUE THREAD

**Issue by raj03kumar** [ssitvit/Games-and-Go#140]
Fix the animation of the pacman in the starting. 
- The yellow ghost should eat IEEE-SSIT and cross the screen from left to right and then the other ghosts should come running from right to left displaying **games and go**
- There is some timing issue that's it.
- Also **LOOP** the animation.
- If anybody comes with any better idea then they are welcomed with **enhancement tag** as well for **GSSoC'23**
- The demo animation looks like: https://deploy-preview-23--harmonious-stardust-e06cab.netlify.app/

**Anybody interested can tag me. I will assign it soon.**

**Comment by AnkitAnandMastery17** [comment]
Can you assign this to me?

**Comment by raj03kumar** [comment]
Assigned this task to you. Kindly get it done within 10 days. All the best to your work.
