### ISSUE TITLE
TIC TAC TOE GAME

### ISSUE THREAD

**Issue by Nishka30** [ssitvit/Games-and-Go#142]
Tic Tac Toe is a classic game that has been brought to life on the web using HTML, CSS, JavaScript, and jQuery. The game is designed to be played by 1-2 players on a 3x3 grid.

When playing in single-player mode, the player competes against the computer. The computer utilizes an algorithm to make its moves. The algorithm typically follows a set of rules to determine the best move to make. It analyzes the current state of the game, evaluates possible moves, and selects the one that maximizes its chances of winning or prevents the player from winning.

In double-player mode, two players take turns placing their respective marks, X's and O's, on the grid. The players can be friends, family members, or any two individuals competing against each other. Each player aims to create a line of three of their marks either horizontally, vertically, or diagonally on the grid.

The game's interface is built using HTML and styled using CSS to provide an appealing visual representation of the grid and the marks placed by the players.

**Comment by admindebu** [comment]
Hi @Nishka30, could you please make it using react JS? if you have any mock UI page demo/video please share here, so that we can evaluate and assigned task to you

**Comment by admindebu** [comment]
ALready game in the repo. plz contribute others features / issues
