### ISSUE TITLE
Issue Title: Fix content visibility on container card

### ISSUE THREAD

**Issue by rishitachail** [ssitvit/Games-and-Go#144]
Hello @Shreyaar12 @raj03kumar 

Issue Description:
Upon visiting the website, I noticed that the content on the container card is only visible when hovering over it, otherwise it appears blank. However, I have already resolved this issue and made the necessary changes to the code.

Issue Resolution:
I have modified the CSS code to ensure that the content on the container card is visible at all times, without the need for hovering. The changes I made address the visibility problem and improve the overall user experience.

Request:
Please assign this issue to me so that I can send a pull request with the fix. I would be glad to contribute the solution and enhance the functionality of the website.

Additional Information:

The issue was observed on the website's container card element, where the content was hidden unless hovered upon.
I have thoroughly tested the changes and verified that the content is now consistently visible without any adverse effects.
Screenshots showcasing the before and after appearance of the container card can be provided if needed.
I am looking forward to contributing and collaborating on this project. Thank you for your attention to this matter.

Best regards,
Rishita Chail

Before updating
![Games-And-Go - Google Chrome 5_22_2023 8_19_04 PM](https://github.com/ssitvit/Games-and-Go/assets/108628119/85574dcb-94b2-409f-95ac-2df28ddb0641)

After updating
![Games-And-Go - Google Chrome 5_22_2023 8_18_51 PM](https://github.com/ssitvit/Games-and-Go/assets/108628119/709b6187-be4a-4af4-875b-2c7a04abd3d6)

**Comment by raj03kumar** [comment]
That's hover effect on the card Ishita. Not a bug

**Comment by rishitachail** [comment]
> That's hover effect on the card Ishita. Not a bug
@Yeah , I know it's hover effect but it is not the suitable one . Let me share in video form.

**Comment by rishitachail** [comment]
This is not the appropriate hover effect 

https://github.com/ssitvit/Games-and-Go/assets/108628119/863f083f-fd0d-4d36-a859-b780dab90a78

**Comment by rishitachail** [comment]
Instead it should appear this way if you want to keep the hover effect. I can increase the effect if required. But the display on the card shouldn't be empty as in the first video.

https://github.com/ssitvit/Games-and-Go/assets/108628119/7fa8083c-c6dc-460c-80cc-acc948359b4e
