### ISSUE TITLE
make-redux-sudoku using react

### ISSUE THREAD

**Issue by cleveranu** [ssitvit/Games-and-Go#15]
Sudoku is a fun puzzle game  and a classic game. Has Undo and problem solver.

**Comment by Sukhendu2002** [comment]
Hey @Shreyaar12 Can you assign this to me i want to make it

**Comment by krittika2004** [comment]
Please assign this issue to me @Shreyaar12

**Comment by Shalender24** [comment]
Hey Shreya , I want to contribute in this issue , I'll also add option like level of game i.e. easy , medium , hard . Please assign me this issue @Shreyaar12 , I'm a member of Gssoc`23 .
