### ISSUE TITLE
Addition of Tetris Game 

### ISSUE THREAD

**Issue by Mukesh751** [ssitvit/Games-and-Go#151]
This is of the best 90s game and I remember that I used to play it in a Nokia's keypad. I can make this game on react.
Thanks and Regards

**Comment by Mukesh751** [comment]
![Screenshot (118)](https://github.com/ssitvit/Games-and-Go/assets/91366697/eaedf485-2cea-4808-aced-c3418ab8cb7d)

**Comment by admindebu** [comment]
Hi @Mukesh751 , are you fine to develop this using react js ? 
and share the details documentation of this project.

**Comment by Mukesh751** [comment]
![Screenshot (121)](https://github.com/ssitvit/Games-and-Go/assets/91366697/7596bca5-b058-4dad-a769-bde1ac0d703a)


Sir, is it good? should i commit and request PR?
