### ISSUE TITLE
[GSSoC'23] Developing a hangman game

### ISSUE THREAD

**Issue by ManasaKaza** [ssitvit/Games-and-Go#155]
The hangman game is a game to guess a word within a certain limit of chances, the words are taken from a dictionary and if the word is not guessed correctly by the chances, the man will be dead.

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly get it done within a week and go through the readme and contributing.md for successful merge. All the best to your work Manasa... !!!

**Comment by Srishtikumari2002** [comment]
@raj03kumar  If this issue is not solved yet then I would like to work on it. I have previously worked on this problem, you can check it on my GitHub profile for reference.
