### ISSUE TITLE
Card Background image set

### ISSUE THREAD

**Issue by AnmolChauhan123** [ssitvit/Games-and-Go#159]
Can set the Background image of the Card so that one can get a glimpse of the game and how it is. There can also be an moving SVG on the background of the card on the home page. Please assign this issue to me. Under the tag gssoc'23

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly get it done within a week. All the best to your work Anmol... !!!

**Comment by AnmolChauhan123** [comment]
Alright I will try to do it in a given time.... But for the safer side can you give an extension of the deadline as my exams are going on right now... That will be really considerate of you.... BTW I will try my best to complete this one in the given time for sure...
