### ISSUE TITLE
Improve styling of the game trivia.

### ISSUE THREAD

**Issue by AnmolChauhan123** [ssitvit/Games-and-Go#160]
I think the trivia game needs an improvement in the styling and I can make it a little better. I can also add some more questions in the game and make it a little more appealing. Please assign this issue to me. Under the tag gssoc'23.

**Comment by raj03kumar** [comment]
Assigned this issue to you kindly get it done within a week.

**Comment by AnmolChauhan123** [comment]
Alright I will try to do it in a given time....
