### ISSUE TITLE
Developing Tetris Game

### ISSUE THREAD

**Issue by mahekkg** [ssitvit/Games-and-Go#162]
Hello everyone! 
As part of my contribution to GSSoC'23, I would like to propose the addition of a Tetris game to the project. Tetris is a classic and popular game that can bring both entertainment and interactive elements to our project.

Proposed Approach:
1. Research: I will conduct research on Tetris game implementations in various programming languages and frameworks to understand the best practices and design patterns.
2. Design: I will create a plan for the game's architecture, user interface, and game mechanics to ensure an engaging and user-friendly experience.
3. Development: I will write the necessary code to implement the Tetris game, considering modularity, scalability, and code quality.
4. Testing: I will thoroughly test the game for functionality, usability, and compatibility across different devices and browsers.

Please let me know if you have any feedback and assign me task under GSSoC'23.

**Comment by raj03kumar** [comment]
Already someone is assigned

**Comment by mahekkg** [comment]
Okay ,
I have previously also worked on Playable Piano and Word Scramble.
If any of the above is left and not assigned let me know .
Thank you.
