### ISSUE TITLE
I want to add Xylophone website.

### ISSUE THREAD

**Issue by kriti-002** [ssitvit/Games-and-Go#163]
Hi @ssitvit, I want to add xylophone game I built using HTML, CSS, JavaScript and Bootstrap. This will be a boon for small children who want to learn new sounds. This has the tune of all 7 notes of music.
I want to contribute it under GSSOC'23. Kindly assign this issue to me. I would love to contribute to your project.

**Comment by raj03kumar** [comment]
Kindly get it done within a week. You have to use ReactJS and not just HTML, CSS and JS. All the best to your work Kriti... !!!

**Comment by kriti-002** [comment]
Thank you @raj03kumar for this opportunity. I will surely complete this within the timeline.
