### ISSUE TITLE
Playable piano

### ISSUE THREAD

**Issue by raj03kumar** [ssitvit/Games-and-Go#164]
Make a playable piano using ReactJS with beautiful interface and creative design.

**Comment by raj03kumar** [comment]
@mahekkg get this issue

**Comment by mahekkg** [comment]
@raj03kumar Yes I can work on it.
Will a different TechStack work instead of ReactJs?

**Comment by raj03kumar** [comment]
No this is ReactJS repo so it won't support

**Comment by raj03kumar** [comment]
Kindly go through the readme and contributing.md.

**Comment by mahekkg** [comment]
Can I get back to you on this issue by tomorrow morning if it works?

**Comment by raj03kumar** [comment]
Take your time. If u are not comfortable then you can choose anything different.
