### ISSUE TITLE
Rock, Paper, Scissor, Spock and Lizard Game

### ISSUE THREAD

**Issue by prrockzed** [ssitvit/Games-and-Go#166]
I want to create a rock, paper, scissor, spock and lizard game in reactjs. This is a slightly advanced version of the common rock, paper scissor game that we play.

But an amazing game it is!! Fun logic!

![rock___paper___scissors___lizard___spock_by_scificat-d4u389n-741447488](https://github.com/ssitvit/Games-and-Go/assets/97661506/b178c01f-0c69-4578-aa51-862c6c4700f6)

**Comment by prrockzed** [comment]
@raj03kumar Please assign this project to me under gssoc23

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by prrockzed** [comment]
Hi, this was my idea and I proposed it first. So please assign this to me.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly get it done within a week and go through the readme and contributing.md for successful merge. All the best to your work Priyanshu...!!!
