### ISSUE TITLE
Adding Pre loader page [GsSOC 2023] 

### ISSUE THREAD

**Issue by ManishaSwain8** [ssitvit/Games-and-Go#167]
As the application increases the loading time increases ,So adding loader page would increase the overall  attractiveness.
I was thinking to add packman loader.
If this feature is required, then please assign it to me under GSSOC 2023. !   :|)

**Comment by raj03kumar** [comment]
Kindly add "games and go" and the "organization name with logo" which is there in Readme in the preloader. All the best to your work manisha... !!!

**Comment by raj03kumar** [comment]
> As the application increases the loading time increases ,So adding loader page would increase the overall attractiveness. I was thinking to add packman loader. If this feature is required, then please assign it to me under GSSOC 2023. ! :|)

Okay you can go with pacman laoder if u are comfortable. No issues.

**Comment by PayalPadmalyaPrusty** [comment]
@raj03kumar I want to contribute.Please assign me
