### ISSUE TITLE
To add Playable Piano

### ISSUE THREAD

**Issue by DhairyaMajmudar** [ssitvit/Games-and-Go#168]
To add a playable piano and make it attractive HTML, CSS and make it playable with the help JavaScript

**Comment by DhairyaMajmudar** [comment]
Ok, I will do this using React JS

**Comment by DhairyaMajmudar** [comment]
Thank You assigning  😃

**Comment by DhairyaMajmudar** [comment]
And I have also raised the issue:  To Add a memory game #146 it will be really great of if you assign me this issue as well

**Comment by raj03kumar** [comment]
> And I have also raised the issue: To Add a memory game #146 it will be really great if you assign me this issue as well

That's already live on our website. If you haven't checked it then check it out
