### ISSUE TITLE
Diglet Whack a mole

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [ssitvit/Games-and-Go#170]
🎮 Game Logic:

1. Gameplay Setup: The game is typically played on a screen, such as a mobile device or computer, with the Diglet holes displayed in a grid-like pattern.
2. Diglet Pop-Up: Diglets randomly pop up from their holes at different intervals.
3. Whack Action: Players use their finger or a designated control (e.g., mouse click) to tap or "whack" the Diglet as quickly as possible.
4. Scoring: Each successful hit on a Diglet earns the player points. The faster the player reacts, the higher the score.
5. Time Limit: The game typically has a time limit, encouraging players to whack as many Diglets as possible within that time frame.
6. Game Over: The game ends when the time limit expires.

🎮 Features:

1. Time Pressure: The inclusion of a time limit adds excitement and encourages players to act quickly.
2. Visual and Audio Effects: The game may incorporate appealing graphics, animations, and sound effects to enhance the overall gaming experience.

![image](https://github.com/ssitvit/Games-and-Go/assets/90240653/e41bc4dc-3113-40a9-9466-3aeef622a65a)

**Comment by admindebu** [comment]
Hi @PriyankaTamhankar01, could you make this game using react js? is there any level of the game after a certain threshold point is reached by the player?

**Comment by PriyankaTamhankar01** [comment]
@admindebu there are no specific levels that the player advances to after reaching a certain threshold point. I can make this game using **html ,css & js**
