### ISSUE TITLE
Adding a Mine Sweeper Game

### ISSUE THREAD

**Issue by Khushi-Shar** [ssitvit/Games-and-Go#173]
I want to add a mine sweeper game. It is a one player puzzle game that you have to click on all of the tiles that do not have a mine hidden under them to win. 
Please assign me this task.

**Comment by admindebu** [comment]
Hi @Khushi-Shar , could you please elaborate on the features of the game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.
