### ISSUE TITLE
Adding Simon game

### ISSUE THREAD

**Issue by splusb** [ssitvit/Games-and-Go#175]
Please assign this issue to me under GSSOC'23

**Comment by Nitirani2003** [comment]
This would be a great idea to create this game .Please can you assign me this issue under GSSOC'23.This would be great to work on.

**Comment by srushtikage** [comment]
Hi I'm GSSOC'23 Contributor, I would like to work on this project pls assign it to me.

**Comment by splusb** [comment]
Hi, Can you review this issue please?

**Comment by admindebu** [comment]
Hi Team, members, serveral contributor already made the same request to add "Simon Game", so I am closing your request. please contribute other unique and open issues.
