### ISSUE TITLE
Adding pause and resume button to any particular game

### ISSUE THREAD

**Issue by trisharaj06** [ssitvit/Games-and-Go#180]
There should be pause resume and restart button on every game, could you assign this to me under gssoc'23

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly get it done in a week.

**Comment by Meghaa702** [comment]
I would be happy to contribute to the project as I find my skills a good fit for the issue . As a GSSOC 23 member I humbly ask to allow me to contribute to the issue.

**Comment by anupdhoble** [comment]
I know how to fix this , So would like to work on this project. Please assign it to me under GSSOC'23
