### ISSUE TITLE
Change the Bg color game

### ISSUE THREAD

**Issue by akshit5565** [ssitvit/Games-and-Go#19]
I want to contribute here under the hacktoberfest.
@vibgyor786 please assign me the task

**Comment by Shreyaar12** [comment]
Assigned it to you 
Make sure you add the game in React and go through readme.md and contributing.md

**Comment by Bharadwajshivam28** [comment]
@cleveranu please assign me under GSSOC@#

**Comment by rahultomarr** [comment]
I'm here to contribute to the GSSOC'23.
Please assign me to do that.

**Comment by Bharadwajshivam28** [comment]
@cleveranu which tags are required fro GSSOC23 mam like please assign and add the tags of difficulty also

**Comment by purviporwal0** [comment]
i would like to contribute to this under GSSOC'23

**Comment by adityavpawar** [comment]
i would like to contribute to this under GSSOC'23
