### ISSUE TITLE
Add a spin-a-wheel pop up after loosing a game 

### ISSUE THREAD

**Issue by Gyanvi908** [ssitvit/Games-and-Go#193]
we can Add a spin-a-wheel pop-up after losing a game so that if the person wants more to play they can spin that wheel and get some lives to play if the wheel hits on additional lives

**Comment by admindebu** [comment]
Hi @Gyanvi908, could you please elaborate on the features of the Crossword game with full details, demo / mock UI sample/Video, and tech stack? also share the plan details

**Comment by Gyanvi908** [comment]
We can add an "Extra Lives" box after losing every game and when somebody clicks on extra lives it gives us the pop-up....we can use a Modal in React to do the same.
