### ISSUE TITLE
[GSSOC'23]Want to add famous Drum game

### ISSUE THREAD

**Issue by piyush-mahajan** [ssitvit/Games-and-Go#195]
Hey!! can I add a popular game to the repo and can you assign it to me?

**Comment by srushtikage** [comment]
Hi I'm a GSSoC'23 Contributor, I would like to contribute to this issue pls assign it to me.

**Comment by admindebu** [comment]
Hi @piyush-mahajan and @srushtikage , could you please elaborate on the features of the game with full details, demo / mock UI sample/Video, and tech stack? also, share the plan details

**Comment by piyush-mahajan** [comment]
It is the game with keyboard stroke for beats and sounds and you will create beat out of it ☺️
