### ISSUE TITLE
Rubik's Cube Game

### ISSUE THREAD

**Issue by prrockzed** [ssitvit/Games-and-Go#197]
Most of us have played rubik's cube game. And playing it in a software in our laptop is just amazing. I want to implement a Rubik's Cube game in javascript. The player will be able to move the rubik's cube and change the viewing angle as well as, of course they will be able to move the parts of the rubik's cube, all with the help of their mouse. The rubik's cube will be unsolved when the game will be started. Once the player solves the cube, he/she wins the game.

Also the player will have the option to choose between rubik's cube. That is, one can choose between 2x2, 3x3, 4x4 and 5x5 rubik's cube. And solve it.

@raj03kumar Please assign this project to me under gssoc23.

**Comment by Meghaa702** [comment]
I would be happy to contribute to the project as I find my skills a good fit for the issue . As a GSSOC 23 member I humbly ask to allow me to contribute to the issue.

**Comment by prrockzed** [comment]
Hey, this is my idea and I want to make it. @raj03kumar please assign it to me.

**Comment by prrockzed** [comment]
I am using javascript to develop the game. Almost everything is done. Just finalising and fixing some bugs. Will be uploading it to GitHub and pushing it tomorrow.

**Comment by admindebu** [comment]
Hi @prrockzed , could you please develop it using react js? as this is react js-based repo? if so then share the UI sample and details
