### ISSUE TITLE
Snake Game 

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Games-and-Go#2]
Create a 90 s snake game using React.js

**Comment by tokyo3001** [comment]
Can you assign me this issue?

**Comment by Shreyaar12** [comment]
Assigned it to you kindly use React js in the game and refer contributing.md before making pr

**Comment by tokyo3001** [comment]
@Shreyaar12 Sure!

**Comment by rt-001** [comment]
I would like to work on this issue under GSSOC'23

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Shreyaar12** [comment]
@rt-001 you can work on this issue, make sure you complete it within 10 days

**Comment by Shreyaar12** [comment]
@harshsingh32 please raise another issue and we will assign that to you
