### ISSUE TITLE
Mario Jump

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Games-and-Go#20]
Make a mario character jump/run/ move on key press and overcome obstacles

**Comment by singh-anushka** [comment]
Can you please assign it to me?

**Comment by vk20july** [comment]
@Shreyaar12 I want to work on this issue under GSSoC'23

**Comment by adityavpawar** [comment]
Can you please assign it to me?

**Comment by Deepanshu0703** [comment]
@Shreyaar12
