### ISSUE TITLE
The Simon Game

### ISSUE THREAD

**Issue by srushtikage** [ssitvit/Games-and-Go#202]
Hi Wanted To Add The Simon Game. Pls Assign This Issue To Me Under GSSOS'23.

**Comment by Meghaa702** [comment]
I would be happy to contribute to the project as I find my skills a good fit for the issue . As a GSSOC 23 member I humbly ask to allow me to contribute to the issue.

**Comment by srushtikage** [comment]
@Meghaa702 i have created this issue and i will be working on it.You can create another issue if u want.

**Comment by Meghaa702** [comment]
> @Meghaa702 i have created this issue and i will be working on it.You can create another issue if u want.

ok

**Comment by admindebu** [comment]
You can start work on it
