### ISSUE TITLE
Adding a Footer

### ISSUE THREAD

**Issue by Sakar95** [ssitvit/Games-and-Go#205]
I would like to add a footer to this game website, which gives a professional look.
Please assign me this under gssoc'23
![gng](https://github.com/ssitvit/Games-and-Go/assets/107045521/a77edc29-5082-47c4-9813-7f529273be67)

**Comment by Alight-Shivam** [comment]
I would like to work on this.

**Comment by himanshi-sharma-123** [comment]
Hii!! I am a contributor in GSSOC'23. I would like to work on it.
Below Here is the Sreenshot
![Screenshot 2023-05-27 203414](https://github.com/ssitvit/Games-and-Go/assets/78066781/3f9b5003-1282-4225-ae6e-fa2066889271)

**Comment by admindebu** [comment]
Hi @Sakar95  make it interactive and responsive.

**Comment by ShubhaSwarup** [comment]
<img width="1022" alt="Screenshot 2023-05-29 at 11 42 41 PM" src="https://github.com/ssitvit/Games-and-Go/assets/112583158/b550f79e-bbc5-4903-ab03-5012a15f7835">
I will make the footer interactive and responsive.I have shared a desig. please assign this issue to me
