### ISSUE TITLE
[GSSOC'23 Contribution]: Dice Showdown Game

### ISSUE THREAD

**Issue by md-rosh02** [ssitvit/Games-and-Go#209]
A fun Dice Showdown game

**Comment by Meghaa702** [comment]
I would be happy to contribute to the project as I find my skills a good fit for the issue . As a GSSOC 23 member I humbly ask to allow me to contribute to the issue.

**Comment by md-rosh02** [comment]
Hey @Meghaa702 ! You have been assigned this issue you can start working on the issue 🎮

**Comment by md-rosh02** [comment]
Hey @Meghaa702 ! You have been assigned this issue you can start working on the issue 🎮

**Comment by admindebu** [comment]
@md-rosh02 , could you please elaborate on the features of the  game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.

**Comment by md-rosh02** [comment]
Below I have given photos of it you can see there.


![Screenshot (41)](https://github.com/ssitvit/Games-and-Go/assets/132879891/55746e43-cb15-4f70-a727-818b11065942)

![Screenshot (40)](https://github.com/ssitvit/Games-and-Go/assets/132879891/330843eb-2b12-4585-94e7-9c894a7b1baf)
