### ISSUE TITLE
GSsOC '23 Contribution [Memory Game]

### ISSUE THREAD

**Issue by jyotideepjee1803** [ssitvit/Games-and-Go#211]
I'd like to express my keen desire to contribute to your project under GSsOC'23 by adding a Magic Match Game implemented using ReactJS.
![game](https://github.com/ssitvit/Games-and-Go/assets/98221699/c1b1258d-bd85-45ef-8ce0-6727c18c574e)
Kindly assign me this issue for game

**Comment by admindebu** [comment]
Hi @jyotideepjee1803 , could you please elaborate on the features of the  game with full details, demo / mock UI sample/Video? better share details documentation.
Because you have pasted the copy right claim pic here.

**Comment by jyotideepjee1803** [comment]
https://github.com/ssitvit/Games-and-Go/assets/98221699/24d0c7ab-2302-4916-ac83-9287609a611b

Demo
