### ISSUE TITLE
SNAKE GAME 🐍🐍

### ISSUE THREAD

**Issue by sanyayaa** [ssitvit/Games-and-Go#213]
I would like to add famous Snake Game which I guess everyone of us have played in our childhood.
The game will be build using HTML CSS and JavaScript.
Kindly assign me this issue.
Thanking You in advance.

**Comment by Shreyaar12** [comment]
This repository is based on React js, also we already have issues open for snake game. 
You can go for other games to contribute. 
Thanks.

**Comment by admindebu** [comment]
[Aleady game in the repo] As this repository is based on React js, we have already issues open for the snake game
