### ISSUE TITLE
New Game: Flappy Bird

### ISSUE THREAD

**Issue by iamaashi23** [ssitvit/Games-and-Go#214]
Create a flappy bird game. Please assign me this under GSSoC'23.

**Comment by admindebu** [comment]
Hi @iamaashi23, could you please elaborate on the features of the game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.

**Comment by iamaashi23** [comment]
Good Evening @admindebu . 
This a mini game where you can control the movement of the bird so that it doesn't collide with any of the pillars.

Score: When the bird crosses one pillar the score is incremented and recorded to get the final score of the player.
Sound Effect: Background sound goes on during the game and pitch increases at the time of hit.
I am attaching a picture for a better understanding of the game.
![image](https://github.com/ssitvit/Games-and-Go/assets/101196053/46a75e9d-3ee5-49ce-97e4-4a7508356199)

Here is a video of the same.

[Screen Recording - Made with FlexClip.webm](https://github.com/ssitvit/Games-and-Go/assets/101196053/1681035d-60e7-4436-b45b-cf63b3477fe8)


Tech Stack: HTML, CSS, JAVASCRIPT
Kindly inform me if there is any other details you need . Thank you.
