### ISSUE TITLE
TETRIS

### ISSUE THREAD

**Issue by Meghaa702** [ssitvit/Games-and-Go#215]
Tetris is a puzzling game that can be made in Python code. It begins with an empty box and vertically falling randomized shapes. Put the shapes in order to avoid reaching the utmost border. If it does, you lose! Focus on each shape, and place them in such a way that they fit and make a perfect horizontal row. Perfect rows will get vanished, and you get points. 
So @ssitvit Please assign me to contribute this.

**Comment by admindebu** [comment]
Hi @Meghaa702, could you please elaborate on the features of the game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.
