### ISSUE TITLE
Shooting bird game!

### ISSUE THREAD

**Issue by Shr-reny** [ssitvit/Games-and-Go#216]
Hey, I would like to add a shooting bird game made using html and css only. It's a simple aiming and shooting game which will earn your shoots in points.

**Comment by soorjya** [comment]
Hey, I would like to add a shooting bird game made using html and css only. It's a simple aiming and shooting game which will earn your shoots in points and a gave over system so assignee me this issue under GSSOC'23

**Comment by admindebu** [comment]
Hi @Shr-reny , could you please elaborate on the features of the Crossword game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.

**Comment by Shr-reny** [comment]
![Bird_game](https://github.com/ssitvit/Games-and-Go/assets/125943681/288f010a-5a07-45f5-9a8b-3d64a7251989)
I've added the game in PR #280 and included the readme file too which explains the features.
