### ISSUE TITLE
Chrome Dino Game 

### ISSUE THREAD

**Issue by DEVANSHUKEJRIWAL** [ssitvit/Games-and-Go#220]
i want to add chrome dino game. please assign this under this project to me under GSSoc'23 tag

**Comment by admindebu** [comment]
Hi @DEVANSHUKEJRIWAL , could you please elaborate on the features of the Crossword game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.

**Comment by DEVANSHUKEJRIWAL** [comment]
Can i work upon this??
