### ISSUE TITLE
Alignment error in Readme file.

### ISSUE THREAD

**Issue by Yashshukla11** [ssitvit/Games-and-Go#225]
## Issue:
There is a alignment error in the readme file.

![e1](https://github.com/ssitvit/Games-and-Go/assets/112846526/e59acb35-0958-48e5-bb23-d3f0f69abaf6)

I am willing to contribute to your project.
Kindly assign the issue to me under GSSOC'23.

Thank you

**Comment by Alight-Shivam** [comment]
I am willing to contribute to your project.
