### ISSUE TITLE
Add a game Hangman

### ISSUE THREAD

**Issue by Meenal21i** [ssitvit/Games-and-Go#227]
I want to add a new game called hangman. Please assign mw this issue under GSSOC'23.

**Comment by admindebu** [comment]
Hi @Meenal21i , could you please elaborate on the features of the game with full details, demo / mock UI sample/Video, and tech stack? better share details documentation.

**Comment by ePSA-eJya** [comment]
I would want to work on this issue. I am a GSSOC'23 contributor. please assign me this.
