### ISSUE TITLE
[New Project : GSSOC '23] : Dragons World Game

### ISSUE THREAD

**Issue by sujanrupu** [ssitvit/Games-and-Go#228]
“Dragon’s World” is a game in which one dragon tries to save itself from the other dragon by jumping over the dragon which comes in its way. The score is updated when one dragon saves himself from the other dragon. 

The project will contain **HTML, CSS and JavaScript** files. The HTML file adds structure to the game followed by styling using CSS. JavaScript adds functionality to the game.

**Comment by sujanrupu** [comment]
@raj03kumar please assign me this issue under **GSSOC '23**.

**Comment by sujanrupu** [comment]
@raj03kumar please assign me the issue under GSSOC '23.

**Comment by admindebu** [comment]
Hi @sujanrupu , this is reacting js-based project repo. would be able to make this using react? if yes then share those details please.
could you please elaborate on the features of the game with full details, demo / mock UI sample/Video? better share detailed documentation.
