### ISSUE TITLE
The Dice Game

### ISSUE THREAD

**Issue by srushtikage** [ssitvit/Games-and-Go#232]
Hi I'm a GSSoC'23 Contributor, in this game there will be two dice for two players which will be rolled together and the dice of player with greater value will win.
Please assign this issue to me.

**Comment by ShubhaSwarup** [comment]
please assign this task to me

**Comment by admindebu** [comment]
Hi @ShubhaSwarup , 
could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

**Comment by ShubhaSwarup** [comment]
With the help of html,css and javascript I will make a dice game in which we have two users.The game will work like this:
Score points by rolling the dice. Fist player to 100 wins. If you roll a 1, you lose your turn. If a 6 is rolled twice in a row, you lose all your points and your turn. You can keep your current score and pass by clicking hold. If you want, you can set the winning score to something different in the box.
Please assign this task to me.

**Comment by PayalPadmalyaPrusty** [comment]
@admindebu I want to contribute.Please assign me
