### ISSUE TITLE
The Drumstick Game

### ISSUE THREAD

**Issue by srushtikage** [ssitvit/Games-and-Go#233]
Hi I'm a GSSoC'23 Contributor.
In this issue a game in which there will be images of different instruments on which if we click of press a keyboard key it will play the sound of that instrument with background effect and sound.
Please assign this issue to me.

**Comment by himanshi-sharma-123** [comment]
Hi!! Please assign me this issue, I worked on this project previously!!
![Screenshot 2023-05-27 202233](https://github.com/ssitvit/Games-and-Go/assets/78066781/85a8f210-e680-496c-a886-9aebffd0ada7)

**Comment by srushtikage** [comment]
@himanshi-sharma-123 i have created this issue and i want to work on it if u want you can create another issue.

**Comment by himanshi-sharma-123** [comment]
@srushtikage ok

**Comment by admindebu** [comment]
Hi @srushtikage,
could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.
