### ISSUE TITLE
Adding sudoku game .

### ISSUE THREAD

**Issue by lakshmiprasannakusumanchi** [ssitvit/Games-and-Go#235]
Game logic and basic description:

Sudoku is a logic-based puzzle. It is a type of constraint satisfaction problem, where the solver is given a finite number of objects (the numerals 1-9) and a set of conditions stating how the objects must be placed in relation to one another. The puzzle consists of a 9×9 grid further divided into nine 3×3 sub-grids (also called boxes, blocks, regions, or sub-squares).

Game points

The objective is to place the digits within the grid so that each column, row, and sub-grid contains all of the digits from
1 to 9. Each puzzle is published with some of the boxes already filled in, and those constraints help define the problem's difficulty level.
 
Please assign this to me under gssoc'23

**Comment by AnanyaSDhar** [comment]
@lakshmiprasannakusumanchi  I have already created an issue for this.
