### ISSUE TITLE
Add: Maze Game

### ISSUE THREAD

**Issue by Pragati-3003** [ssitvit/Games-and-Go#240]
I am writing to request the addition of my Maze Game project. 
![maze_game](https://github.com/ssitvit/Games-and-Go/assets/132778037/a4e710af-1e4f-4f1f-af6c-6e8ca7b764c8)
The Maze Game is a fully functional interactive game that challenges players to navigate through a series of mazes. The game features various levels of difficulty, visually appealing graphics

**Comment by Pragati-3003** [comment]
> I am writing to request the addition of my Maze Game project. ![maze_game](https://user-images.githubusercontent.com/132778037/241385865-a4e710af-1e4f-4f1f-af6c-6e8ca7b764c8.jpg) The Maze Game is a fully functional interactive game that challenges players to navigate through a series of mazes. The game features various levels of difficulty, visually appealing graphics

So, please assign this to me under GSSOC'23.

**Comment by admindebu** [comment]
Hi @Pragati-3003, could you please elaborate on the features of the game? Are you going to make it using react js right?
also, share detailed documentation.?
