### ISSUE TITLE
Add : Rubic cube game 

### ISSUE THREAD

**Issue by Pragati-3003** [ssitvit/Games-and-Go#241]
The Rubik's Cube game is a fully functional implementation of the classic puzzle, designed to provide an immersive and engaging experience for users. The game incorporates the standard Rubik's Cube mechanics, allowing players to rotate the different layers of the cube to solve it.
![rubic_cube](https://github.com/ssitvit/Games-and-Go/assets/132778037/510f05f8-6d57-4afe-9a45-ef9560186fda)
So, please assign this to me under GSSOC'23.

**Comment by admindebu** [comment]
Hi @Pragati-3003 , 
could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.
