### ISSUE TITLE
ADD:Smash cube game

### ISSUE THREAD

**Issue by Pragati-3003** [ssitvit/Games-and-Go#242]
I would like to add smash cube game to the repository.
![smash_cube](https://github.com/ssitvit/Games-and-Go/assets/132778037/94269352-820c-4d9f-8284-faed20e23dc2)

This is a game where you have to smash the cubes moving on the screen and earn points.
so,please assign this to me under gssoc'23.

**Comment by admindebu** [comment]
Hi @Pragati-3003 , could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.
