### ISSUE TITLE
[Gssoc'23] Add a reserved copyright footer

### ISSUE THREAD

**Issue by kanishkasah20** [ssitvit/Games-and-Go#244]
![WhatsApp Image 2023-05-27 at 18 55 46](https://github.com/ssitvit/Games-and-Go/assets/114860158/86255b7f-ccb1-493b-b7d1-95ea7a603006)

Make a reserved copyright footer and I will also add social media icons with hover effects.

Please assign this issue to me , thank you for your Consideration!

**Comment by tripathishipra** [comment]
I am interested in contributing to this project. Can you please assign me this issue?

**Comment by admindebu** [comment]
It's already assigned issue
