### ISSUE TITLE
Guess My Number

### ISSUE THREAD

**Issue by khushbumaheshwarii** [ssitvit/Games-and-Go#246]
this a one player game. In this game you have to guess the hidden number if you guess it right you will win else you will lose

> HI @khushbumaheshwarii, could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

![Screenshot (166)](https://github.com/ssitvit/Games-and-Go/assets/81244936/7901c39a-03a5-4701-a518-3744058b7827)
i uploaded a screenshot of the game can please check it

**Comment by singhapeksha** [comment]
Please Assign this to me

**Comment by admindebu** [comment]
HI @khushbumaheshwarii, could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

**Comment by singhapeksha** [comment]
Here is the documentation for the game. Please look into it.
[Guess The Number Game.docx](https://github.com/ssitvit/Games-and-Go/files/11593426/Guess.The.Number.Game.docx)

**Comment by singhapeksha** [comment]
\assign
