### ISSUE TITLE
New page for contributors

### ISSUE THREAD

**Issue by aysal04** [ssitvit/Games-and-Go#248]
Adding a dedicated page to display the contributors of this project

**Comment by admindebu** [comment]
@aysal04 , Please describe what're the benefits of this.  where do you want to add this page and what technology are you going to use?

**Comment by aysal04** [comment]
Using github api we will be fetching the info about contributors. The game they contributed, their profile pic and username will be mentioned. We can create a navbar for better navigation and add a  link to the navbar that shows all contributors of this project. It's just for appreciating their efforts. Kindly please let me know if I can start working on it.
