### ISSUE TITLE
[GSSOC'23] Add a new game : FlipCard

### ISSUE THREAD

**Issue by MisterMickey** [ssitvit/Games-and-Go#249]
**About the Game:** 

FlipCard-Memory Game is a modern version of the classical flip card game in which the user has to pull a card 
and remember what is the symbol in that card when two cards having the same symbol are flipped then those cards vanish.

This is my first-ever contribution to open source, kindly assign me this issue.

![Screenshot from 2023-05-27 23-32-09](https://github.com/ssitvit/Games-and-Go/assets/93720428/498a952a-8d17-4d25-bea7-f5fe7e60615d)
![Screenshot from 2023-05-27 23-32-27](https://github.com/ssitvit/Games-and-Go/assets/93720428/d95937f5-6b22-461e-8d4c-f24e63a750bb)

**Comment by admindebu** [comment]
Hi @MisterMickey , could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

**Comment by MisterMickey** [comment]
Sure @admindebu

The Flipcard Memory Game is a classic memory-matching game where the player's goal is to flip cards and find matching pairs within a certain time limit. Here are the detailed features of the game:

**Landing Page:** There will be 4 cards labelled as F, L, I, & P at the beginning of the game and 3 of them(F, I,&P) will be flippable and 'L' will not be. Flipping 'F' will show Figures(stats including the best score of all three modes, total flips, matched flips and wrong flips), flipping 'I' will show game instructions and flipping 'P' will let us choose between difficulty mode(casual, medium, or hard) after selecting any of the mode game will begin.

**Game Board:** The game board consists of a grid of face-down cards. The number of cards and the grid size can vary depending on the difficulty level or customization options.

**Card Flipping:** The player can select any two face-down cards to flip them face-up. This allows the player to see the images or symbols on the cards.

**Matching Pairs:** The objective is to find matching pairs of cards. When the player flips two cards and they match, both cards vanish from the game board. If the cards don't match, they are flipped back face-down, and the player will continue flipping other cards.

**Time Limit:** The game is played against the clock, meaning there is a time limit for completing the game. The player must match all the pairs before time runs out to win the game. The time limit will be set based on the game's difficulty level or adjustable by the player.

**Difficulty Levels:** The game offers multiple difficulty levels to cater to players of different skill levels. Higher difficulty levels have larger grids and more cards, making it harder to remember the card placements.

**Scoring:** The game can track the player's score based on their performance. Points will be awarded for each successful match.

**Progress Tracking:** The game will keep track of the player's progress and will be displayed to the player by flipping the 'F' card at the end or beginning of the game.

These are some of the core features of a Flipcard Memory Game.  

Please mark this issue as Level-3

**Comment by MisterMickey** [comment]
**Game Screenshots:**

![Screenshot from 2023-05-29 22-33-47](https://github.com/ssitvit/Games-and-Go/assets/93720428/8bc1a99a-70ac-423c-a9fe-29ff36668d6a)
![Screenshot from 2023-05-29 22-33-59](https://github.com/ssitvit/Games-and-Go/assets/93720428/0b4de490-4517-4ddd-bc87-7c1b43ab9495)
![Screenshot from 2023-05-29 22-34-04](https://github.com/ssitvit/Games-and-Go/assets/93720428/d5e257d3-5ad3-4e74-8d3b-5bff8519b67e)
![Screenshot from 2023-05-29 22-34-09](https://github.com/ssitvit/Games-and-Go/assets/93720428/5fee1490-4772-4a7c-9d47-52647e1aba2d)
![Screenshot from 2023-05-29 22-34-17](https://github.com/ssitvit/Games-and-Go/assets/93720428/516998d6-3575-46ff-a893-5f32a67ba4fb)
![Screenshot from 2023-05-29 22-34-20](https://github.com/ssitvit/Games-and-Go/assets/93720428/68f2015e-e333-41f0-93c2-3f89e68b8526)
![Screenshot from 2023-05-29 22-34-31](https://github.com/ssitvit/Games-and-Go/assets/93720428/ba1a8b73-f58b-45f1-988e-efda9784f44c)
![Screenshot from 2023-05-29 22-34-43](https://github.com/ssitvit/Games-and-Go/assets/93720428/806578a1-02c7-45ef-8d17-18e00fa5f2bf)

**Comment by KholoodS** [comment]
Hello is this issue still open for contribution
