### ISSUE TITLE
2048 game 

### ISSUE THREAD

**Issue by Sambhavmahajan11** [ssitvit/Games-and-Go#25]
Create 2048 game using ReactJS

**Comment by Bharadwajshivam28** [comment]
@cleveranu I want to work on it  and  where to deploy the game after making it

**Comment by Subby575** [comment]
PLease assign me this issue

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
