### ISSUE TITLE
[New Game] : Tilting Maze

### ISSUE THREAD

**Issue by trishanu-init** [ssitvit/Games-and-Go#251]
Embark on a thrilling journey through a tilting maze in this captivating game built with HTML, CSS, and JS. Tilt your device or use arrow keys to navigate through an intricate labyrinth, testing your reflexes and problem-solving skills. With stunning visual effects and smooth animations, immerse yourself in a dynamic gameplay experience. Collect power-ups and unlock new levels as you strive to reach the maze's elusive exit. Get ready for an addictive and mind-bending adventure that will keep you engaged for hours

Could you please assign this issue to me under GssoC'23 , i have everything ready i just need to commit the changes.

**Comment by admindebu** [comment]
Hi @trishanu-init , This is react js-based repo. would you be able to make it using react js? if yes then share the below details.
 elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

**Comment by trishanu-init** [comment]
> Hi @trishanu-init , This is react js-based repo. would you be able to make it using react js? if yes then share the below details. elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

Yes , i will update you regarding that and i will make sure that it has proper documentation.
