### ISSUE TITLE
[New Game]: Snake and Ladder game

### ISSUE THREAD

**Issue by whiteknight16** [ssitvit/Games-and-Go#254]
The age-old classic Indian Snake and ladder game made using HTML CSS and JS. Support of up to 4 players. Classic rules.Kindly assign this issue to me

**Comment by soorjya** [comment]
The age-old classic Snake and ladder game made using HTML CSS and JS. Support of up to 4 players.Kindly assign this issue to me under GSSOC'23 i have made similar game to this so it should not be a issue for me.

**Comment by admindebu** [comment]
Hi @whiteknight16 , could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

**Comment by whiteknight16** [comment]
Will try to make the game with classic rules. Supporting up to 4 players. I am currently learning web sockets so will try to make it online multiplayer else it will be offline multiplayer. The game will proceed in a turn-by-turn manner all regular snake and ladder type.

**Comment by Shreyaar12** [comment]
@whiteknight16 This repo is based on React js so please ensure you work on react js
