### ISSUE TITLE
[GSSOC'23] [New Game]: Guess Number🍉.

### ISSUE THREAD

**Issue by AVUKU-PRAGATHESWARI** [ssitvit/Games-and-Go#259]
Guess-Number Game can be played very easily.
The user just needs to type the number in the input field.

👉And based on the number it will show the hint like:
✔️Whether the guessed number is less than the desired number.
✔️Whether the guessed number is greater than the desired number.
✔️Else your guess is exactly correct so it will show Your "Guess is Right".

👉This is how the Game flow will happen.

🍉Hope you like the game.

**Comment by AVUKU-PRAGATHESWARI** [comment]
[https://github.com/ssitvit/Games-and-Go/pull/257](url)

**Comment by MisterMickey** [comment]
I guess this game is already in the repository.

**Comment by admindebu** [comment]
Hi @AVUKU-PRAGATHESWARI ,
could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

**Comment by AVUKU-PRAGATHESWARI** [comment]
The Game to Guess a random number
