### ISSUE TITLE
Enhancement: Add games logo/images instead of blank screen background

### ISSUE THREAD

**Issue by dhairyaostwal** [ssitvit/Games-and-Go#26]
@vibgyor786 @Shreyaar12 @nandurijv Can we add images in these blank screens which upon hover shows more info about the game(currently functional). Leaving blank screen isn't a good idea. 

Views? 

<img width="1158" alt="Screenshot 2022-10-28 at 11 27 34" src="https://user-images.githubusercontent.com/50984984/198514161-f9494070-59e6-448c-9b28-3045abfde3cf.png">

Much thanks! Cheers!

**Comment by Shreyaar12** [comment]
Yes! it will surely improve the UI

**Comment by Bharadwajshivam28** [comment]
@cleveranu Please assign me under GSSOC

**Comment by AishwaryVishwa** [comment]
@Shreyaar12  please assign it to me I can solve this issue

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by babitarit** [comment]
could you please assign me this issue

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Vickyaryan33** [comment]
@dhairyaostwal Please assign it to me I can solve this issue

**Comment by Atharvasharma12** [comment]
@dhairyaostwal,
Please assign this task to me i can include this enhancement.
I am a contributer of GSSoC'23.

**Comment by Shreyaar12** [comment]
@Bharadwajshivam28 assigning this to you kindly complete within a week. All the best!!
