### ISSUE TITLE
[New Game :] LOVE CALCULATOR

### ISSUE THREAD

**Issue by shivani-tripurari** [ssitvit/Games-and-Go#261]
Love Calculator game is a pretty fun yet simple game which was very popular in the 2000's.

The interface will be made using basic html , css and javascript

The game takes 2 names as input and gives the % of "Love" between the partners and with a special message to the users.

If you liked the idea please do tell me and i could show you the prototype/design of the game. 

@cleveranu

**Comment by singhapeksha** [comment]
Please assign this to me

**Comment by admindebu** [comment]
Hi @shivani-tripurari ,

could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

**Comment by shivani-tripurari** [comment]
> Hi @shivani-tripurari ,
> 
> could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

Hey! 
Here is the demo interface of the game. 

- This game basically takes 2 names as inputs. 
- Calculates a score with the help of JavaScript. 
-Gives a special message based on the score. 
-The interface of the website is made using HTML and CSS. 

![IMG_20230529_231845.jpg](https://github.com/ssitvit/Games-and-Go/assets/96899982/8f9f3a2b-be07-4436-949e-fa55535edd40)

I'm still working on the project, once done I'll share you the working video of the game.

**Comment by shivani-tripurari** [comment]
@admindebu 
Hey!!
Here is the working demo of the game : )
This is a fun game, hope you like it.

https://github.com/ssitvit/Games-and-Go/assets/96899982/d21a780c-dd57-45e6-8266-e28b814598fc

**Comment by PayalPadmalyaPrusty** [comment]
@admindebu I want to contribute.Please assign me
