### ISSUE TITLE
Memory card game

### ISSUE THREAD

**Issue by Enhancer18** [ssitvit/Games-and-Go#265]
Game logic and basic description
Matching cards gains points. Counts the points and times.

**Comment by ShubhaSwarup** [comment]
please assign this task to me

**Comment by admindebu** [comment]
Hi @Enhancer18 ,
could you please elaborate on the features of the game with full details, demo / mock UI sample/Video,? better share detailed documentation.

**Comment by Enhancer18** [comment]
plz close this issue as the pull request has been merged. Pull request #346
@panwar8279

**Comment by Enhancer18** [comment]
@panwar8279 can I ask why you reopened this issue?

**Comment by Enhancer18** [comment]
@panwar8279 this issue is not shown in the leaderboard. Why isn't it shown?
