### ISSUE TITLE
ROG (Run On Gun)

### ISSUE THREAD

**Issue by 584aditya** [ssitvit/Games-and-Go#27]
ROG (Run On Gun) is a Shooting Game where users can enjoy the game launched back in the '90s. This Shooting Game is with some more Enhanced features and UI where users can better interact with the game with ease and without getting stuck.

It can be Build in Front end technologies with some sort of Python Codes.

**Comment by admindebu** [comment]
HI @584aditya , please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.

**Comment by vk20july** [comment]
@admindebu sir i want to work on this issue under gssoc'23
