### ISSUE TITLE
[GSSOC'23 Contribution]: Connect Four Game

### ISSUE THREAD

**Issue by varunshankar07** [ssitvit/Games-and-Go#270]
Connect Four is a competitive game where players strategize and try to out manoeuvre their opponent by strategically placing their coloured discs in a grid. The game requires critical thinking and planning ahead to block the opponent's moves while setting up opportunities for their own victories. The player who successfully connects four discs of their colour first wins the game. ☺️💿

Features : 🚚🤺
1. Disc Colours: Players choose their preferred colour, often represented by red and yellow discs.
2. Turn-Based Gameplay: Players take turns dropping one disc at a time into the grid.
3. Win Conditions: The game detects and declares a winner if a player successfully connects four of their discs in a row, horizontally, vertically, or diagonally.
4. Simple User Interface: The game features an intuitive and user-friendly interface for easy interaction.

Tech Stacks : [Html, Css And Javascript]

Screenshots: 

![1](https://github.com/ssitvit/Games-and-Go/assets/82266277/59711fc3-06ca-471c-acfb-e9cff05644f1)
![2](https://github.com/ssitvit/Games-and-Go/assets/82266277/59b2f2ad-0088-402b-847a-ac229bb72d38)
![3](https://github.com/ssitvit/Games-and-Go/assets/82266277/519d8a2e-3cf0-44e9-96c8-626b859dbf94)

**Comment by varunshankar07** [comment]
@admindebu Could You Look Into This! 😊

**Comment by singhapeksha** [comment]
Please Assign this to me

**Comment by panwar8279** [comment]
Hi @singhapeksha , Assigned this issue to you. Kindly complete the work and also go through the readme and contributing.md for successful merge. All the best to your work.

**Comment by varunshankar07** [comment]
@panwar8279 Hey I raised the issue because i wanted to work on this.. i think this is some confusion.. could you please assign this to me.

**Comment by varunshankar07** [comment]
@panwar8279 I Have The Game Ready To Make A PR.

**Comment by panwar8279** [comment]
hi @varunshankar07 ,I am assigning this issue to you. Kindly complete the work and also go through the readme and contributing.md for successful merge. All the best to your work.

**Comment by varunshankar07** [comment]
thank you☺️
