### ISSUE TITLE
[GSSOC 2023 Contribution ] Add animation to the background .

### ISSUE THREAD

**Issue by ManishaSwain8** [ssitvit/Games-and-Go#28]
I would like to work upon it ,as the UI is very simple want to make it look more alive under GSSOC 2023.
Do assign it to me! @Shreyaar12

**Comment by raj03kumar** [comment]
Kindly add the preview of the animation here.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly go through the readme and contributing.md for the project for successful merge. All the best to your work Manisha... !!!

**Comment by ManishaSwain8** [comment]
> Kindly add the preview of the animation here.

soon I will add the preview of my idea before pull req. :)
