### ISSUE TITLE
[ New Game ] : Car game { GSSOC'23 }

### ISSUE THREAD

**Issue by md-rosh02** [ssitvit/Games-and-Go#281]
I Think you like it😍

![Screenshot (49)](https://github.com/ssitvit/Games-and-Go/assets/132879891/ed788729-47b3-4ada-9b34-2c248d4650eb)
![Screenshot (50)](https://github.com/ssitvit/Games-and-Go/assets/132879891/862c4018-2116-4b87-9174-2c7b47461871)

**Comment by panwar8279** [comment]
Hi @md-rosh02 ,I am assigning this issue to you. Please complete the work within a week and also go through the readme and contributing.md for successful merge. All the best to your work.

**Comment by md-rosh02** [comment]
@panwar8279  I have completed this work and I have this Project ready plz guide me to make successful PR

**Comment by md-rosh02** [comment]
@panwar8279 i did how you told then check my PR

**Comment by md-rosh02** [comment]
@panwar8279 plz merge my PR
