### ISSUE TITLE
Block Puzzle 

### ISSUE THREAD

**Issue by saniyabangwal** [ssitvit/Games-and-Go#288]
![Screenshot (23)](https://github.com/ssitvit/Games-and-Go/assets/75465479/3fb65b9a-6bf3-42d1-9b29-c0885329e1be)

I want to add a Block puzzle game using Python

When a block land at the bottom the next block will begin to fall. Your goal is to clear lines by manipulating the pieces so that they fill horizontal row. To clear a line, every square of the row has to be filled.

**Comment by saniyabangwal** [comment]
can you please assign me this issue under GSSoC'23 label

**Comment by singhapeksha** [comment]
Can you please assign this issue to me

**Comment by panwar8279** [comment]
Hi @saniyabangwal, I assigned this issue to you. Please complete the work within a week and go through the readme and contributing.md for successful merge.
