### ISSUE TITLE
Chess Game

### ISSUE THREAD

**Issue by i-am-yuvi** [ssitvit/Games-and-Go#29]
I can add a Chess in the game section.

**Comment by Aditi323** [comment]
I would like to work on this project. Please assign it to me.

**Comment by aniketburman014** [comment]
I would like to work on this project.

**Comment by AdhiRaj08** [comment]
Please assign me this issue under GSSOC'23

**Comment by admindebu** [comment]
Hi @i-am-yuvi , please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.

**Comment by sumitkr2000** [comment]
hey @raj03kumar if he is not working on it can I work on this issue? Please assign me this issue. I can work on it.
