### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by Illuminati9** [ssitvit/Games-and-Go#293]
Implementing the classic mathematical puzzle game Tower of Hanoi. Players need to move a tower of disks from one peg to another, following the rules of the game.

**Comment by panwar8279** [comment]
Hi @Illuminati9, I assigned this issue to you. Please complete the work within a week and go through the readme and contributing.md for successful merge.

**Comment by PayalPadmalyaPrusty** [comment]
@panwar8279 I want to  contribute.Please assign me
