### ISSUE TITLE
[NEW GAME]:  FRANTIC RUN OF VALOROUS RABBIT (3D)

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#296]
### DESCRIPTION :
- This game is about a frantic run of an valorous rabbit, which may run endless. Yeah this is an endless running game
- This game's graphics is some similar like Roblox's graphics
- Quite addictive game, which may be fun for so many peoples

### PREVIEW :
![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/cb9cb8e6-dc95-44fc-a853-9491fd5a8da7)

### POSTSCRIPT :
- I would like to contribute this game to this repository, so kindly assign me this issue under `gssoc23`.
- Regards!

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid, I assigned this issue to you. Please complete the work within a week and go through the readme and contributing.md for successful merge.

**Comment by 0xabdulkhalid** [comment]
Sorry for the inconvenience, i wish i can add the game in plain Html, css & Js. I'm closing this Issue.

Thank you!
