### ISSUE TITLE
Ping Pong Game 

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Games-and-Go#3]
Create a Ping Pong Game using React.js

**Comment by priyam212001** [comment]
Hey, @Shreyaar12  assign me this issue. I will try to create this game as soon as possible. If you want to see my work please visit my LinkedIn profile: https://www.linkedin.com/in/priyam-mishra-31843a205/

**Comment by rt-001** [comment]
I would like to work on this issue.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Shreyaar12** [comment]
@priyam212001 assigned the issue to you, make sure you complete it within 10 days

**Comment by priyam212001** [comment]
Sure!

**Comment by priyam212001** [comment]
Can I use JS as a language?

**Comment by ManasaKaza** [comment]
Hi @Shreyaar12 I would like to work on this issue under GSSoC

**Comment by priyam212001** [comment]
Hi, @Shreyaar12  I have completed this project in JS. So, If you don't mind can I request to merge this project into your project?
