### ISSUE TITLE
[GSSOC 2023 Contribution ] Adding music feature to background.

### ISSUE THREAD

**Issue by ManishaSwain8** [ssitvit/Games-and-Go#30]
As it is a gaming platform, Adding video game background music is a fair deal !
To make it more attractive and alive ,I would like @Shreyaar12 to assign this issue to me under GSSOC 2023.

**Comment by Aditi323** [comment]
I would like to work on this project. Please assign it to me.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Try to use very low and slow sound in the background like in the games. Kindly complete the work within a week and go through the readme and contributing.md for successful merge. All the best to your work Manisha... !!!
