### ISSUE TITLE
Add Wordle Game

### ISSUE THREAD

**Issue by ishita80** [ssitvit/Games-and-Go#303]
# Description
Wordle is a word guessing game where the player has to guess a 5 letter word.
Player is given 6 guesses.

# How-To-play
- Computer generates a random word which the player has to guess.
- Player makes a 5 letter word guess.
- Then after enter, the square tiles change its color according to the following color coding scheme:
  Correct letter with correct position - GREEN
  Correct letter with wrong position - YELLOW
  Wrong letter - GREY
- Keyboard keys also change their color according to same color scheme(after a guess is made).
- If the player guesses the correct word, he/she receives a congratulations message.
- If the player cannot make the guess and exhausts all the guesses, he/she loses the game.

Please assign me this issue to work on  for GSSoc'23
<img width="239" alt="wordle" src="https://github.com/ssitvit/Games-and-Go/assets/121221158/b9931cac-8e8d-4f01-84a1-1401920d7b80">

**Comment by panwar8279** [comment]
Hi @ishita80 ,I assigned this issue to you. Please complete the work within a week and go through the readme and contributing.md for successful merge.

**Comment by ePSA-eJya** [comment]
i would want to work on this issue. i am a gssoc 23 contributor. please assign this issue to me @panwar8279
