### ISSUE TITLE
[Feature Request]: Search bar

### ISSUE THREAD

**Issue by c0mpli** [ssitvit/Games-and-Go#305]
### Search bar 
Add a a search bar so that people can search for the games easily.

## Implementation of search bar

1. Add a input field
2. Store the input in a variable.
3. Return the set of games which contain the letters searched

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by AVUKU-PRAGATHESWARI** [comment]
I would like to work on the issue as a contributor of GSSoC23.
Please assign me the issue.
