### ISSUE TITLE
[Feature Request]: The box is not looking great for the Tic-Tac-Toe. Assign me the issue I will work on it.

### ISSUE THREAD

**Issue by AVUKU-PRAGATHESWARI** [ssitvit/Games-and-Go#313]
### How would you like to enhance the existing project.

Enhancement

### Describe breifly how would you implement the same.

Solution steps:

Modified Tic Tac Toe UI so that it looks more beautiful and approachable...

[Before:]
![Screenshot (95)](https://github.com/ssitvit/Games-and-Go/assets/117664019/9fe13948-1c65-4d46-83c6-7ab2697ef0a1)

After::: 
![Screenshot (92)](https://github.com/ssitvit/Games-and-Go/assets/117664019/0d165521-660e-42d1-8a6a-5c98e39f7e39)

✔️Features Added 👍:
👉Given A dropdown list for Rules so that , when clicking rules it will display rules and when we click the results again it will close the rules.
👉Modified the Grid from to unstructured manner to a structured grid(3X3).

Consider my pull request and hope it is useful . Please consider and merge it.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by AVUKU-PRAGATHESWARI** [comment]
please assign me the issue.

**Comment by Rakesh-code65** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task .
