### ISSUE TITLE
[Feature Request]: UI changing in Rock-Paper-Scissors Game.

### ISSUE THREAD

**Issue by AVUKU-PRAGATHESWARI** [ssitvit/Games-and-Go#314]
### How would you like to enhance the existing project.

Enhancement

### Describe breifly how would you implement the same.

Solution steps:

Modified Rock-Paper-Scissors Game UI so that it looks cleaner and more visible. Check out the changes by comparing the images.

Before:
![Screenshot (99)](https://github.com/ssitvit/Games-and-Go/assets/117664019/51e7dae8-ec12-480f-8b05-b92fdbf2f87b)

After::
![Screenshot (98)](https://github.com/ssitvit/Games-and-Go/assets/117664019/27d36c4e-0106-412f-8b5d-b55ea5cd511a)

✔️Feature Added:

👉Changed the score displaying UI. To make the score more visible.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by AVUKU-PRAGATHESWARI** [comment]
Please assign me the issue as a contributor of GSSoC23.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly get it done within a week. All the best to your work....
