### ISSUE TITLE
[Feature Request]: aligning botom section of Typo game

### ISSUE THREAD

**Issue by gitssz** [ssitvit/Games-and-Go#316]
### How would you like to enhance the existing project.

Enhancement: I would like to shift the bottom part of Typo game to the center and make the overlapping letters clear.
I would also like to add a colon[:] between player score in the dice game.
![Screenshot from 2023-06-01 18-22-36](https://github.com/ssitvit/Games-and-Go/assets/83583240/e29344cc-faf6-4945-b4d6-02049ce3dac3)

### Describe breifly how would you implement the same.

Solution_steps
1) In the typo game, i could just add a <br> tag between the time remaining and the score 
2) And then i could center them with align tag in css file
3) In the dice game i could just add a <span> tag with colon in it.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by gitssz** [comment]
Yeah will do. Can i also improve the UI of Typo game a bit. The text seems too cluttered and the textarea could be properly aligned aswell.

**Comment by gitssz** [comment]
Hey

**Comment by raj03kumar** [comment]
Alright. Assigned this issue to you. Get it done within a week.
