### ISSUE TITLE
[Documentation Addition]:  show all the latest contributors in README

### ISSUE THREAD

**Issue by kshitijarvikar** [ssitvit/Games-and-Go#318]
### Also, describe the documentation you want to add. ✍️

We can display all the active and latest contributors on README.md file

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by linga66** [comment]
i want to work on this issue

**Comment by Harshu467** [comment]
I feel I can contribute , Can u please assigned me this work??

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week. All the best to your work.
