### ISSUE TITLE
Snake game

### ISSUE THREAD

**Issue by nishita2104** [ssitvit/Games-and-Go#32]
Adding a simple yet nostalgic snake game would add more to the site's functionalities. Please assign it to me under GSSOC'23.

**Comment by aniketburman014** [comment]
I would like to work on this project. Please assign it to me.

**Comment by anveshajain19** [comment]
I am Anvesha Jain, I have earlier made a snake game in Python and Flutter please assign it to me under GSSOC'23.

**Comment by AMAN-BAGADIYA** [comment]
Hello, I am Interested in contributing to this project .I am Skilled in web development and i am ready to collaborate and follow project guidelines.

**Comment by anveshajain19** [comment]
Thank you for assigning it to me.

**Comment by purviporwal0** [comment]
I would love to contribute to this issue Pls assign this to me

**Comment by rv1830** [comment]
please assign this to me

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
