### ISSUE TITLE
[Bug]: Flappy bird game is not showing on the website

### ISSUE THREAD

**Issue by sumitkr2000** [ssitvit/Games-and-Go#321]
### Give a brief about the bug discovered✍

Hey @raj03kumar I found that the flappy game was merged in the repo but it is not showing on the website. Please assign me this issue. I can fix it.

### What is the expected behavior?

Show the flappy bird game on the website.

### Give a brief description to get the expect behaviour.

Add flappy bird games in the routes

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @sumitkr2000, I assigned this issue to you. Please complete the work within a week and go through the readme and contributing.md for successful merge.

**Comment by sumitkr2000** [comment]
Yeah sure!

**Comment by sumitkr2000** [comment]
Hey @panwar8279 this game is made with html css and js. So can't include it in the router file. What should I do???

**Comment by sumitkr2000** [comment]
Your description says that all the games should be made with react.
