### ISSUE TITLE
Adding a Boxing Game

### ISSUE THREAD

**Issue by shubham-mookim** [ssitvit/Games-and-Go#323]
### How would you like to enhance the existing project.

Wanted to add a boxing game like taken 3

### Describe breifly how would you implement the same.

Solution_steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @shubham-mookim , I am assigning this issue to you, kindly complete your work within a week. Good luck for you game.
