### ISSUE TITLE
[Feature Request]: Want to add AI mode in Tic-Tac-toe

### ISSUE THREAD

**Issue by AyishikD** [ssitvit/Games-and-Go#324]
### How would you like to enhance the existing project.

I want to add AI mode in Tic-Tac-Toe game which will help the users to play alone without any other player.

### Describe breifly how would you implement the same.

I will implement it using javascript logic and algorithm. Also I have readymade code available for that.
![image](https://github.com/ssitvit/Games-and-Go/assets/99983449/4679841e-0002-4f9e-b3df-9bf79a7362bd)
![image](https://github.com/ssitvit/Games-and-Go/assets/99983449/8b69d8ac-5789-4a44-ae9c-e006c5a91991)

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @AyishikD , I am assigning this issue to you. Kindly complete your work within a week. Good luck for your work.

**Comment by AyishikD** [comment]
Thank you so much for assigning me. I will surely complete it within one week.
