### ISSUE TITLE
Start again card in ball Shooting game

### ISSUE THREAD

**Issue by 9520prashant** [ssitvit/Games-and-Go#325]
### Give a brief about the bug discovered✍

when I play the ball shooting game and it gets over then the position of game over card was very below in the game screen. You can see in the screen shot :

![Screenshot (288)](https://github.com/ssitvit/Games-and-Go/assets/99237795/ba399f6f-416d-4c41-a97a-749d3240f1ae)

### What is the expected behavior?

It should be something like this 

![Screenshot (287)](https://github.com/ssitvit/Games-and-Go/assets/99237795/d9ea1205-9918-40de-bdf0-ff248d605863)

### Give a brief description to get the expect behaviour.

when I play the ball shooting game and it gets over then the position of game over card was very below in the game screen.
please assign me this issue under gssoc

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @9520prashant, I am assigning this issue to you. Kindly complete within a week. Good luck for your work.

**Comment by 9520prashant** [comment]
> Hi @9520prashant, I am assigning this issue to you. Kindly complete within a week. Good luck for your work.

@panwar8279 Sure, Thanks
