### ISSUE TITLE
Add simon game

### ISSUE THREAD

**Issue by sumitkr2000** [ssitvit/Games-and-Go#33]
hey @Shreyaar12 I want to add simon game to your repo. Please assign me this issue. Thank you!

**Comment by Samriddhi15** [comment]
I have experience in JavaScript game development and I am confident that I can successfully implement the Simon game into our project. please assign me this issue.

**Comment by sumitkr2000** [comment]
@Samriddhi15 i have raised this issue and will work on it. Please raise another issue if you want yo contribute. Thank you!

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week and go through the readme and contributing.md for successful merge. All the best to your work Sumit... !!!

**Comment by sumitkr2000** [comment]
@raj03kumar yeah sure!

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue

**Comment by sumitkr2000** [comment]
I am working on this. Please raise another issue.

**Comment by sumitkr2000** [comment]
Hey @raj03kumar I found that this game is already added by another contributor. So I am closing this issue.
