### ISSUE TITLE
[Feature Request]: Single Button for Music On/Off

### ISSUE THREAD

**Issue by ManasMadan** [ssitvit/Games-and-Go#339]
### How would you like to enhance the existing project.

Enhancement : Instead of two buttons for music control there can be a single button for music control that too on the bottom left of the site so one can toggle it from any scroll position

### Describe breifly how would you implement the same.

I Will Remove the buttons for music on/off and instead following the same design language create a new button for the same

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by ManasMadan** [comment]
@panwar8279 Please assign this issue to me under GSSoC 23

**Comment by panwar8279** [comment]
Hi @ManasMadan , I am assigning this issue to you, kindly complete within a week . Good luck for your work.

**Comment by ManasMadan** [comment]
Have Created a PR #366, Merging that closes this issue
