### ISSUE TITLE
Improving the readme file of this project 

### ISSUE THREAD

**Issue by harshsingh32** [ssitvit/Games-and-Go#34]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by SamridhiNancy** [comment]
I Would like to work on this issue, please assign this issue to me under GSSOC'23'.

**Comment by harshsingh32** [comment]
Assign this issue to me under GSSoC'23, I would like to work on this issue.
