### ISSUE TITLE
New Game: Space Invaders Game

### ISSUE THREAD

**Issue by nikhilkumar50** [ssitvit/Games-and-Go#341]
Space Invaders is a classic game commonly found at any retro-based arcade
I would love to work on this plz assign .

**Comment by panwar8279** [comment]
Hi @nikhilkumar50 , I assigned this issue to you, please complete you work within a week. Good luck nikhil.

**Comment by mubasharaKhan** [comment]
Assign me this issue under GSSoC'23 label
