### ISSUE TITLE
[New Game]: Pac - Man 

### ISSUE THREAD

**Issue by Poonam-13** [ssitvit/Games-and-Go#350]
### Description

Pac-Man is a classic arcade game where players control a character named Pac-Man to navigate through a maze filled with dots and avoid ghost enemies. The objective is to eat all the dots in the maze while avoiding the ghosts. Power pellets are available to temporarily turn the tables, allowing Pac-Man to eat the ghosts. The game ends when all the dots are eaten, or when a ghost captures Pac-Man.

### Screenshots

![243197351-3451465b-0f99-46b5-8813-ab8db029891d](https://github.com/ssitvit/Games-and-Go/assets/103939318/f49731b4-c4fd-4adc-a7e2-4153523a7f41)

https://github.com/ssitvit/Games-and-Go/assets/103939318/c8d08bc5-437f-415f-89bd-f40e510dd5fd

## Point down the features

- Classic gameplay inspired by the original Pac-Man arcade game.
- Use arrow keys or touch gestures to control Pac-Man's movement.
- Engaging maze layout with dots and power pellets.
- Colorful graphics and visually appealing game elements.
- Dynamic ghost AI that presents challenges and strategies.
- Score tracking to keep a record of the player's progress.
- Audio effects and background music for an immersive experience.

## Are you contributing for a program?
GSSoC23

## Code of Conduct
I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Poonam-13, I am assigning this work to you. Kindly complete within 2 week. Good luck for your work.
