### ISSUE TITLE
[Feature Request]: Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [ssitvit/Games-and-Go#351]
### How would you like to enhance the existing project.

**Issue:** The website does not have meta tags with descriptions.

**Impact:** This means that the website is not as visible in search results, and users are less likely to click on the website's links.

### Describe breifly how would you implement the same.

I would like to add meta tags with descriptions to all of its pages. This will help the website rank higher in search results and attract more visitors.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by panwar8279** [comment]
Hi @Avinash905 , I am assigning this issue to you, kindly complete work within a week. Good luck for you work.

**Comment by Avinash905** [comment]
Thank you, can you also add the GSSoC'23 label also

> Hi @Avinash905 , I am assigning this issue to you, kindly complete work within a week. Good luck for you work.
