### ISSUE TITLE
Improve Navbar and Scroll Effect

### ISSUE THREAD

**Issue by Ayush9951** [ssitvit/Games-and-Go#354]
### Description

Hi, @panwar8279, I am a contributor in GSSOC'23.
I want to work on Improving the Navbar and scroll effect
Navbar doesn't have equal margin and padding. 
Scroll bar animation is not smooth.
please assign me this task under label gssoc'23.

### Screenshots

![Screenshot 2023-06-05 124711](https://github.com/ssitvit/Games-and-Go/assets/60573378/b54910a5-6cc7-4769-9c52-8a8e41089a4a)

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week. All the best to your work.
