### ISSUE TITLE
Proposal for newly awesome Color Match Game

### ISSUE THREAD

**Issue by urz-ahmed** [ssitvit/Games-and-Go#36]
Dear Project Maintainer,

I hope this message finds you well. I am writing to express my sincere interest in contributing to your project. The work you have accomplished so far has truly impressed me, and I would be honored to be a part of its success.

Here's a simple game called "Color Match" that you can build using ReactJS and CSS only. The objective of the game is to match the color of the target box with the color of one of the selectable boxes. 
Please assign me this issue to work under gssoc'23.
Best regards,
Urooz

**Comment by admindebu** [comment]
Hi @urz-ahmed , please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.
