### ISSUE TITLE
[FEATURE] <Loop the pacman animation>

### ISSUE THREAD

**Issue by raj03kumar** [ssitvit/Games-and-Go#367]
### Description

Loop the pacman animation so that it is always running.

**Comment by ManasMadan** [comment]
@raj03kumar actually have too many issues assigned at this moment would be better if someone else get to work on this

**Comment by Anjali2312-Thombare** [comment]
@ManasMadan  i would like to solve this issue please assign it to me

**Comment by vk20july** [comment]
@raj03kumar sir i want to work on this issue under gssoc'23

**Comment by raj03kumar** [comment]
@Anjali2312-Thombare Assigned this issue to you. Kindly get it done in 2 weeks. All the best to your work.
