### ISSUE TITLE
[GSSOC'23 Contribution]: Wordle

### ISSUE THREAD

**Issue by pshantanu771** [ssitvit/Games-and-Go#37]
I'd like add a simple yet engaging **Wordle Game** using **HTML, CSS** , **BOOTSTRAP** and **jQuery** where players will have to guess a randomly generated 5 letter word within limited number of attempts. I'll also make the UI responsive.

**Features:**

- Responsive UI
- Showing which letter are correct and which are wrong if user guesses it wrong
- Also showing if the letter is at correct position or not
- Option to opt for an hint in exchange with 1 reduced attempt
- Showing the correct word if all the attempts are exhausted

Please assign this issue to me under **GSSOC'23**.

**Comment by admindebu** [comment]
HI @pshantanu771 , please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.
