### ISSUE TITLE
 [Feature Request]: 2048 game addition 

### ISSUE THREAD

**Issue by Anjali2312-Thombare** [ssitvit/Games-and-Go#372]
### How would you like to enhance the existing project.

i will add 2048 game in your website  

### Describe breifly how would you implement the same.

Solution_steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by Anjali2312-Thombare** [comment]
@panwar8279  please assign me this issue under gssoc 2023

**Comment by panwar8279** [comment]
Hi @Anjali2312-Thombare, I am assigning this to you.Kindly complete within a week. Good luck for your work.

**Comment by Anjali2312-Thombare** [comment]
@panwar8279 Thank you and I am grateful about it
