### ISSUE TITLE
Thumbnail or Cover for cards

### ISSUE THREAD

**Issue by suzy-g38** [ssitvit/Games-and-Go#38]
The cards is showing content after we hover, otherwise, it is blank.
If we add a thumbnail or a cover or make it static that will give a better look.
These are the cards look like when we don't hover.
![image](https://github.com/ssitvit/Games-and-Go/assets/62666287/729fe1e1-43bc-48fe-ba9b-64289c979680)

I would like to work on it under gssoc23

**Comment by harmeetsingh11** [comment]
I am a GSSoC'23 contributor. Can I work on this issue?

**Comment by admindebu** [comment]
Hi @suzy-g38 ,please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.
