### ISSUE TITLE
Spin a Wheel present in the repo is not made using react

### ISSUE THREAD

**Issue by sumitkr2000** [ssitvit/Games-and-Go#381]
### Description

Hey @panwar8279 I just found that the Spin a Wheel game in the repo is made using HTML CSS and vanilla js. It's not made using react. Please assign me this issue I will remove it. Thank you!

**Comment by raj03kumar** [comment]
@sumitkr2000 There are many duplicate issue which you have opened so we can't assign all these to you. Kindly make a single PR and remove all the unnecessary files.

**Comment by sumitkr2000** [comment]
Okay bro Ill make a single pr only :)

**Comment by sumitkr2000** [comment]
Also, there is another issue that I raise in which I asked to add a path for the Tetris game, I  will make a separate pr for that.

**Comment by sumitkr2000** [comment]
Made a single pr for removing unwanted files. So closing this issue.
