### ISSUE TITLE
Proposal for an awesome Duck Hunt Game

### ISSUE THREAD

**Issue by MohnishK7** [ssitvit/Games-and-Go#39]
Dear Project Maintainer,

I hope this message finds you well. I am writing to express my sincere interest in contributing to your project. The work you have accomplished so far has truly impressed me, and I would be honored to be a part of its success.

Here's a simple game called "Duck Hunt Game" that you can build using **Python & PyGame Game**. The objective of the game is to shoot moving targets on the screen in mid-flight. The game is played from a first-person perspective and requires the **NES Zapper light gun,** which the player aims and fires at the screen.
Please assign me this issue to work **under gssoc'23.**
Best regards,
Mohnish Kumar

**Comment by MohnishK7** [comment]
Please assign me this issue to work under gssoc'23.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week and go through the readme and contributing.md for successful merge. All the best to your work Mohnish... !!!

**Comment by MohnishK7** [comment]
@raj03kumar sir please assign me for this project .

**Comment by admindebu** [comment]
Hi @MohnishK7 , please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.

**Comment by MohnishK7** [comment]
@admindebu ok I will get back to you soon with plan and dummy video
