### ISSUE TITLE
[FEATURE] <description>Dice Game

### ISSUE THREAD

**Issue by shivani-tripurari** [ssitvit/Games-and-Go#390]
### Description

Dice game is a simple yet fun game which is made using html , css and javascript.
Here is the screeshot and video of the game !
![Screenshot (11)](https://github.com/ssitvit/Games-and-Go/assets/96899982/231c0550-1a6a-4e11-a6fa-39adc09a9eb4)

https://github.com/ssitvit/Games-and-Go/assets/96899982/96037501-f4ab-49d8-81d6-53a831fad3cf

**Comment by shanu-user** [comment]
I am interested to develop this portion .Please assign me this issue

**Comment by panwar8279** [comment]
Hi @shivani-tripurari, I am assigning this work to you. Kindly complete within a week. Good luck shivani!

**Comment by shivani-tripurari** [comment]
> Hi @shivani-tripurari, I am assigning this work to you. Kindly complete within a week. Good luck shivani!

Yeah sure!

**Comment by vk20july** [comment]
@panwar8279 mam i want to work on this issue under gssoc'23
