### ISSUE TITLE
Improve Styling

### ISSUE THREAD

**Issue by Ayush9951** [ssitvit/Games-and-Go#398]
### Description

Hi @raj03kumar, I am a contributor in GSSOC'23.
Game on title and search input field doesn't have proper margin-top.
I want to work on fixing this issue.
please assign me this issue under label gssoc'23

### Screenshots

![Screenshot 2023-06-07 134932](https://github.com/ssitvit/Games-and-Go/assets/60573378/eaf1b0f4-a613-410d-a8ba-2d0358fea3d9)

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week. All the best to your work...
