### ISSUE TITLE
Rock Paper Scissors

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Games-and-Go#4]
Create a Rock Paper Scissors game using React

**Comment by priyam212001** [comment]
hey @Shreyaar12, I want to create this game. I have experience in react. Please assign it to me.

**Comment by rt-001** [comment]
I have created game using react and I would like to work on this issue.

**Comment by aniketburman014** [comment]
I have created game using react and I would like to create this game.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Shreyaar12** [comment]
@aniketburman014 Kindly complete this within 1 week

**Comment by vk20july** [comment]
@Shreyaar12 sir i want to work on this issue under gssoc'23
