### ISSUE TITLE
[GSSOC'23 Contribution]: Minesweeper game

### ISSUE THREAD

**Issue by singh-anushka** [ssitvit/Games-and-Go#40]
In Minesweeper, you need to uncover all the squares on the grid without detonating any mines. The grid is initially covered with hidden squares, some of which contain mines. Your task is to reveal the safe squares while avoiding the explosive mines lurking beneath. 
This is prepared using HTML, CSS and JavaScript.

**Comment by 24-Aarushi-Singh-24** [comment]
I am willing to do this task. Please assign it to me.

**Comment by admindebu** [comment]
Hi @singh-anushka ,please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.

**Comment by singh-anushka** [comment]
Actually, this needs to be made in react. So I'm still getting proficient in react. Can I make in html css and JavaScript?

**Comment by singh-anushka** [comment]
Or can I create a Pr for the same in Code canvas repository? @admindebu

**Comment by 24-Aarushi-Singh-24** [comment]
Can I use html, css and javascript to make this?
