### ISSUE TITLE
want to add new game

### ISSUE THREAD

**Issue by Yashoda2003** [ssitvit/Games-and-Go#405]
game :
I want to add AI chess game under GSSocC'23.

![Screenshot (492)](https://github.com/ssitvit/Games-and-Go/assets/116747256/94f466da-e4ae-43c7-97ed-91f18c1ccad8)

**Comment by silky-modi22** [comment]
I want to add a temperature converter game  
![image](https://github.com/ssitvit/Games-and-Go/assets/99467488/768de6ae-5cf6-4f85-a4c1-12e253c13313)
Please assign this issue to me under GSSOC 2023
