### ISSUE TITLE
[GSSOC'23 Contribution]: Candy Crush

### ISSUE THREAD

**Issue by singh-anushka** [ssitvit/Games-and-Go#41]
The goal is to match at least three candies of the same colour and type in a row or column to clear them from the board. With each successful match, players earn points.

**Comment by admindebu** [comment]
Hi @singh-anushka ,  please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.

**Comment by sumitkr2000** [comment]
Hey @raj03kumar @admindebu Can I work on this issue? It seems that the person who has created this issue is not working on it. Its been 2 week now.
