### ISSUE TITLE
Bug: tic tac toe game

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Games-and-Go#417]
Tic tac toe game crashes when draw is there. Fix it by adding an if statement or any other method.

**Comment by raj03kumar** [comment]
@Shreyaar12 Once try Tic tac toe with AI :')

**Comment by Shreyaar12** [comment]
@raj03kumar 

Sure, you can incorporate ai with tic tac toe and improve the game

**Comment by sirajlekhak** [comment]
assign me this

**Comment by raj03kumar** [comment]
> @raj03kumar 
> 
> Sure, you can incorporate ai with tic tac toe and improve the game

Already it is incorporated to the website

Play game no.17 tic tac toe with AI

**Comment by raj03kumar** [comment]
@sirajlekhak Assigned this issue to you. Kindly fix the crash when draw is there in game no. 1. Go through the guidelines and contributing.md for successful merge. Kindly complete it within a week. All the best to your work...

**Comment by palakag29** [comment]
@raj03kumar I saw this issue is opened for 3 weeks. if not completed assign it to me
