### ISSUE TITLE
Update card UI

### ISSUE THREAD

**Issue by Ayush9951** [ssitvit/Games-and-Go#423]
### Description

Hi @raj03kumar, I am a contributor in GSSOC'23, 
I want to work on Improving layout of card.
I will add some margins and padding between title, desc, and button
please assign me this task under label gssoc'23

### Screenshots

![Screenshot 2023-06-08 115110](https://github.com/ssitvit/Games-and-Go/assets/60573378/417605e6-a833-4014-a26b-9409e719e3e1)

**Comment by silky-modi22** [comment]
I want to update a card UI my design looks like this 
![image](https://github.com/ssitvit/Games-and-Go/assets/99467488/4e0aaae1-3ada-4467-8428-7fe7c12ee4b8) 
on hovering the image 
![image](https://github.com/ssitvit/Games-and-Go/assets/99467488/935770fe-f988-4ba8-851a-457ea6dea66b)
if you like my design please assign this issue to me under gssoc 2023. I want to work on this.
