### ISSUE TITLE
To add a multiplayer snake game created with the help of web sockets

### ISSUE THREAD

**Issue by DhairyaMajmudar** [ssitvit/Games-and-Go#431]
### Description

To add a multiplayer snake game created with the help of web sockets

**Comment by DhairyaMajmudar** [comment]
@raj03kumar please assign this issue to me under GSSoC'23, I will create the game as mentioned

**Comment by raj03kumar** [comment]
This is react js repository and you have to contribute in react js. Kindly get it done within 10 days.

**Comment by DhairyaMajmudar** [comment]
Thank you @raj03kumar sir for assigning me this issue I will solve this issue in 10 days with React.
