### ISSUE TITLE
[NEW GAME]: Red Light Green Light

### ISSUE THREAD

**Issue by uzmaansari23** [ssitvit/Games-and-Go#433]
### Description

It is the simple game similar to Squid Game.
Where there will be two players, Player 1 and Player 2. Player 1 ball will move by pressing "up rrwo" andd Player 2 ball will move by pressing "w".
Players have to move the ball from one point to another when the doll is looking away . And when the doll is looking in front players have to stop or else they will loose.

### Screenshots

![screenshot](https://github.com/ssitvit/Games-and-Go/assets/113499701/623ea4fb-33d5-4aab-bd13-27b84259161a)

**Comment by uzmaansari23** [comment]
Please assign me this issue under gssoc'23.

**Comment by panwar8279** [comment]
Hi @uzmaansari23, I am assigning this to you. Kindly complete your work within a week. Good luck for your work.
