### ISSUE TITLE
[NEW GAME]: Valorous Rabbit

### ISSUE THREAD

**Issue by uzmaansari23** [ssitvit/Games-and-Go#434]
### Description

This game is made by using HTML, CSS and JavaScript.
In this game a player has to make the running rabbit jump by clicking on "click to jump" to save  the rabbit life from the dangerous cat. The longer the rabbit run the greater the score will be.

### Screenshots

![valorous_rabit png](https://github.com/ssitvit/Games-and-Go/assets/113499701/b28862f5-8480-4788-8aa1-2a2bf9a59b98)

**Comment by uzmaansari23** [comment]
Please assign me this issue under gssoc'23.

**Comment by panwar8279** [comment]
Hi @uzmaansari23, I am assigning this to you. Kindly complete your work within a week.

**Comment by uzmaansari23** [comment]
@panwar8279 okay!
