### ISSUE TITLE
Home page is not responsive

### ISSUE THREAD

**Issue by crocmons** [ssitvit/Games-and-Go#437]
### Description

Home page text is not responsive also properly not visible for the blue color.. I want to responsive the home page for all devices also want to improve visibility by changing the text color to white, please assign this issue to me as a gssoc23 contributor

### Screenshots

![Screenshot (401)](https://github.com/ssitvit/Games-and-Go/assets/106610322/a403169b-60fc-41ae-837a-72f857e4a63c)

**Comment by panwar8279** [comment]
Hi @crocmons, I am assigning this issue to you. Kindly fix this issue within a week. Good luck for your work.
