### ISSUE TITLE
[Add]: Bow_Arrow Game

### ISSUE THREAD

**Issue by Roshnijeewani3457** [ssitvit/Games-and-Go#438]
### Description

Bow_Arrow is a game implemented using HTML, CSS, and JavaScript. The game is to shoot monsters and save birds.
Objective is to Shoot monsters and save birds.

**HOW TO PLAY**
- Start the game
- Move the man with Arrow Keys
- Shoot arrow with Space Bar
- +1 for hitting monsters
- -5 if monsters reaches birds
- Game Over if score<0
- Monsters speed increases each level.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/89697445/89aee5ed-76be-43ac-abad-19eaf986eb81)
![image](https://github.com/ssitvit/Games-and-Go/assets/89697445/025cc839-2d76-4207-a7f7-fac3b7c10a0f)

**Comment by Roshnijeewani3457** [comment]
I would like to work on this project under GSSOC'23.Please Assign me this task.

**Comment by panwar8279** [comment]
Hi @Roshnijeewani3457, I am assigning this to you. Kindly complete within a week. Good luck for your work.

**Comment by Roshnijeewani3457** [comment]
Thanks @panwar8279 for assigning me.I will make sure to complete this project within a week.

**Comment by nandini601** [comment]
I would like to work on this project under GSSOC'23.Please Assign me this task.
