### ISSUE TITLE
[ADD] <Word Connect Game>

### ISSUE THREAD

**Issue by kavya-gaur** [ssitvit/Games-and-Go#440]
### Description

I would like to enhance the existing project by adding Word Connect game in which we have to connect the letters to create words which is a really cool game to play with as far as gaming is concerned .

### Screenshots

![WhatsApp Image 2023-06-09 at 10 26 40](https://github.com/ssitvit/Games-and-Go/assets/122012883/0a280c26-d23d-4173-9c78-09c0e9b2c469)

**Comment by kavya-gaur** [comment]
@Shreyaar12  I would be more than happy to work upon this issue since i have already worked upon these projects in the past .

**Comment by panwar8279** [comment]
Hi @kavya-gaur, I am assigning this issue to you. Kindly complete your work within a week.
