### ISSUE TITLE
[Add] New Game Drum_kit

### ISSUE THREAD

**Issue by Roshnijeewani3457** [ssitvit/Games-and-Go#447]
### Description

A fun and interactive drumming simulation game that can be played through your web browser.

**Tech used**
- HTML for structure
- CSS for styling
- JavaScript for interactivity and game logic

## **functionalities 🎮**
Easy to play
Mind relaxing
Fully responsive design
Fun to play 

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/89697445/4d8299a0-4c59-4c23-aaa3-cdbe3a822246)

**Comment by Roshnijeewani3457** [comment]
I would like to work on this game under GSSOC'23.Please Assign me this task.

**Comment by panwar8279** [comment]
Hi @Roshnijeewani3457, I am assigning this task to you. Kindly complete your work within a week. Good luck !
