### ISSUE TITLE
Memory Game Bug

### ISSUE THREAD

**Issue by kavya-gaur** [ssitvit/Games-and-Go#449]
### Description

When user choose to play memory game . It shows a start button for around a second or two but then it disappears and the game starts suddenly . This issue can be easily fixed by adding event listener to the start button. So when user clicks the start button then only the game will start and not the other way around .

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/122012883/9d5e9a7e-4f12-451f-ab49-d837020021ff)

**Comment by kavya-gaur** [comment]
@panwar8279 I would be happy to work upon this issue . If possible , Kindly allot it to me . I will be adding an event listener  to the start button properly , so that game only starts on clicking the start button and not the other way around thus enhancing the user experience .

**Comment by panwar8279** [comment]
Hi @kavya-gaur , I am assigning this issue to you. Complete your work within a week . Make sure file will not be conflict. Good luck.
