### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by Pranav-Rustagi** [ssitvit/Games-and-Go#452]
### Description
Netlify deployment shows an error "Page Not Found" on pages.

### Reproduction of bug
Open the website, and click the "Play now!!!" button on any card. Refresh the screen. The error pops up.

### Screenshots
![image](https://github.com/ssitvit/Games-and-Go/assets/57594891/620ddac0-f88f-4624-9095-ff5392d2839d)

**Comment by Pranav-Rustagi** [comment]
@panwar8279 Kindly assign this issue to me under GSSOC

**Comment by Pranav-Rustagi** [comment]
@panwar8279 @raj03kumar Please assign this issue to me under GSSOC

**Comment by panwar8279** [comment]
Hi @Pranav-Rustagi , I am assigning this issue to you. Complete your work within a week. And also do work carefully without any file conflict.
