### ISSUE TITLE
Enhancement of game cards

### ISSUE THREAD

**Issue by Pranav-Rustagi** [ssitvit/Games-and-Go#454]
### Description

The current UI of cards does not very pleasant. There is lack of spacing, as well as indentation.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/57594891/e75a139b-d869-46a3-8101-52b2cd4f23e4)

**Comment by Pranav-Rustagi** [comment]
@panwar8279 @raj03kumar Kindly assign this issue to me under GSSOC

**Comment by panwar8279** [comment]
Hi @Pranav-Rustagi , I am assigning this issue to you. Kindly complete this within a week. Good luck for your work.

**Comment by raj03kumar** [comment]
@Pranav-Rustagi i guess u r working on older version of the fork. Kindly sync your fork to latest so that you avoid merge conflict in future. All the best to your work.
