### ISSUE TITLE
[New Game] : Hunt Your Card

### ISSUE THREAD

**Issue by dhruvishavaghani** [ssitvit/Games-and-Go#456]
### How would you like to enhance the existing project.

I want to add new game Hunt Yout Card .

### Describe breifly how would you implement the same.

How to pay?
- There will be 4 shuffling cards, the front side of the cards will be hidden.
- One target card will be given.
- The player has to randomly select one card from the shuffling cards.
- If the selected card is the same as the target card points will be incremented.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @dhruvishavaghani , I am assigning this task to you. Kindly complete within a week. Good luck for your work.
