### ISSUE TITLE
[GSSOC'23] Color Blast Game

### ISSUE THREAD

**Issue by Arnabhit** [ssitvit/Games-and-Go#46]
The above game is a Html,Css,JavaScript game that creates a canvas element and initializes various game
objects such as the player, enemies, bullets, and particles. It also handles user input for movement
and shooting, collision detection, and game over conditions. The game loop continuously updates and
renders the game objects on the canvas. The game can be paused and restarted by clicking on the
canvas or pressing the spacebar.

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Arnabhit** [comment]
Hey @cleveranu I have raised this issue first , so shoudn't I get the chance to contribute?

**Comment by cleveranu** [comment]
yah fine @Arnabhit

**Comment by purviporwal0** [comment]
i would love to contribute under gssoc'23 pls assign this to me

**Comment by rv1830** [comment]
please assign this to me

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
