### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by Naman2408** [ssitvit/Games-and-Go#460]
### Description

Adding a old Indian game Raja, mantari ,chor and  sipayi

### Additional information

if you didn't heard about this game I will explain it is game between four persons we can play it by making four chits and naming randomly as raja ,mantari,chor, sipayi and we let the chits in air and and everyone have to take one and see what's in their chit the raja has maximum points mantri has second highest followed by sipayi and then Chor and after 10 rounds or whatever counting you have selected for rounds we will collect the points of each person and declare a winner

**Comment by panwar8279** [comment]
Hi @Naman2408, I am assigning this task to you. Kindly complete within a week. Good luck for your work.

**Comment by Naman2408** [comment]
hey!! Mam i have completed html css for the task as i am beginners in frontend coding i am currently in my first year my java script coding is not so strong so i have write that code in python but i don't know the codes so if you allow me i will show you my work

**Comment by Naman2408** [comment]
hey!! Mam i have completed html css for the task as i am beginners in frontend coding i am currently in my first year my java script coding is not so strong i have written in JavaScript but it doesn't go so well so i have write that code in python but i don't know the connectivity of codes so if you allow me i will show you my work

**Comment by Hrjfi** [comment]
38522
