### ISSUE TITLE
[New Game] Tangled Word

### ISSUE THREAD

**Issue by AnkitaBarbora** [ssitvit/Games-and-Go#464]
### Description

Players have to rearrange a set of letters to form a valid word within a specific time limit. Users may get a hint about the word they are trying to guess.

### Screenshots

Screenshots are not available as the project is in progress.

### Additional information

- Challenging Word Puzzles: Players must use their vocabulary and problem-solving skills to unscramble the letters and form a valid word.
- Time Pressure: Players must think quickly and efficiently to unscramble the letters and submit their answer before time runs out.
- Hint System: To provide some assistance, the game offers a hint system.

**I want to contribute this as a part of the GSSoC'23.**

**Comment by panwar8279** [comment]
Hi @AnkitaBarbora, I am assigning this to you. Kindly complete within a week. Good luck for your work.
