### ISSUE TITLE
[FEATURE] Chain Reaction Game

### ISSUE THREAD

**Issue by himanshu-03** [ssitvit/Games-and-Go#47]
Hello!
I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this project by adding a game called **Chain Reaction** which is a fun banter to play with multiple friends.

Things I will be doing as of now:

- [ ] Adding the game 'Chain Reaction'
- [ ] Making it user friendly
- [ ] Try to update the documentation as well as instructions to play the game

If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well ✌️

**Comment by Shreyaar12** [comment]
Hi Himanshu,

I am assigning this to you, please add a demo video while submitting the game and go through contributing.md and readme.md while you submit. The deadline is 10 days.

Happy Coding!

**Comment by himanshu-03** [comment]
> Hi Himanshu,
> 
> I am assigning this to you, please add a demo video while submitting the game and go through contributing.md and readme.md while you submit. The deadline is 10 days.
> 
> Happy Coding!

Hi @Shreyaar12 

Actually I have my End Sems starting from day after tomorrow, so can I create a PR by the first week of June?
