### ISSUE TITLE
Snake Game - Gameplay and Rendering Issues[Feature Request]: 

### ISSUE THREAD

**Issue by rishiofficial** [ssitvit/Games-and-Go#474]
### How would you like to enhance the existing project.

Enhancement

1. update the UI of the snake game 
2. Added score feature
3. When the snake bump into itself the game is over

### Describe breifly how would you implement the same.

Solution_steps

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by sayan2002-github** [comment]
Hello I also want to contribute in this issue.
