### ISSUE TITLE
want to Add color changing feature of text.

### ISSUE THREAD

**Issue by ShrutiSingh-1** [ssitvit/Games-and-Go#475]
### How would you like to enhance the existing project.

![Screenshot 2023-06-13 165023](https://github.com/ssitvit/Games-and-Go/assets/98824644/ff2ef6d5-840b-4ab1-bff8-b13d6d0f63c6)
In text "90S SNAKE GAME", I want to add color changing feature. 

### Describe breifly how would you implement the same.

In src folder ->Game ->Snake Game ->SnakeGmae.css file
I will add my feature in .heading tag.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @ShrutiSingh-1, I am assigning this task to you. Kindly complete within a week.

**Comment by ShrutiSingh-1** [comment]
@panwar8279 okayy
