### ISSUE TITLE
[Feature Request]: Drag & Drop - size of table is not fixed.

### ISSUE THREAD

**Issue by hetero-1** [ssitvit/Games-and-Go#476]
### How would you like to enhance the existing project.

Enhancement
size of table is not matched with background 
![Screenshot 2023-06-13 170748](https://github.com/ssitvit/Games-and-Go/assets/93766992/17bc1202-5dd2-4fc5-9cb2-f53cba9f2cdf)
box 

### Describe breifly how would you implement the same.

Solution_steps

1. src -> games -> Drag & Drop -> App.css 
2. Change the table size in class table.  

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @hetero-1 , I am assigning this task to you. Kindly complete within a week. Good luck for your work.

**Comment by hetero-1** [comment]
hi @panwar8279, is it okay or can I do anything else ?

![Screenshot 2023-06-13 233323](https://github.com/ssitvit/Games-and-Go/assets/93766992/bb6435e6-ab0a-4d8f-bde2-cb4a6eb831bc)
