### ISSUE TITLE
[FEATURE] : Add "Leaderboard" Section To All Individual Games

### ISSUE THREAD

**Issue by NarendraKoya999** [ssitvit/Games-and-Go#478]
### Issue Description:
- Add Leaderboard Section for Each Individual Game.

## How To Design That ??
- Go To The 'https://games.ieeessitvit.tech/' Website.
- See Different Types of Games There.

> Design Particular Leaderboard Section Below Way:
- User Name, Game Name, Game ID, Particular Rank
- Except, User Name.  All Other Options having Maintain Drop Down List.

> For Example:
-  Suppose, When Click on Game Name Drop Down, What are the Games Currently Present in Our website are Present in this Game Name Drop Down.  
- Likewise, Maintain Drop Down List to Remain Things like Game ID, Particular Rank Except User Name .

> Where To Put in This Feature ??
- Entire this Feature Puts in Whenever Particular User Attempt and Finished that One Game. Immediately, Shown Leaderboard Card.

> Generate Updated Details of Particular Game attempted By User shown in 2 Ways :

**( 1st Base Level Choice)**
- **Select, Drop Down Options. If select All Drop Down Options for Each Category, `Then Automatic Particular Rank Updated and Shown there that Rank based on Previous Ranks (Develop Automatic Generating Feature for Ranks). `**

**(2nd Hard Level Choice)**
- **Better Than Selecting Particular Drop Down Options,` We Can Design Automatic Generating Feature for All Options.`**

### NOTE: 

- **Maintain Leaderboard Feature  is Best Thing for Gives High Motivation and Confidence to Users Who Can Attempt Particular Game.**

**Comment by poorvamaggu** [comment]
Similar to the home tab we can add a leaderboard tab and in it there would be tiles of game redirecting them to leader board of that particular game.
--------------------------------------------------------------------------------------------------------------------------------------------
Screenshot:
[sample screenshot](https://drive.google.com/file/d/19rXKjG1cZtx3lfoJcjQNPtxAtogl5ZPd/view?usp=sharing) 
--------------------------------------------------------------------------------------------------------------------------------------------
THEN PROCEDING FURTHER this UI will come,
screenshot:
https://drive.google.com/file/d/1lWXoKbUQcNqftReP7So2Ua9pE3bywl0D/view?usp=sharing
--------------------------------------------------------------------------------------------------------------------------------------------
This will be the leaderboard when we click on Display leaderboard:
https://drive.google.com/file/d/1lJFisseocjSCkfW5e_bnVA2O3fd8HxWb/view?usp=sharing
--------------------------------------------------------------------------------------------------------------------------------------------
I can do this task quickly and with a better ui please assign this to me..under gssoc'23

**Comment by poorvamaggu** [comment]
please assign this issue

**Comment by panwar8279** [comment]
Hi @NarendraKoya999 , I am assigning this issue to you. Kindly complete within a week. Good luck!

**Comment by NarendraKoya999** [comment]
Sure @panwar8279
