### ISSUE TITLE
[FEATURE] : Add Sign-in OR and Login Feature for All Games

### ISSUE THREAD

**Issue by NarendraKoya999** [ssitvit/Games-and-Go#479]
### Issue Description:
- User Must Registered with Respective User Name, E-Mail , Password Details Before Entering Into Any Individual Game.

## Reason For Proposed This Feature is:
1. **Actually, This Feature is Referencing with Other Particular Issue No < #478  > for User Name Wise.**
2. **It's also Automatically Generate User Name in Leaderboard Section After Completing the Particular Game By User.**
 

### NOTE:

- **This Feature is Very Helpful for Security Validations and Verifications.**
- **And Maintaining Genuine User Data.**

**Comment by praveenrider784** [comment]
i would like to work on this issue please let me in

**Comment by Uma-Shankar0927** [comment]
Hello, please allow me to contribute, I will implement the feature.

**Comment by panwar8279** [comment]
Hi @NarendraKoya999 , i am assigning this task to you. Kindly complete within a week. Good luck!

**Comment by NarendraKoya999** [comment]
Ok sure @panwar8279
