### ISSUE TITLE
[FEATURE] Lights Out Game

### ISSUE THREAD

**Issue by himanshu-03** [ssitvit/Games-and-Go#48]
Hello!
I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this project by adding a Lights Out game

Things I will be doing as of now:

- [ ] Adding the Lights Out Game in React.js
- [ ] Enhancing UI of the gane with Neon Filters

### About the Game:

The aim of the game is to turn all the lights on the board off. When you click on one light, it will toggle on/off that light and its 4 non-diagonal neighbours (N,S,E,W).
 
---

If you think it is legit then do assing me the issue under GSSoC '23 with the level of the PR as well

**Comment by Shreyaar12** [comment]
Hi Himanshu, 

I am assigning this to you, please add a demo video while submitting the game and go through contributing.md and readme.md while you submit. The deadline is 10 days. 

Happy Coding!

**Comment by himanshu-03** [comment]
> Hi Himanshu, 
> 
> I am assigning this to you, please add a demo video while submitting the game and go through contributing.md and readme.md while you submit. The deadline is 10 days. 
> 
> Happy Coding!

Hi @Shreyaar12 

Actually I have my End Sems starting from day after tomorrow, so can I create a PR in the first week of June?

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue

**Comment by himanshu-03** [comment]
> Can you please assign me this issue

Hi @Harshvardhan-Dubey-Github 
As you can already see the game is identified and issued by me. Can you please think of something different and raise an issue for the same?
