### ISSUE TITLE
[GSSOC' 23] : Maze Game 

### ISSUE THREAD

**Issue by jaydeep099** [ssitvit/Games-and-Go#49]
A maze game is a type of puzzle game where players navigate through a maze to reach a specific goal or objective. There will be a key and House in the Maze , so here player will be key and using arrow keys he has to reach to the house. There will four difficulty level : easy, medium, hard and Extreme. this game will use HTML,CSS,JavaScript.

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by anveshajain19** [comment]
Hey @jaydeep099, I am Anvesha Jain, please assign it to me, I have made these kinds of games earlier and have a good hand in MERN Stack.
Thank you.

**Comment by jaydeep099** [comment]
I think game is my idea. So ideally it should be assigned to me. @anveshajain19

**Comment by Shreyaar12** [comment]
Kindly complete it within 10 days

**Comment by jaydeep099** [comment]
Ok
