### ISSUE TITLE
[Feature Request]: To decrease the size of the Game and Go box 

### ISSUE THREAD

**Issue by linga66** [ssitvit/Games-and-Go#497]
### How would you like to enhance the existing project.

Games and Go is written in a box, I think that box UI should be changed

![Screenshot (590)](https://github.com/ssitvit/Games-and-Go/assets/103192975/75555d40-5cb5-47f6-8236-7209fe646600)

### Describe breifly how would you implement the same.

Buy changing the dimensions of the box, we can make it look good and occupy less space.
Assign it to me @Shreyaar12  @cleveranu  @raj03kumar 

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @linga66 , I am assigning this task to you. Kindly complete within a week. Make sure no any file conflict. Good luck!
