### ISSUE TITLE
[FEATURE] About section addition

### ISSUE THREAD

**Issue by linga66** [ssitvit/Games-and-Go#498]
### Description

We can add the about section above the search bar which describe the Games-And-Go website.

### Screenshots

![Screenshot (591)](https://github.com/ssitvit/Games-and-Go/assets/103192975/8c1d2de2-93ed-449e-bbe8-de477388b614)

### Additional information

Assign it to me @Shreyaar12 @cleveranu @raj03kumar

**Comment by Pulkitxm** [comment]
Can I get is assigned and explain how to get started
