### ISSUE TITLE
Hi there! I am selected as GSSOC contributor and your tech stack matches mine so I would like to be a part of this project ⭐

### ISSUE THREAD

**Issue by anshita742** [ssitvit/Games-and-Go#50]

**Comment by Shreyaar12** [comment]
Hi, please tell us about the kind of project you will be adding

**Comment by anshita742** [comment]
> Hi, please tell us about the kind of project you will be adding

We can make project where their might we some codes (basic) and you have to sort of set the correct logic so that that code will work and you build a house or something like that.
Apart from this I am ready to work on any idea.

**Comment by admindebu** [comment]
Invalid for the issue. make sure you are adding proper issues or ideas.
