### ISSUE TITLE
Adding a flip feature to card to show rules of game

### ISSUE THREAD

**Issue by Dimple-01** [ssitvit/Games-and-Go#504]
### Description

 **Issue:**

The rules of games are not mentioned properly.

**Issue description**

I found it difficult to play some games as the rules were not instructed.
I want to add flip functionality to the game cards so that the user could understand the rules.
On cards, I would write simple rules to play the game as everyone is not familiar with every game.
I would add small small points how to play the game.

**Current behavior**

![Screenshot (108)](https://github.com/ssitvit/Games-and-Go/assets/114878264/8c06d89a-d392-4acb-bcc6-7327d307e38b)

**Desired Behavior**
All cards are static

https://github.com/ssitvit/Games-and-Go/assets/114878264/665852cd-4276-4245-95e4-0e120967644b

**I want to work on this issue.
Please assign this to me.**

**Comment by panwar8279** [comment]
Hi @Dimple-01 , I am assigning this task to you. Kindly complete within a week. Good luck for your work!

**Comment by Dimple-01** [comment]
Thank you for assigning.

**Comment by Dimple-01** [comment]
@panwar8279  please check, whether u r satisfied with me or not.

https://github.com/ssitvit/Games-and-Go/assets/114878264/b375b678-d364-4067-962b-8c748aa81482

 
Please give feedback.
I have done 90% of the work.
I just want your approval to finish it.
