### ISSUE TITLE
Trivia Game Alignment

### ISSUE THREAD

**Issue by muskandn** [ssitvit/Games-and-Go#508]
### How would you like to enhance the existing project.

The box containing the questions is not center aligned. It would look good if all the nested boxes will get center aligned.

### Describe breifly how would you implement the same.

Solution_steps.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @muskandn, I am assigning this task to you. Kindly complete within a week. Good luck for your work!

**Comment by muskandn** [comment]
okay @panwar8279 I am on it.
