### ISSUE TITLE
[Feature Request]: adding various themes

### ISSUE THREAD

**Issue by Swapnil-2503** [ssitvit/Games-and-Go#509]
### How would you like to enhance the existing project.

Enhancement will be as we can add a button for changing themes and it will change themes in various colors.
 it is awesome to see it in various themes of colors

### Describe breifly how would you implement the same.

Solution_steps

I will change some code in Homepage.js and Homepage.css 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Swapnil-2503, I am assigning this task to you. Kindly complete within a week. Good luck!
