### ISSUE TITLE
Rock paper scissors game

### ISSUE THREAD

**Issue by Tusharjoshi1703** [ssitvit/Games-and-Go#51]
I'll create a Rock paper scissors game which is made by using Html,css and JavaScript.
Please assign it to me.

**Comment by 24-Aarushi-Singh-24** [comment]
I have already created a rock, paper and scissor game. Please assign this issue to me.

**Comment by Shreyaar12** [comment]
An issue for this game is already open, please raise another issue

**Comment by splusb** [comment]
I will very much like to work on this project under GSSOC'23. I will create a new rock-paper-scissors game using proper tech-stack. So please assign this issue to me.

**Comment by admindebu** [comment]
Duplicate idea, closing this
