### ISSUE TITLE
[DOCS] : Contributing.md is missing an important step.

### ISSUE THREAD

**Issue by trishanu-init** [ssitvit/Games-and-Go#510]
### Description

The Contributing.md file should have one more important step before Step 2

### Screenshots

This step is missing :
![image](https://github.com/ssitvit/Games-and-Go/assets/85580785/04f2b4aa-13d2-46bc-8364-b849f52adb81)

### Additional information

It should look like:
Step 2 :
 import your javascript file
![image](https://github.com/ssitvit/Games-and-Go/assets/85580785/b0aeea68-651f-4f7b-893a-044065c92ffe)

Step 3:
Go to AllRoutes.js in Routes Folder and add your name in the Routes with a suitable path

**Comment by panwar8279** [comment]
Hi @trishanu-init, I am assigning this task to you. Kindly complete with in a week. Good luck!
