### ISSUE TITLE
GSSOC '23 Space Race Game! 

### ISSUE THREAD

**Issue by nikitachaudharicodes** [ssitvit/Games-and-Go#52]
Hey, I'm a contributor at GirlScript Summer of Code 2023 and I'd love to contribute to your project by building a simple Space Race Game. It's a two-player game. [https://www.youtube.com/watch?v=ibESf4gAuMw](https://www.youtube.com/watch?v=ibESf4gAuMw)

**Comment by raj03kumar** [comment]
Assigned this issue to you kindly complete it within 10 days go through the readme and contributing.md as well for successful merge. All the best to your work Nikita... !!!

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
