### ISSUE TITLE
[NEW GAME]: Ball Ninja

### ISSUE THREAD

**Issue by Parul1606** [ssitvit/Games-and-Go#54]
Description: 
Ball Ninja is an arcade-style game where the player takes on the role of a skilled ninja tasked with slicing and avoiding bouncing balls. The objective is to survive for as long as possible while slicing as many balls as the player can. 

Basic Game Logic:
1. Display a game screen where balls of different sizes and colors bounce around.
2. Allow the player to control a ninja character using arrow keys or touch gestures to move horizontally across the screen.
3. Implement collision detection to check if the ninja's sword intersects with a ball. If a collision occurs, split or destroy the ball, awarding the player points.
4. Ensure the balls bounce off walls and obstacles in the game area to create challenging movement patterns.
5. Occasionally, introduce special balls with unique properties, such as larger size, increased speed, or the ability to split into smaller balls.
6. End the game if any of the following conditions are met:
    (i). The player's ninja character collides with a ball.
    (ii). The player reaches a predetermined time limit or score threshold.

Features I'm going to add in this project are: 
1. Power-ups: Occasionally, spawn power-ups that provide temporary benefits to the player, such as slowing down the balls.
2. Obstacles: Introduce obstacles or barriers in the game area that require the player to maneuver strategically to avoid collisions.
3. High Score Tracking: Keep a record of the highest scores achieved by players. Display the top scores on a leaderboard.
4. Sound Effects and Music: Enhance the gaming experience with sound effects for ball slicing, character movement, and background music.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete the work within 10 days and go through the readme and contributing.md for successful merge. All the best to your work Parul... !!!

**Comment by Parul1606** [comment]
Thank you @raj03kumar ! I will give my best to give to the project.

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
