### ISSUE TITLE
[FEATURE] Whack-a-Mole Game

### ISSUE THREAD

**Issue by lakhan06** [ssitvit/Games-and-Go#545]
### Description

The Whack-a-Mole game is a classic arcade game implemented using HTML, CSS, and JavaScript. Players must whack or hit moles that randomly pop up from holes on the screen. The game features a simple and intuitive user interface with responsive design elements.

- Hit moles that randomly pop up from holes on the screen
- Score points for successfully hitting moles
- Track your score as you play
- Responsive design for easy play on different devices
- Plants also pop up and if you click them then game is over

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/119161467/cfb84438-d00f-4a8e-a874-402fec351f8c)

### Additional information

https://github.com/ssitvit/Games-and-Go/assets/119161467/8676f48c-7a15-436e-9706-9358e214248c

**Comment by Swapnil-2503** [comment]
nice bro 👍.

**Comment by lakhan06** [comment]
@raj03kumar I am writing to kindly request your attention and consideration in reviewing and  assigning me this issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

**Comment by raj03kumar** [comment]
@lakhan06 this is reactJS repo and you are requested to contribute in react and not just HTML, CSS and JS

**Comment by lakhan06** [comment]
@raj03kumar i can convert it inti a react game
