### ISSUE TITLE
[Addition] Throw a dice - 2 Player game

### ISSUE THREAD

**Issue by saniaahmad6** [ssitvit/Games-and-Go#55]
Please assign this issue to me under GSSOC 2023.

**Comment by raj03kumar** [comment]
Please give description in detail to us to further proceed with you.

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by saniaahmad6** [comment]
> Please give description in detail to us to further proceed with you.

The game can proceed as: 

1. The game requires a standard six-sided dice.
2. Decide on the number of attempts they wish to play.
3. Set a target score that all players aim to reach. For example, they can set the target score at 30 points.
3. The players take turns to throw the dice in each round.
4. On their turn, a player rolls the dice and adds the resulting number to their cumulative score.
5. After each throw, the player can choose to either continue rolling or end their turn and pass the dice to the next player.
6. We can add: If a player rolls a 1, their cumulative score for that round becomes zero, and their turn ends immediately.

The game continues until all the rounds have been completed, or a player reaches or exceeds the target score.
1. The one with more points is the winner
2. Who reached the target sum earlier is the winner

This is the idea, we can modify it as well.

Thank you

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly get it done within 10 days and go through the readme and contributing.md for successful merge. All the best to your work Sania... !!!
