### ISSUE TITLE
[FEATURE] Kill the Bird Game

### ISSUE THREAD

**Issue by lakhan06** [ssitvit/Games-and-Go#555]
### Description

In this game player have to kill the bird using the mouse.

- Point down the features
- Single PLayer
- Time limit
- easy to play
- Need to Shoot the bird

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/119161467/9f982391-0fcc-41f3-99f7-35a8793c306b)

### Additional information

https://github.com/ssitvit/Games-and-Go/assets/119161467/dd5f49a2-1339-4154-be99-65590fca67c3

**Comment by panwar8279** [comment]
Hi @lakhan06 , I am assigning this task to you. Kindly complete your work within a week. Good luck for your work!
