### ISSUE TITLE
[FEATURE] Add hover effect to home button

### ISSUE THREAD

**Issue by accodes21** [ssitvit/Games-and-Go#559]
### Description

Currently, the home button doesn't have any hover effect, so add it to make it more user interactive.

I'm contributing under GSSoC'23 program.
Do assign this issue to me.

**Comment by panwar8279** [comment]
Hi @accodes21 , I am assigning this task to you. Kindly complete within 2 day. Good luck!

**Comment by Dimple-01** [comment]
If this work not done yet.
Please assign this work to me.
I want to work on this issue.

**Comment by bibhanshu01** [comment]
I want to work on this issue by adding some animated hover effect on buttons, can you assign this to me?
