### ISSUE TITLE
Add Plant Defense Game

### ISSUE THREAD

**Issue by Prajwal0225** [ssitvit/Games-and-Go#561]
### Description

Wanted to Add Plant Defense Game to Games-and-Go

Game logic and basic description

1. The player takes control of a plant that is under attack by rocks.
2. The plant is equipped with a gun that can fire bullets to destroy the rocks.
3. Rocks approach the plant from different directions and at varying speeds.
4. The player must aim the gun and fire bullets to break the rocks before they reach the plant.
5. Each time a rock is successfully destroyed, the player earns one point.
6. The game continues until a certain number of rocks breach the plant's defenses or a time limit expires.
7. The player's objective is to achieve the highest score possible by defending the plant for as long as possible.

### Screenshots

https://github.com/ssitvit/Games-and-Go/assets/103810119/193fd7ec-3ded-4400-b611-55f8f0b04cde

**Comment by panwar8279** [comment]
Hi @Prajwal0225 , I am assigning this task to you. Kindly complete your work within a week. Good luck!
