### ISSUE TITLE
[FEATURE] Air Balloon game

### ISSUE THREAD

**Issue by VSatwika** [ssitvit/Games-and-Go#566]
### Description

 - A game where you fly an Air Balloon as far as you can with your limited fuel.
 - Try to move your balloon as far as possible without striking any obstacles.
 - Could this issue be assigned to me under GSSoC'23?

### Additional information

You begin the game with an air balloon and a full tank of fuel.
You need to fly your air balloon as far as possible.
The game ends when you are out of fuel or when you hit a tree.
You consume more fuel the higher your balloon goes.

**Comment by panwar8279** [comment]
Hi @VSatwika , I am assigning this task to you. Kindly complete within a week. Good luck for you work!
