### ISSUE TITLE
checkers

### ISSUE THREAD

**Issue by 24-Aarushi-Singh-24** [ssitvit/Games-and-Go#57]
I have created a checkers game that can be played by either single player(against ai) or two players(player vs player). I have used minimax algorithm to implement single player version and rest is done in pygame.

**Comment by raj03kumar** [comment]
Aarushi This is ReactJS repo and if you can implement what u did with pygame to ReactJS then u r welcome to contribute....

**Comment by 24-Aarushi-Singh-24** [comment]
Sure. I can do that!

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within 10 days and go through the readme and contributing.md for successful merge. All the best to your work Aarushi... !!!
