### ISSUE TITLE
[Feature Request]: Convert Images to WebP Format for Improved GitHub Project Performance

### ISSUE THREAD

**Issue by Avinash905** [ssitvit/Games-and-Go#577]
### How would you like to enhance the existing project.

Currently, the images in our GitHub project are stored in the PNG/JPG image format. However, I would like to convert them to the more efficient WebP format. This conversion will help us reduce file sizes while maintaining image quality, leading to improved website performance and faster loading times. This issue aims to update the entire project's image assets from PNG/JPG to WebP format.

### Describe breifly how would you implement the same.

- Start by identifying all the PNG/JPG images currently present in the project. This includes images used in HTML, CSS, JavaScript, or any other relevant files.

- Utilize image conversion tools or libraries to convert each PNG/JPG image to the WebP format. Ensure that the conversion process maintains the original image quality as much as possible.

- Once the images have been converted, update the references to the PNG/JPG images in the project's codebase. Replace the references with the corresponding WebP image paths to ensure seamless integration.

- Thoroughly test the project after the conversion process to ensure that all images are displayed correctly and maintain their original quality. Verify that the project's functionality remains intact and that there are no broken image references or display issues.

- Submit a pull request with the changes, making sure to include a clear description of the modifications made, the reasoning behind the conversion, and any relevant performance improvements observed.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by panwar8279** [comment]
Hi @Avinash905 , I am assigning this task to you. Kindly complete your work within a week. Good luck!
