### ISSUE TITLE
[ADDITION] Guess The Color game 

### ISSUE THREAD

**Issue by linga66** [ssitvit/Games-and-Go#582]
### Description

GUESS THE COLOR when the RGB value is given
We will be having easy and hard level
Blocks of different colors are given
The RGB value is given and we need to guess the color and select the correct box

### Additional information

Assign me this @raj03kumar @cleveranu @Shreyaar12

**Comment by linga66** [comment]
@Shreyaar12 @raj03kumar Assign me this issue

**Comment by panwar8279** [comment]
Hi @linga66 , i am assigning this task to you. Kindly complete within a week. Good luck for your work!
