### ISSUE TITLE
[Feature Request]: Important Improvement in the layout of few games

### ISSUE THREAD

**Issue by Dimple-01** [ssitvit/Games-and-Go#585]
### How would you like to enhance the existing project.

**Issue**
Important Improvement in the layout of few games

**Description**
Few of games does not appear user engaging and attractive as its elements are not properly oriented.

**Current behavior**

**Here container is only half of the page**

![Screenshot (123)](https://github.com/ssitvit/Games-and-Go/assets/114878264/8d8e2f55-ee1e-4f58-b301-351cfb546352)

**Here layout is looking clumsy**

![Screenshot (125)](https://github.com/ssitvit/Games-and-Go/assets/114878264/d36c23f5-a38f-4754-95c3-12ede9ab3dcc)

**Desired Behavior**

I would add my skills to enhance its appearance so that it would become more clean, eyecatching and user engaging. 

I want to work on this.
Please assign this work to me.

### Describe breifly how would you implement the same.

**Steps to solve this issue.**

1. I would give proper orientation to all elements.
2. I would work on the appearance of the page to make it more appealing.
3. Features of html , CSS , Javascript will be applied. 

**In the middle of the work, I would provide screenshots of the work.**

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Dimple-01 , I am assigning this task to you. Kindly complete your work within a week. Good luck!
