### ISSUE TITLE
Addition of footer section

### ISSUE THREAD

**Issue by Dimple-01** [ssitvit/Games-and-Go#586]
### Description

**Issue** 
Addition of footer section

**Description**

 The footer will serve as a consistent element across all pages, offering easy access to important navigation links, contact details, legal information, and additional resources.

The addition of a footer section will benefit the website:

Improved Navigation: With secondary navigation links in the footer, users will have quick access to essential pages, ensuring they can easily find the information they need.

Enhanced User Experience: By incorporating a well-designed footer, we can create a more intuitive and user-friendly browsing experience, allowing visitors to navigate your website effortlessly.

Increased Accessibility: The footer will contain important contact information, including your company's address, phone number, and email. This will enable visitors to reach out to you directly, enhancing communication and customer engagement.

Legal Compliance: Including links to legal policies such as the terms and conditions, privacy policy, and copyright information in the footer ensures transparency and demonstrates your commitment to legal compliance.

Social Media Integration: We will integrate social media links into the footer, enabling visitors to connect with your brand across various platforms and increasing your online presence.

### Screenshots

**Current Behavior**

![Screenshot (127)](https://github.com/ssitvit/Games-and-Go/assets/114878264/586099db-74b3-4885-b976-7e4a424726b5)

**Desired Behavior**

![Screenshot (126)](https://github.com/ssitvit/Games-and-Go/assets/114878264/0c827817-d724-4b37-ab20-83648513decf)

### Additional information

**I want to work on this issue.
Please assign me this.**

**Comment by iKrishnendu** [comment]
I want to work on this issue.

**Comment by panwar8279** [comment]
Hi @Dimple-01 , I am assigning this issue to you. Kindly complete within a week. Good luck Dimple!

**Comment by Dimple-01** [comment]
Hello @panwar8279, please share your name and social media links. so that I can add it to the website footer. The work is almost done.

**Comment by Dimple-01** [comment]
Please provide me your name and social media links so that I could link it
into the website.
Please respond fast.
