### ISSUE TITLE
[FEATURE]: Backgammon Game

### ISSUE THREAD

**Issue by Killer2OP** [ssitvit/Games-and-Go#589]
### Description

A game of Backgammon made with React and Typescript. It can be played by two players.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/111378171/7c4bb187-210f-4fd4-b9d7-325d32bfca03)

**Comment by Killer2OP** [comment]
@panwar8279 Can you please assign me this issue.

**Comment by panwar8279** [comment]
Hi @Killer2OP , I am assigning this task to you. Kindly complete within 10 days. Good luck for your task!
