### ISSUE TITLE
Add block tower game

### ISSUE THREAD

**Issue by nishita2104** [ssitvit/Games-and-Go#59]
I have made several games earlier and would love to contribute on this project by making a tower block game with a good UI. Please assign this to me under GSSOC'23.

**Comment by anan262** [comment]
I can make this game pretty uqick plus I have good experience on making such games..could you please assign this to me?

**Comment by admindebu** [comment]
Hi @nishita2104 , 
please let us know the detailed plan, dummy UI/Video. make sure you are using react js.
