### ISSUE TITLE
[FEATURE]: Lights-Out Game

### ISSUE THREAD

**Issue by Killer2OP** [ssitvit/Games-and-Go#590]
### Description

- A virtual recreation of the 90's classic, Lights Out! Turn out all the lights to win.
- Lights Out is a logic/puzzle game, played on a gird of individual lights, which can either be lit or unlit. The puzzle is won when when all of the lights are turned off. 

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/111378171/61c71f86-393b-4001-85fb-c0a98137cfb8)

**Comment by Killer2OP** [comment]
@panwar8279 Can you please assign me this issue.

**Comment by panwar8279** [comment]
Hi @Killer2OP , I am assigning this task to you. Kindly complete your work within a week. Good luck for your work!
