### ISSUE TITLE
[Feature Request]: Add the Snake-water game

### ISSUE THREAD

**Issue by Parmesh119** [ssitvit/Games-and-Go#597]
### How would you like to enhance the existing project.

You have to add new snake-water game.

### Describe breifly how would you implement the same.

Solution_steps

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Parmesh119 , i am assigning this task to you. Kindly complete within a week. Make sure your game made in react because it's react based repository. Good luck!
