### ISSUE TITLE
Guess the number 

### ISSUE THREAD

**Issue by Shreyaar12** [ssitvit/Games-and-Go#6]
Create a simple guess the number game

**Comment by omk-coder** [comment]
Can would love to work on this issue.

**Comment by Shreyaar12** [comment]
Assigned it to you

**Comment by omk-coder** [comment]
actually their is an error why starting the react file
<img width="951" alt="image" src="https://user-images.githubusercontent.com/93393539/194744724-088aae2b-7bb0-437d-b675-55f4224f5ab6.png">

**Comment by omk-coder** [comment]
does any one have any idea about this error??

**Comment by subhadiip333** [comment]
I would like to work on this project. Please assign it to me.

**Comment by aniketburman014** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Vickyaryan33** [comment]
Please assign it to me I can solve this issue

**Comment by panwar8279** [comment]
Hi @Vickyaryan33 , Assigned this issue to you. Kindly contribute on this and also go through the readme and contributing.md for successful merge. All the best to your work.
