### ISSUE TITLE
Hunt Your Card

### ISSUE THREAD

**Issue by dhruvishavaghani** [ssitvit/Games-and-Go#60]
Hunt your card is a card game in which one card will be displayed known as a target card and a few cards will be shuffled randomly in such a way that the card's symbols are not displayed to the player. Then the player has to select a random card from the shuffled cards. If the chosen card is not the same as the target card, the rest cards will be displayed to the player which the player needs to remember. In the next turn, cards will be shuffled again and the player has to choose a random card again and the target card will remain the same. On selecting the right card player will get points and in the next turn, a new target card will be set.

Functionalities of the game:
-This game has rounds as per the player's selection of the right card.
-The player's best score will always be stored and updated every time a player scores the highest score.
-Good animated card shuffling.

**Comment by adisuyash** [comment]
Is this issue assigned to you @dhruvishavaghani ?

**Comment by admindebu** [comment]
Hi @dhruvishavaghani , please let us know the detailed plan, dummy UI/Video ? make sure you are using react js.

**Comment by dhruvishavaghani** [comment]
It is a simple card-choosing game. One target card and a few selection cards will be provided. Pattern and the digit of the target card will be displayed while in the case of the selection card, it will be hidden. Cards will be shuffled for a while and then the player has to choose a random card from the selection card. If the card chosen by the player has the same pattern and digit then he/she will get a point.

**Comment by dhruvishavaghani** [comment]
Can you assign this issue to me ?
