### ISSUE TITLE
[FEATURE] Spelling Bee Game 

### ISSUE THREAD

**Issue by vaanyasharmaaa** [ssitvit/Games-and-Go#601]
### Description

A spelling bee game will typically involve the user being given a word with the help of audio and then they have to attempt to spell it correctly. This game is designed to help players improve their spelling skills while providing an enjoyable and engaging experience.

After spelling it, you have to click on submit and you will be told if the answer is correct or not.

#### Increase the volume for better understanding 
https://github.com/ssitvit/Games-and-Go/assets/130481025/c2f3140e-39b7-4067-b3b2-44d41d6ed263

**Comment by vaanyasharmaaa** [comment]
@panwar8279 @raj03kumar I'd appreciate if you'd have a look into this game and would assign me this issue. 
Thanks & Regards

**Comment by panwar8279** [comment]
Hi @vaanyasharmaaa , I am assigning this task to you. Kindly complete within a week. Make sure your game will be in react because it's react based repository. Good luck for your work!
