### ISSUE TITLE
[FEATURE] HOME ,A and B button is missing hover effect.

### ISSUE THREAD

**Issue by HimanshuNarware** [ssitvit/Games-and-Go#602]
### Description

I want to add hover effects on the HOme and A, B button

### Screenshots

![65](https://github.com/ssitvit/Games-and-Go/assets/83147410/32817b7c-b05e-4288-bc98-a94d107edbcf)

**Comment by panwar8279** [comment]
@HimanshuNarware , I am assigning this issue to you. Kindly complete within 2 days. Good luck!
