### ISSUE TITLE
[FEATURE] Add lazy loading

### ISSUE THREAD

**Issue by sumitkr2000** [ssitvit/Games-and-Go#604]
### Description

Hey, I want to add lazy loading to the website. The benefits of lazy loading include:

- **Reduces initial load time –** Lazy loading a webpage reduces page weight, allowing for a quicker [page load time].

- **Bandwidth conservation –** Lazy loading conserves bandwidth by delivering content to users only if it’s requested.

- **System resource conservation –** Lazy loading conserves both server and client resources, because only some of the images, JavaScript, and other code actually need to be rendered or executed.

**Comment by panwar8279** [comment]
@sumitkr2000 , Is it on react or not?

**Comment by panwar8279** [comment]
Hi @sumitkr2000 , I am assigning this task to you. Kindly complete within a week. Good luck!

**Comment by sumitkr2000** [comment]
Yes, it's in react and it is not a documentation update. @panwar8279
