### ISSUE TITLE
[FEATURE] Adding Sitemap for Website {GSSoc'23}

### ISSUE THREAD

**Issue by NikhilRaikwar** [ssitvit/Games-and-Go#605]
### Description

The current website lacks a sitemap, which poses challenges for search engines and users to navigate and discover all the pages and content on the site. This limitation can lead to lower search engine rankings, decreased visibility, and a subpar user experience.

### Screenshots

![sss](https://github.com/ssitvit/Games-and-Go/assets/70462831/ba523633-8d3f-4fab-8247-f54619d8e014)
In the attached screenshot, I have highlighted the website name with the expected presence of a sitemap.xml file. However, upon inspection, it is evident that the sitemap is not being displayed. This screenshot underscores the problem of the current website lacking a visible sitemap, further emphasizing the need for its implementation.

### Additional information

Adding a sitemap to the website will provide several benefits, including improved search engine optimization (SEO), better indexing of content, and enhanced user experience. It will make it easier for search engines to discover and understand the website's structure and content, ultimately leading to higher organic traffic and better visibility in search results. The GSSoc label will highlight the contribution's association with the GSSoc program, showcasing the participant's involvement.

**Comment by panwar8279** [comment]
Hi @NikhilRaikwar , I am assigning this task to you. Kindly complete within 3 days. Good luck!

**Comment by NikhilRaikwar** [comment]
Hey @panwar8279 I completed my task. Please review the pr.
