### ISSUE TITLE
[NEW GAME] React chess game

### ISSUE THREAD

**Issue by Kalivarapubindusree** [ssitvit/Games-and-Go#606]
### Description

I want to add react chess game .
Can you please assign me this task under GSSOC'23 contribution

**Comment by panwar8279** [comment]
@Kalivarapubindusree , Please make this game in react because it's react based repository.

**Comment by Kalivarapubindusree** [comment]
Ok

**Comment by Kalivarapubindusree** [comment]
If you assign me I will try to do that in react.

**Comment by panwar8279** [comment]
Hi @Kalivarapubindusree , I am assigning this task to you. Kindly complete within 10 days. Good luck for your work!
