### ISSUE TITLE
[Bug]: Play button not showing

### ISSUE THREAD

**Issue by sumitkr2000** [ssitvit/Games-and-Go#609]
### Give a brief about the bug discovered✍

Hey @panwar8279 The buttons to play the game are not visible on the website. I have attached a screenshot to have a better look. Please have a look at it and assign me this issue. Thank you!

![image](https://github.com/ssitvit/Games-and-Go/assets/100675296/bde370da-38ed-41bd-8605-61508673e1f1)

### What is the expected behavior?

The buttons should be visible to the users for a better user experience.

### Give a brief description to get the expect behaviour.

- Increase the height of the cards.
- Align the button in the center.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @sumitkr2000 , i am assigning this issue to you. Kindly complete within 2 days. Good luck sumit!
