### ISSUE TITLE
[GSSOC'23] Memory game

### ISSUE THREAD

**Issue by Yash7426** [ssitvit/Games-and-Go#61]
A memory based game in which 12 different cards will be present . Whenever a user selects any card , cards are rearranged in random order. A player loses if he/she selects same card twice.
Functionalities -
1. Users current and high score will be maintained
2. Resetting the game on victory with winning screen and a notification to the user
I would like to work on this,Please assign it to me

**Comment by Shreyaar12** [comment]
Hi @Yash7426 We already have a memory game in our website, please make sure your contribution is unique

**Comment by admindebu** [comment]
Closing duplicate ideas

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by soorjya** [comment]
I would like to help tis issue so do assign me this issue under GSSoC'23.
