### ISSUE TITLE
[NEW GAME] Dice Game

### ISSUE THREAD

**Issue by AvinashChourasia** [ssitvit/Games-and-Go#611]
### Description

This Game is an exciting multiplayer game where two players compete to roll the highest number on their dice. Experience the thrill of luck and strategy as you aim to outscore your opponent in this engaging game suitable for players of all ages.

**functionalities 🎮**
random key generation
Mutiplayer Gameplay
animated keys

**How to play? 🕹️**
The game follows a simple set of rules:

Each player rolls a dice, which generates a random number between 1 and 6.
The player with the higher number wins the game.
If both players roll the same number, the game ends in a tie. Players can easily continue playing by refreshing the page to generate new random numbers for their respective dice.

### Screenshots

![Screenshot (86)](https://github.com/ssitvit/Games-and-Go/assets/97829396/ab59e4a2-5c0b-48ab-af75-f89b54dd90d6)

**Comment by panwar8279** [comment]
Hi @AvinashChourasia , I am assigning this task to you. Kindly complete within a week. Good luck for your task!

**Comment by AvinashChourasia** [comment]
![Screenshot (87)](https://github.com/ssitvit/Games-and-Go/assets/97829396/f526fad0-389e-4360-8eec-c9b09c560c16)
