### ISSUE TITLE
Adding a new game -> Mix or Match

### ISSUE THREAD

**Issue by Amitdahiya08** [ssitvit/Games-and-Go#62]
game overview->
Matching cards, also known as Memory or Concentration, is a popular game where players need to find matching pairs of cards by flipping them over. Here are some details and resources to help you get started with creating a matching cards game:

Game Overview:

The game typically involves a grid of faced-down cards.
Players take turns flipping two cards at a time to reveal their symbols or images.
If the two flipped cards match, they remain face-up.
If the cards don't match, they are flipped back face-down.
The objective is to flip and match all the pairs of cards with the fewest number of moves.
@ssitvit please assign it to me

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete the work within a week and go through the readme and contributing.md for successful merge. All the best to your work Amit... !!!

**Comment by Amitdahiya08** [comment]
thanks for assigning it to me .

**Comment by vk20july** [comment]
@raj03kumar sir i want to work on this issue under gssoc'23
