### ISSUE TITLE
[FEATURE] Escape Room

### ISSUE THREAD

**Issue by sabhisharma-ise** [ssitvit/Games-and-Go#620]
### Description

It is a puzzle game where you must solve a series of puzzles in order to escape the room. The puzzles are all based on different programming concepts, such as HTML, CSS, and JavaScript.

Challenging puzzles: The puzzles in the game are designed to be challenging, but they are also fair. If you get stuck, you can always ask for help from the community.
Educational: The puzzles in the game are based on different programming concepts, such as HTML, CSS, and JavaScript. This makes the game a great way to learn about these concepts.
Visually appealing: The game is visually appealing and engaging. The puzzles are presented in a way that is both challenging and fun.
Social: The game has a forum where you can discuss the puzzles with other players. This is a great way to get help if you are stuck, or to share your own solutions.

### Screenshots

![image](https://github.com/kunjgit/GameZone/assets/100849696/4dc2c3b0-1750-49c3-97b3-665d953f497a)

### Additional information

Sabhi Sharma 
GSSOC'23 Contributor

**Comment by sabhisharma-ise** [comment]
@panwar8279 Hello, please assign me this issue

**Comment by panwar8279** [comment]
Hi @sabhisharma-ise, I am assigning this task to you. Kindly complete your work within a week. Good luck!
