### ISSUE TITLE
[FEATURE] Tic Tac Toe

### ISSUE THREAD

**Issue by sabhisharma-ise** [ssitvit/Games-and-Go#623]
### Description

"Tic Tac Toe" is a classic two-player game played on a 3x3 grid. The objective of the game is to get three of your symbols (either X or O) in a row, either horizontally, vertically, or diagonally, before your opponent does.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/100849696/21a32a5c-abb5-4379-af58-995d4abded5b)

### Additional information

Sabhi Sharma
GSSoC'23 Contributor

**Comment by sabhisharma-ise** [comment]
@panwar8279 Hello, please assign me this issue

**Comment by panwar8279** [comment]
Hi @sabhisharma-ise , I am assigning this task to you. Kindly complete your work within a week. Good luck!
