### ISSUE TITLE
[New game] <A famous Retro game> ENDURO

### ISSUE THREAD

**Issue by Bhuvanchand26** [ssitvit/Games-and-Go#627]
### Description

we all played this game in our childhood, this is a simple game that uses a bit of js
player get to control his keyboard up, left, and right. On colliding with other cars player's card gets decreased.
This game doesn't need any description, because this was played by us. This game was from the 1980s and a perfect fit for this repository.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/131843589/0fd0c00a-aa78-4207-a407-c71af1cf794a)

### Additional information

This is a classic retro game, which will bring back those nostalgic moments again.

**Comment by panwar8279** [comment]
Hi @Bhuvanchand26 , I am assigning this task to you. Kindly complete your work within a week. Good luck.
