### ISSUE TITLE
[FEATURE] planet defense game

### ISSUE THREAD

**Issue by SimranLahrani842** [ssitvit/Games-and-Go#628]
### Description

This is a game where we need to defend our planet from stones and meteroids.
The score is displayed ont he earth itself.
The final score is displayed.
Hit the stones using the gun and maximize your score.

**Comment by SimranLahrani842** [comment]
> wave @SimranLahrani842
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
> 
> Please make sure you have given us as much context as possible.

Assign me this i ll finish it today itself @panwar8279

**Comment by panwar8279** [comment]
Hi @SimranLahrani842 , I am assigning this task to you. Kindly complete within a week. Good luck for your work!
