### ISSUE TITLE
[FEATURE] Tower blocks game

### ISSUE THREAD

**Issue by SimranLahrani842** [ssitvit/Games-and-Go#629]
### Description

We need to form the tower with the help of blocks.Block should be placed upon block with same size else size of block goes on reducing.

Game points:Score will be displayed as how long our tower is.

**Comment by SimranLahrani842** [comment]
> wave @SimranLahrani842
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
> 
> Please make sure you have given us as much context as possible.

Assign me @panwar8279

**Comment by panwar8279** [comment]
Hi @SimranLahrani842 , I am assigning this task to you. Kindly complete within a week. Good luck!
