### ISSUE TITLE
[FEATURE] <description>Typing Master Challenge: Test Your Speed and Accuracy

### ISSUE THREAD

**Issue by shishiro26** [ssitvit/Games-and-Go#630]
### Description

The Typing Speed Test is an interactive game that measures your typing speed and accuracy. It provides you with a passage of text, and your goal is to type it as quickly and accurately as possible. The game calculates your words per minute (WPM) and tracks any mistakes you make during the test.

Instructions:

1.Start the game by clicking the "Begin Test" button.
2.The passage of text will appear on the screen.
3.Begin typing the text in the provided input field as accurately and quickly as possible.
4.Your typing speed and accuracy will be measured and displayed in real-time.
5.If you make a mistake, it will be highlighted or indicated, and the error count will be updated.
6.Once you finish typing the entire passage, the game will display your final WPM score and the number of mistakes you made.
Features:

1.Real-time WPM calculation: The game calculates your typing speed in words per minute as you type.
2.Error tracking: Mistakes made during typing are tracked and displayed.
3.Passage variations: Each time you take the test, a new passage is presented to keep the challenge fresh.
4.Replay option: You can replay the test to improve your typing speed and accuracy.

### Screenshots

<img width="676" alt="image" src="https://github.com/ssitvit/Games-and-Go/assets/113853868/b9bf400f-b12e-4ba5-9d0c-47f58b003e6c">

**Comment by panwar8279** [comment]
Hi @shishiro26 , I am assigning this task to you. Kindly complete within a week. Good luck!
