### ISSUE TITLE
[Feature Request]: Improve Font Weight on Rules Card in Games List Section

### ISSUE THREAD

**Issue by NarendraKoya999** [ssitvit/Games-and-Go#639]
### Feature Description
- **`Commonly add 3 Rule Points for Every Game.`**
- **`So, Much Space is there for Possibility to Improving Font Weight of Rule Points  `**
- **`I want to Improve Little Bit Font Improvement for Rule Points`**

### Describe breifly how would you implement the same.

Solution_steps:

- Go To 'https://games.ieeessitvit.tech/'
- Scroll Down to **'Games Projects List'**
- **Hovering on Games Card List. Then, Rule Points are came out and Observe Font Lists.**
- **So, Better to improving Font Weight for Better Eye Vision** 

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

### NOTE: I want to work on this ISSUE

**Comment by panwar8279** [comment]
Hi @NarendraKoya999 , I am assigning this issue to you. Kindly complete your work within a week. Good luck!

**Comment by NarendraKoya999** [comment]
Sure @panwar8279

**Comment by NarendraKoya999** [comment]
Hey @panwar8279 . Please close this Related Issue and Merged PR Also.
