### ISSUE TITLE
[Feature Request]: Dark Mode

### ISSUE THREAD

**Issue by shraddha761** [ssitvit/Games-and-Go#643]
### How would you like to enhance the existing project.

I want to add button which change to dark mode 

### Describe breifly how would you implement the same.

Make changes in button which change to dark mode

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @shraddha761 , I am assigning this task to you. Kindly complete your work within a week. Good luck!
