### ISSUE TITLE
[New Game] : GSSOC '23: Archery Game

### ISSUE THREAD

**Issue by sujanrupu** [ssitvit/Games-and-Go#644]
## Game logic and basic description::
Archery game is frontend game developed using HTML, CSS, JavaScript.
In this game the player has to hit the target with the arrows provided and points will be gained according to the number targets hitting and accuracy of hitting.

## Game points::

- A specific number arrows will be provided to the player
- The player has to hit a specific target using those arrows
- If he hits a target successful, then points will be gained
- Points may also vary according to the accuracy of hitting
- If first level the target position will be fixed
- In the second level the target position will also vary.

**Comment by panwar8279** [comment]
Hi @sujanrupu , I am assigning this task to you. Kindly complete your work within a week. Good luck.
