### ISSUE TITLE
[NEW GAME] Adding a Duck Hunt Game

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [ssitvit/Games-and-Go#646]
### Description

I will be adding a duck hunt game using HTML/CSS

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/85278243/36c4cb25-b1d5-4dfe-baec-a651e4515343)

[Screencast from 29-06-23 12:06:36 PM IST.webm](https://github.com/ssitvit/Games-and-Go/assets/85278243/5a5e9dd1-c99c-44ef-86c4-fdddc9656aaa)

### Additional information

Please assign me this under GSSOC'23

**Comment by panwar8279** [comment]
Hi @Swapnil-Singh-99 , I am assigning this task to you. Kindly complete your work within a week. Good luck!
