### ISSUE TITLE
Typing Speed Game

### ISSUE THREAD

**Issue by Prabhroop-Singh2002** [ssitvit/Games-and-Go#65]
Random Text will be displayed and we will find the winner by calculating the typing speed along with accuracy.
![55](https://github.com/ssitvit/Games-and-Go/assets/114666573/75acd85a-ae7d-467b-9ff5-9c7dc821c254)
![66](https://github.com/ssitvit/Games-and-Go/assets/114666573/850011c4-391c-46b4-8900-2c982d32e516)

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly improve the css as well to get an advance label for this project. All the best to your work. Kindly go through the readme and contributing.md for successful merge.

**Comment by vk20july** [comment]
@raj03kumar sir i want to work on this issue under gssoc'23
