### ISSUE TITLE
[NEW GAME] Adding a Classic Minesweeper Game

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [ssitvit/Games-and-Go#650]
### Description

I will be adding a classic minesweeper game made in react 

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/85278243/7db7655d-de22-48da-af79-caa2edffa3a6)

### Additional information

Please assign me this under GSSOC'23

**Comment by panwar8279** [comment]
Hi @Swapnil-Singh-99 , I am assigning this task to you. Kindly complete within a week. Good luck for your work!

**Comment by Swapnil-Singh-99** [comment]
> Hi @Swapnil-Singh-99 , I am assigning this task to you. Kindly complete within a week. Good luck for your work!

Sure 😊

**Comment by Swapnil-Singh-99** [comment]
> Hi @Swapnil-Singh-99 , I am assigning this task to you. Kindly complete within a week. Good luck for your work!

And can I get a level 2 or 3 label ?
