### ISSUE TITLE
Glitch effect and search image

### ISSUE THREAD

**Issue by akanksha984** [ssitvit/Games-and-Go#652]
### How would you like to enhance the existing project.

![image](https://github.com/ssitvit/Games-and-Go/assets/97845909/6540d280-5d34-494d-85dc-a5ecfc610686)
I would like to add an image of magnifying glass in the search bar and also I would like to add glitch effect to the text GAME ON.

Please assign it to me under gssoc'23. I want to work on this issue.

### Describe breifly how would you implement the same.

Solution_steps

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @akanksha984 , I am assigning this task to you. Kindly complete your work within a week. Good luck!
