### ISSUE TITLE
[NEW GAME]  Chrome Dinosaur game

### ISSUE THREAD

**Issue by komalioruganti** [ssitvit/Games-and-Go#653]
### Description

I want to add a new game to the list of games. It is a dinosaur game available on Chrome when there is no internet connection. Because of its familiarity and ease to play, I think this would be an amazing game to add. 

### Screenshots
![image](https://github.com/ssitvit/Games-and-Go/assets/95839946/f841a922-9068-4584-a12f-4380be5091fb)

![image](https://github.com/ssitvit/Games-and-Go/assets/95839946/b38af204-b55e-4913-92cd-0bc3e02d116b)

_No response_

### Additional information
Can you assign me this issue? I will work on it and contribute to this project.

**Comment by panwar8279** [comment]
Hi @komalioruganti , I am assigning this task to you. Kindly complete your work within a week. Good luck!

**Comment by komalioruganti** [comment]
I made a pull request. Can you review it and tell me if any changes are needed?
