### ISSUE TITLE
[NEW GAME] Memory Game

### ISSUE THREAD

**Issue by komalioruganti** [ssitvit/Games-and-Go#654]
### Description

In this game there will 16 different boxes containing 8 different objects which are placed in these boxes randomly.A player has to choose 2 same objects by flipping only 2 cards at a time. If the same object is chosen twice only then it will be flipped around otherwise it will remain unflipped until the right pair is found.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/95839946/e29a634e-70ad-4c36-9a5b-44e4658fda79)

### Additional information

Please assign me this issue. I would love to work on it and contribute to your project.

**Comment by panwar8279** [comment]
@komalioruganti , Memory game is already exist in repository. So give another name to your game.

**Comment by panwar8279** [comment]
Hi @komalioruganti ,I am assigning this task to you. Kindly complete your work within a week. Make sure no any duplicacy will create. Good luck!
