### ISSUE TITLE
[Feature Request]: Play-button is not visible [GSSOC'23]

### ISSUE THREAD

**Issue by priyas32** [ssitvit/Games-and-Go#656]
### How would you like to enhance the existing project.

Enhancement
<img width="1339" alt="Screenshot 2023-06-30 at 5 41 40 PM" src="https://github.com/ssitvit/Games-and-Go/assets/96781240/8f634069-c70b-4324-8abb-f568bb21a95d">

Since the play-button is not visible so by changing its css style we can make it visible.

### Describe breifly how would you implement the same.

Solution_steps
[in folder] games and go -> src -> app.css -> .contentclass [ want to change the style]

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
@priyas32 , someone already working on this issue.
