### ISSUE TITLE
[NEW GAME] Othello/Reversi

### ISSUE THREAD

**Issue by RitiChandak** [ssitvit/Games-and-Go#659]
i want to add a new game to the library othello also know as reversi

The game starts with an 8x8 board with two initial black and two initial white pieces placed in the center.
Players take turns placing their colored pieces on the board. A move is valid if it results in the flipping of at least one opponent's piece in a straight line (horizontally, vertically, or diagonally).
some of the features are :
-to flip the token
-cascading effects
-the corners and edges of the board have special strategic significance in Othello

**Comment by panwar8279** [comment]
Hi @RitiChandak , I am assigning this task to you. Kindly complete within a week. Good luck!

**Comment by RitiChandak** [comment]
Hi @panwar8279, I will do my best to complete this project within a week. Could you please consider upgrading the level? Thank you!
