### ISSUE TITLE
Add Re-Play Button in Ninety Nine

### ISSUE THREAD

**Issue by ishita80** [ssitvit/Games-and-Go#66]
The game is resetting on after we press a number. So, I want to add a re-play button(with margin), so that the user can start playing again. 
You can tell me if you want the re-play button the whole time(so that the user can re-play whenever he/she wants) or only when the game is ended.

**Comment by raj03kumar** [comment]
Assigning this issue to you. Kindly complete it within a week and go through readme.md and contributing.md for successful merge.

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
