### ISSUE TITLE
[NEW GAME] SPACE INVADERS [GSSoC'23]

### ISSUE THREAD

**Issue by varshanim** [ssitvit/Games-and-Go#660]
### Description

Space invaders is a game which was first released in `1978` in which there are aliens in N-rows and they will increase with time and the bottom-most row of the aliens will keep shooting at you space ship. You will be in a spaceship and you can destroy the aliens by shooting at them with the help of your spaceship. When you shoot at an alien it dies(disappears).
This game can be developed by using JavaScript.

## Game points:
You can shoot the Aliens by pressing the space bar and move from left to right to avoid the bullets being shot by the aliens using the left and right arrow keys. If you get shot by the aliens then it will display GAME OVER.

### Screenshots

![Screenshot 2023-06-30 at 9 04 33 PM](https://github.com/ssitvit/Games-and-Go/assets/105119278/82323552-7c38-4d2e-aa96-9459ab1db24a)

### Please assign me this issue under GSSoC'23.

**Comment by panwar8279** [comment]
Hi @varshanim, I am assigning this task to you. Kindly complete your work within a week. Good luck!

**Comment by varshanim** [comment]
@panwar8279 I need two more days to fix this PR as I've not been feeling well for the past few days.
