### ISSUE TITLE
[FEATURE] Doodle jump game

### ISSUE THREAD

**Issue by SimranLahrani842** [ssitvit/Games-and-Go#663]
### Description

Same game as available on playstore.
Score will increase as one goes up and pass all the obstacles.
Will add the game today itself.

**Comment by SimranLahrani842** [comment]
> wave @SimranLahrani842
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
> 
> Please make sure you have given us as much context as possible.

@panwar8279 assign me this...

**Comment by panwar8279** [comment]
Hi @SimranLahrani842 , I am assigning this task to you. Kindly complete your work within a week. Make sure no any duplicacy of game will create. Good luck for your work!
