### ISSUE TITLE
[FEATURE] Snake Game

### ISSUE THREAD

**Issue by SimranLahrani842** [ssitvit/Games-and-Go#664]
### Description

This game is developed by html,css and js tech stacks and you can play it easily by using the arrows !
A snake is given to control which will change it length upon eating
there are fruits which appear randomly one after another.

**Comment by SimranLahrani842** [comment]
> ### Description
> This game is developed by html,css and js tech stacks and you can play it easily by using the arrows ! A snake is given to control which will change it length upon eating there are fruits which appear randomly one after another.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

@panwar8279

**Comment by SimranLahrani842** [comment]
> wave @SimranLahrani842
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
> 
> Please make sure you have given us as much context as possible.

Please assign me this @panwar8279

**Comment by panwar8279** [comment]
Hi @SimranLahrani842 , I am assigning this task to you. Kindly complete your work within a week. Make sure no any duplicacy of game will create. Good luck for your work!
