### ISSUE TITLE
[Bug]:  Unable to see play button and the text play is not centered 

### ISSUE THREAD

**Issue by Adityamishra9719** [ssitvit/Games-and-Go#668]
### Give a brief about the bug discovered✍

Hi , @cleveranu ,i visited you site and observed that the Play button is not visible it .
This is due to incorrect css .

You can see it in below screen shot
![Screenshot 2023-07-01 135414](https://github.com/ssitvit/Games-and-Go/assets/105539123/30771ce0-e0d4-49b2-990e-52d18a10e870)

### What is the expected behavior?

It can be fixed and the expected behavior of this should be like below screen shot 

![Screenshot 2023-07-01 135356](https://github.com/ssitvit/Games-and-Go/assets/105539123/32e69071-d72c-4941-ba6b-33f6d1fe4456)

### Give a brief description to get the expect behaviour.

It can be correct by changing some css in 
**.container_card .card .content a** homepage.css

some how like below css  :-
.container_card .card .content a {
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 0.75rem 0rem;
    margin-bottom: 43px;
    background: #fff;
    color: #000;
    border-radius: 20px;
    text-decoration: none;
    font-weight: 500;
    font-family: "Press Start 2P", cursive;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
    transition: background-color 0.3s ease;
}

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Adityamishra9719 , I am assigning this issue to you. Kindly complete your work within 2 days. Good luck for your work!

**Comment by Adityamishra9719** [comment]
Okk
