### ISSUE TITLE
Snake Water Gun

### ISSUE THREAD

**Issue by Aryan123-rgb** [ssitvit/Games-and-Go#67]
A game very similar to rock paper scissor ,but rather than rock paper and scissor we will be playing with snake water and gun .
1. Snake can drink the water (Snake vs Water -> Snake wins)
2. Gun can shoot the snake (Gun vs Snake -> Gun wins)
3. Water can submerge the gun or basically can make it ineffective (Water vs Gun -> Water wins)

I will create 3 cards and a score card and reset button and make it completely responsive so that it can be played on the mobile devices as well. Also I can deploy on the live server so the users just need internet connection to play the game.

If you like it , please approve the idea and assign it to me under Gssoc-23 . I promise to follow all the code of conducts :)

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week and go through the readme and contributing.md for successful merge.
