### ISSUE TITLE
[FEATURE] Bird Shooter using html and css

### ISSUE THREAD

**Issue by SimranLahrani842** [ssitvit/Games-and-Go#670]
### Description

Game logic and basic description
Hit the birds and kill them to get the score.
Hit the birds at the centre.
A notification will appear that it is killed.

Game points:
Points increase as soon as you hit the bird.

**Comment by SimranLahrani842** [comment]
> wave @SimranLahrani842
> 
> Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
> 
> Please make sure you have given us as much context as possible.

Please assign me this @panwar8279

**Comment by panwar8279** [comment]
Hi @SimranLahrani842 , I am assigning this task to you. Kindly complete your work within a week. Make sure no any duplicacy of game will create. Good luck for your work!
