### ISSUE TITLE
[FEATURE] Cyber Chunk Game

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [ssitvit/Games-and-Go#675]
### Description

Hello @panwar8279 ,
Here is a game which based on the water world developed using HTML, CSS, JS

## Game points - 
1. Responsive
2. Monster Fish
3. Bullet
4. Arrow Key Events
5. Themes

**Comment by panwar8279** [comment]
Hi @SyedImtiyaz-1, please make your game in React js because its react based repository.

**Comment by SyedImtiyaz-1** [comment]
ok
