### ISSUE TITLE
Adding a new game - Color Chase

### ISSUE THREAD

**Issue by aysal04** [ssitvit/Games-and-Go#68]
Its a game in which there are cards of dinstinct colors and using basic js we display a random color and user should click on the same. for the next turn computer displays one more color but this time user should click a pattern of previous card and the present card. Believe me it would be fun playing it to test our memory. I would like to add this game to the website.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete the work in a week and go through the readme and contributing.md for successful merge. All the best to your work.
