### ISSUE TITLE
Classic 2048 game animated version

### ISSUE THREAD

**Issue by rks-031** [ssitvit/Games-and-Go#683]
### Description

`2048` is a popular number puzzle game where the player's objective is to slide numbered tiles on a grid and combine them to reach the elusive number 2048.

The game continuously generates new tiles on the grid after each move. The new tiles appear with a subtle animation, sliding into their designated spot. The player's goal is to keep combining tiles and strategize their moves to reach the highest possible tile value of 2048.

The user also gets to move to a new game as per his/her wish and can also see the score simultaneously while playing.

By utilizing **ReactJS and implementing animations**, this version of the 2048 game offers an engaging and visually appealing gameplay experience, making it enjoyable for players of all ages nostalgic to this game.

### Screenshots

*Initial Look*
![image](https://github.com/ssitvit/Games-and-Go/assets/103258259/6d4a01c2-1212-4bc8-8480-c02f3a4a8fd7)

### Video Illustrations

*While playing*

https://github.com/ssitvit/Games-and-Go/assets/103258259/8ae5b961-f491-4a9b-ac4e-2983dc3c3be6

*On winning*

https://github.com/ssitvit/Games-and-Go/assets/103258259/179d740b-9f95-4f12-b9ac-8c02d4278d10

*Game over*

https://github.com/ssitvit/Games-and-Go/assets/103258259/980e64bf-c367-4c03-8ace-a434f4e11afe

**Comment by panwar8279** [comment]
Hi @rks-031 , I am assigning this task to you. Kindly complete within a week. Good luck!

**Comment by rks-031** [comment]
> Hi @rks-031 , I am assigning this task to you. Kindly complete within a week. Good luck!

@panwar8279 The PR is attached with the issue.
