### ISSUE TITLE
Ball Shooting Game

### ISSUE THREAD

**Issue by Aryan123-rgb** [ssitvit/Games-and-Go#69]
The game is ready to be merged within 2 hours of the approval of this issue
I feel this is more sort of a pull request rather than an issue :) .Thank you

https://github.com/ssitvit/Games-and-Go/assets/118872531/0cbd16af-c9f5-4072-a508-c445a4844b64

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week and go through readme and contributing.md for successful merge. All the best to your work Aryan... !!!

**Comment by Aryan123-rgb** [comment]
@raj03kumar I have created a pr. Kindly review it and tell me if any necessary changes are required


Thank you
