### ISSUE TITLE
[NEW GAME] <Insect Catch Game>

### ISSUE THREAD

**Issue by JadavShraddha** [ssitvit/Games-and-Go#691]
### Description

This game is created with the help of html, css and javascript.
In this game first you can choose your favorite insect.The objective of the game is to catch as many insects as possible within a given time limit.
The insects come in various shapesand they move quickly and unpredictably across the screen.
The catchers must be quick and agile to track the insects' movements and snatch them out of the air.

### Screenshots

<h2>Game points</h2>
change the insect type
show user points and time on screen
sound feature

<h2>Select The Game Type</h2>
Single Player

### Additional information

![image](https://github.com/ssitvit/Games-and-Go/assets/95160083/b50ede2c-35ba-458e-b8bc-38cac2f31d3b)
![image](https://github.com/ssitvit/Games-and-Go/assets/95160083/8edebc08-06d3-4fc0-8e9b-b10cc16175c8)

**Comment by panwar8279** [comment]
Hi @JadavShraddha , I am assigning this task to you. Kindly complete your work within a week. Make sure no any duplicacy of game will create. Good luck for your work!

**Comment by JadavShraddha** [comment]
please merge this PR
