### ISSUE TITLE
[NEW GAME] Guess the number game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Games-and-Go#693]
### Description

- This is a game in which the user has to guess a number from a given range. If the user guesses correctly then the game will show the user guesses the right number by displaying a message.

### Additional information

- If the user guesses the number correctly then the game will greet the user with a message stating he guesses the right number.
- Single player game

**Comment by Avdhesh-Varshney** [comment]
@panwar8279 please assign this game to me to contribute under GSSoC'23 program

**Comment by panwar8279** [comment]
Hi @Avdhesh-Varshney , I am assigning this issue to you. Kindly complete within a week. Make sure you will make your game in react because it's react based repository Good luck!
