### ISSUE TITLE
[NEW GAME] Alphabet Learn Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Games-and-Go#694]
### Description

- This game will show the picture of pressed key on the keyboard
- Also creating a sound and pronounce that letter and a related word to that picture

### Additional information

- This project will be very helpful to the children
- This will boost the knowledge of children
- Learn alphabets and meaning in a funny way

**Comment by Avdhesh-Varshney** [comment]
@panwar8279 please assign this project to me

**Comment by panwar8279** [comment]
Hi @Avdhesh-Varshney , I am assigning this task to you. Kindly complete within a week. Good luck!

**Comment by harsh0628** [comment]
Hlo please assign to me @Avdhesh-Varshney
