### ISSUE TITLE
[NEW GAME] Fifteen game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Games-and-Go#695]
### Description

- The Fifteen Puzzle is a classic sliding puzzle game where the goal is to rearrange the tiles in numerical order by sliding them into the empty space. 
- This implementation of the game is built using HTML, CSS, and JavaScript.
- The game consists of a 4x4 grid with fifteen numbered tiles and one empty space.
- To make a move, click on a tile adjacent to the empty space. The clicked tile will slide into the empty space.
- The goal is to arrange the tiles in numerical order, from 1 to 15, starting from the top-left corner and leaving the bottom-right cell empty.

### Additional information

- This game will boost the problem solving skills of the player

**Comment by Avdhesh-Varshney** [comment]
@panwar8279 please assign this project to me to contribute under GSSoC'23 program

**Comment by panwar8279** [comment]
Hi @Avdhesh-Varshney , I am assigning this task to you. Kindly complete within a week. Good luck!
