### ISSUE TITLE
[NEW GAME] Memorizing the cards game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Games-and-Go#696]
### Description

- Display the cards face-down in a grid pattern on the webpage.
- Allow the player to click on a card.
- When a card is clicked, reveal its symbol.
- Track the number of flipped cards.
- If it's the first card flipped, remember it.
- If it's the second card flipped:
- Compare the symbols of the two cards.
- If they match, keep them face-up.
- If they don't match, flip them face-down after a short delay.
- Allow the player to continue selecting pairs of cards.
- Keep track of the number of attempts or time taken.
- Once all cards are matched, display the player's score.

**Comment by Avdhesh-Varshney** [comment]
@admindebu @panwar8279 please assign this game to me

**Comment by panwar8279** [comment]
Hi @Avdhesh-Varshney ,I am assigning this task to you. Kindly complete within a week. Good luck!
