### ISSUE TITLE
search bar should be on top[Feature Request]: 

### ISSUE THREAD

**Issue by DIVYANSHURATHAUR** [ssitvit/Games-and-Go#697]
### How would you like to enhance the existing project.

it will be easy for others to search

### Describe breifly how would you implement the same.

there should be a sign to indicate that scroll down to play games

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @DIVYANSHURATHAUR , I am assigning this issue to you. Kindly complete within a week. Good luck!
