### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by vibgyor786** [ssitvit/Games-and-Go#7]

**Comment by amitmishra11** [comment]
@vibgyor786 can I work on this?

**Comment by vibgyor786** [comment]
ok @amitmishra11 i am assigning this issue to you

**Comment by vibgyor786** [comment]
@amitmishra11 try to make it look better , then i will add your pr under hacktoberfest-accepted .

**Comment by iamparas0** [comment]
I am a graphic designer and worked on ui/ux , i can make the ui more comfortable view by adjusting and resizing components, please assign it to me.
