### ISSUE TITLE
Puzzle Slider 

### ISSUE THREAD

**Issue by Iron-Thunder** [ssitvit/Games-and-Go#70]
Want to add a puzzle slider game where players can solve a maths puzzle by sliding the numbers in their screen
![image](https://github.com/ssitvit/Games-and-Go/assets/103611908/2d116dcc-3af8-424a-912e-0c3a3fecd378)

**Comment by Iron-Thunder** [comment]
I want to work on this issue of adding this new game. So please assign me this issue.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week and go through the readme and contributing.md for successful merge. All the best to your work.
