### ISSUE TITLE
[NEW GAME] Pong game

### ISSUE THREAD

**Issue by jaivsh** [ssitvit/Games-and-Go#701]
### Description

I'd design a regular pong game that the users can play against the computer. It would be a 2d game that would simulate the table tennis. 

Tech stack: HTML, CSS, Javascript

**Comment by jaivsh** [comment]
@panwar8279 please assign me this! Thanks

**Comment by panwar8279** [comment]
Hi @jaivsh , I am assigning this task to you. Kindly complete within a week. Make sure you will make your project in react because its a react based repository. Good luck!
