### ISSUE TITLE
[Feature Request]: Improve UI of Search bar in Home page

### ISSUE THREAD

**Issue by Geeta259** [ssitvit/Games-and-Go#704]
### How would you like to enhance the existing project.

Enhancement

Improved Search bar section by added some CSS properties on it to look it good.
Add search icon embedded on search bar
Make it responsive in all devices

![Screenshot (542)](https://github.com/ssitvit/Games-and-Go/assets/75520947/63284dd9-61f9-4f5a-b0b1-b87db37e641d)

### Describe breifly how would you implement the same.

here is demo:
![Screenshot (540)](https://github.com/ssitvit/Games-and-Go/assets/75520947/38198d85-889f-45b7-94f4-658a45acfca5)

@panwar8279 I would like to work on it . Please assign this to me!!

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Geeta259 , I am assigning this task to you. Kindly complete your work within a week. Good luck.

**Comment by Geeta259** [comment]
@panwar8279 Can you please guide me how can I run this project in localhost . Can not be able to preview this in localhost.
which dependencies I have to install to preview this site.
