### ISSUE TITLE
[Feature Request]:  Urgent correction is needed in the main page layout

### ISSUE THREAD

**Issue by Dimple-01** [ssitvit/Games-and-Go#705]
### How would you like to enhance the existing project.

**Issue**

 **PlayNow !**  **button is not visible. How anyone could play games?**

Earlier I have worked on this project, that time the main page layout was quite good, but now it is totally clumsy. It looks very irritating and confusing. This will decrease user engagement and user interest.

**See Current behavior**

![Screenshot (147)](https://github.com/ssitvit/Games-and-Go/assets/114878264/b3998bbc-d762-4fc0-ac63-48057fabddd9)

![Screenshot (146)](https://github.com/ssitvit/Games-and-Go/assets/114878264/bbb589a1-f27b-478d-a76b-18743cb861fd)

### Describe breifly how would you implement the same.

Solution_steps

1. I will work on font sizes, alignments, and adjustments with the container.
2.  I would add CSS to give it proper margin, padding, alignment, and other necessary features as per the requirement.
3.  later I would add more features to make it totally good.

**I want to work on this issue immediately.
Please assign this work to me, I would complete this task within few hours**

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Dimple-01 , I am assigning this issue to you. Kindly complete your work within a week. Good luck for your work!

**Comment by Dimple-01** [comment]
Dear Ssitvit/Games-And-Go,

I have already made a pull request on this work please merge that.

Regards
Dimple
