### ISSUE TITLE
[NEW GAME] Hangman - built using HTML, CSS and JS

### ISSUE THREAD

**Issue by parridhi** [ssitvit/Games-and-Go#706]
# 💥 Hey! I want to add a new game, HANGMAN, under the games section.

#### Could you please assign this issue to me?

**Comment by panwar8279** [comment]
Hi @parridhi , I am assigning this task to you. Kindly complete your work within a week. Make sure no any duplicacy of game will create. Good luck for your work!

**Comment by parridhi** [comment]
Thank you for assigning this issue to me! On it.
