### ISSUE TITLE
Add a making a tower game 

### ISSUE THREAD

**Issue by Arnabhit** [ssitvit/Games-and-Go#71]
In this game a initial block will be present and multiple block will pass above it. We have to stop the block exactly above the initial block to increase the size of the tower. As soon as the lenght and width of a block becomes zero the game stops. Please assign this issue to me so that i can contribute in GSSOC 23.

**Comment by raj03kumar** [comment]
Assigning this issue to you. Kindly complete it within a week and go through the readme and contributing.md for successful merge. All the best to your work.

**Comment by rv1830** [comment]
please assign this to me

**Comment by singh-anushka** [comment]
@raj03kumar can you please assign me this game?

**Comment by raj03kumar** [comment]
> @raj03kumar can you please assign me this game? Since the previous assignment is revoked.

Kindly create a new issue. Will assign it to u

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by soorjya** [comment]
please assign me this issue under GSSoC'23.
