### ISSUE TITLE
The contents on cards is not visible properly.

### ISSUE THREAD

**Issue by PiyushK79** [ssitvit/Games-and-Go#710]
### How would you like to enhance the existing project.

Enhancement - 
I would like to change the ui of the cards and make it more related to the theme.
[](url)
![games](https://github.com/ssitvit/Games-and-Go/assets/100259650/07fb5ad4-abcd-4d70-94ad-63a443536de0)

### Describe breifly how would you implement the same.

Solution_steps
I would change the font sizes and apply another effect in order to get clear reading of the card components.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by PiyushK79** [comment]
Please assign this issue to me so I can start working on it.

**Comment by panwar8279** [comment]
Hi @PiyushK79 , I am assigning this issue to you. Kindly complete your work within a week. Good luck for your work!

**Comment by PiyushK79** [comment]
I will start working on it from today itself. Thanks!
