### ISSUE TITLE
[FEATURE] Rock paper scissor

### ISSUE THREAD

**Issue by SimranLahrani842** [ssitvit/Games-and-Go#714]
### Description

Game with html,css and js.
User has three options Rock paper and scissor.
The game is made in a simple manner and easy to play with

**Comment by panwar8279** [comment]
Hi @SimranLahrani842 , I am assigning this task to you. Kindly complete your work within a week. Make sure no any duplicacy of game will create. Good luck for your work!

**Comment by SimranLahrani842** [comment]
> Hello @SimranLahrani842, thank you for raising an issue. raised_hands I have assigned the issue to you. You can now start working on it. If you encounter any problems, please feel free to connect with us. +1

Sure mam can u check my issue no #629 ?
