### ISSUE TITLE
Blackjack

### ISSUE THREAD

**Issue by Iron-Thunder** [ssitvit/Games-and-Go#72]
Want to add a simplified version of the blackjack card game where players try to get a hand value as close to 21 as possible without exceeding it.

**Comment by Iron-Thunder** [comment]
I want to work on this issue of adding this game. So please assign me this issue under GSSOC'23

**Comment by KaviRana** [comment]
I have created a blackjack game before. Can this issue be assigned to me?

**Comment by raj03kumar** [comment]
Assigning this issue to you. Kindly complete it within 1 week and go through the readme and contributing.md for successful merge. All the best with your work...

**Comment by anan262** [comment]
I want to tackle this one as I have done this game as part of my project before
