### ISSUE TITLE
[FEATURE]: Snakes And Ladders Game

### ISSUE THREAD

**Issue by Keyuri-19** [ssitvit/Games-and-Go#731]
### Description

Snakes and Ladders is the well known game. Here the game is made with the help of HTML, CSS and JavaScript
here you have to roll your dice when it's your turn and according to the number you have to move your pieces 
on the board where snakes will eat you and drop you down and ladder will take you upwards.

### Screenshots

![Snakes and Ladders](https://github.com/ssitvit/Games-and-Go/assets/115471178/85bcce86-ff11-495a-a1ed-bf33232ee001)

**Comment by Keyuri-19** [comment]
@panwar8279  Please assign these issue to me under gssoc23

**Comment by panwar8279** [comment]
Hi @Keyuri-19 , I am assigning this task to you. Kindly complete within a week. Make sure your project is in react, because it's react based repository. Good luck!
