### ISSUE TITLE
[FEATURE] Add prettier linter

### ISSUE THREAD

**Issue by Abhinavcode13** [ssitvit/Games-and-Go#732]
### Description

Prettier enforces a consistent code style across your YAML files. It automatically formats your code according to a set of predefined rules, ensuring that the codebase looks uniform and is easier to read.

**Comment by Abhinavcode13** [comment]
@panwar8279 please assign me

**Comment by panwar8279** [comment]
Hi @Abhinavcode13 , I am assigning  this task to you. Kindly complete your work within a week. Good luck!
