### ISSUE TITLE
[FEATURE] MAGIC MATCH

### ISSUE THREAD

**Issue by Parul1606** [ssitvit/Games-and-Go#745]
### Description

I would like to add Memory magic match game to the project.
A grid of cards is displayed on the game board, typically faced down at the beginning of the game.
Each card has a matching pair in the grid. The objective is to find and match all pairs of cards.
Players can click or tap on a card to reveal its face.
Please assign me this project I would like to work on it under gssoc.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/80768852/3e387bdd-5833-4f1a-b07a-99956a7b0071)

**Comment by panwar8279** [comment]
Hi @Parul1606 , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make game in react because it's react based repository. Good luck for your work!

**Comment by Parul1606** [comment]
Yes, I'm working on it. I'm in the last stage of the project. I'm busy with my college too as it is started too. Sorry for submitting it late. PR will be created by tomorrow evening.
