### ISSUE TITLE
[Bug]: BUG IN THE DIV WHERE GAMES ARE REPRESENTED

### ISSUE THREAD

**Issue by marshadkhn** [ssitvit/Games-and-Go#749]
### Hey @panwar8279 
_I found a BUG in the game selection where all the games are stored_ 

**_Following are the bugs:_**
1. The text in card is not aligned and looks very odd, like it is spreaded all over the box 
2. The number of game is also not right in every box in some box it is fully visible and in some it's not

![FireShot Capture 002 - Games-And-Go - localhost](https://github.com/ssitvit/Games-and-Go/assets/80325579/c2f2efdf-d370-4a59-940b-ec96d5e8c993)

### What is the expected behavior?

The name of game should be in one or two line in the bottom of card so that is should visible and the number of game should be visible clearly

### Give a brief description to get the expect behaviour.

NONE

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @marshadkhn , I have assigned this issue to you. Kindly complete within 4 days. Good luck!

**Comment by marshadkhn** [comment]
For sure

**Comment by marshadkhn** [comment]
This issue is done
