### ISSUE TITLE
[FEATURE] Tekken 3 game

### ISSUE THREAD

**Issue by marshadkhn** [ssitvit/Games-and-Go#750]
### Description

**Hey @panwar8279 
I want to add a game similar to tekken 3**

### About the game:
- It is a 2 character game one is soldier and one is wizard
- Both have a limited amount of life
- You have to fight with each other
- You can play with computer or in two player mode
- You have 3 rounds like tekken 3 the one who has more winning rounds will win

### Screenshots

![207382595-5d20c1ce-2713-4198-8989-9b341294eb1d](https://github.com/ssitvit/Games-and-Go/assets/80325579/a393bfa1-b4d1-407c-9a19-5bedf2ec00db)
![207382999-e6e210bb-a54d-48f0-81fe-fcb51066358c](https://github.com/ssitvit/Games-and-Go/assets/80325579/1541fc40-390a-435f-9194-ce0fc2d48b8a)

### Additional information

NONE

**Comment by panwar8279** [comment]
Hi @marshadkhn, I have assigned this task to you. Kindly complete your work within a week. Make sure you will make game in react because it's react based repository. Good luck for your work!

**Comment by marshadkhn** [comment]
@panwar8279
