### ISSUE TITLE
[FEATURE] Add a well designed FOOTER

### ISSUE THREAD

**Issue by marshadkhn** [ssitvit/Games-and-Go#751]
### Description

**_Hey @panwar8279, the repo is awesome, but the website does not have any footer at all
I will like to add footer in the website
Assign me this issue for this add-on_**

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/80325579/c203d5ad-1ed0-451b-9df5-c3aad31394d6)

### Additional information

NONE

**Comment by panwar8279** [comment]
Hi @marshadkhn , i have assigned this task to you. Kindly complete your work within a week. Good luck!

**Comment by marshadkhn** [comment]
@panwar8279 you accidentally labeled hacktoberfest
