### ISSUE TITLE
[FEATURE] Add Floating Particles in Background

### ISSUE THREAD

**Issue by 5h0ov** [ssitvit/Games-and-Go#756]
### Description

I would like to add floating particles in the background to give the webpage a more lively feeling.
I will make it compatible with the Light/Dark Theme switch.

# Preview Concept:

![particles](https://github.com/ssitvit/Games-and-Go/assets/83227649/9566bb69-f154-4653-8fa7-1ce2b78a44d8)

It would be great to contribute to this repo uner GSSoC'23

**Comment by panwar8279** [comment]
Hi @5h0ov , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make game in react because it's react based repository. Good luck for your work!
