### ISSUE TITLE
[FEATURE] Add 2048 game

### ISSUE THREAD

**Issue by PVBharadwaj** [ssitvit/Games-and-Go#762]
### Description

I would like to add 2048 game to the website.

**Comment by PVBharadwaj** [comment]
@panwar8279 please assign me this issue under gssoc'23

**Comment by panwar8279** [comment]
Hi @PVBharadwaj ,  I have assigned this task to you. Kindly complete your work within a week. Male sure you will make your game in react because it's react based repository. Good luck!

**Comment by PVBharadwaj** [comment]
@panwar8279  thank you for assigning me this issue. 
I have raised the PR #818 regarding this issue. Please review and merge it under GSSoC'23
