### ISSUE TITLE
[DOCS] Include a direct link for CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by jfmartinz** [ssitvit/Games-and-Go#763]
### Description

In the `Code of Conduct 💚` section, I suggest adding a direct link to the guidelines on ` CODE_OF_CONDUCT.md`. This improvement would make it easier for contributors to find the documentation without having to search for it manually. By implementing this enhancement, it will greatly enhance productivity and improve the overall user experience for everyone.

### Screenshots

Before:
![image](https://github.com/ssitvit/Games-and-Go/assets/129386460/04b5d3f6-0e6f-4b29-b71b-57089da4b691)
Expected: 
![image](https://github.com/ssitvit/Games-and-Go/assets/129386460/492c1510-79c1-4e9d-bfef-b5b568ee8add)

### Additional information

Assign this issue to me under GSSOC23

**Comment by jfmartinz** [comment]
assign this issue to me @panwar8279 Thank you!!

**Comment by panwar8279** [comment]
Hi @jfmartinz ,  I have assigned this task to you. Kindly complete your work within 2 days. Good luck!
