### ISSUE TITLE
Back to top button need to be fixed

### ISSUE THREAD

**Issue by harshita-2003** [ssitvit/Games-and-Go#767]
### Description

back to top button is animating to very low and should up-down in the given center only

**Comment by spruhakar5** [comment]
kindly assign me this issue under gssoc'23

**Comment by panwar8279** [comment]
Hi @harshita-2003 ,  I have assigned this issue to you. Kindly complete your work within a week. Good luck!

**Comment by harshita-2003** [comment]
hey @panwar8279 can you look into this box shadow design and let me know if you like it , I will create the pr 


https://github.com/ssitvit/Games-and-Go/assets/119532943/28529ab2-77d4-4811-8791-00eab7179e08
