### ISSUE TITLE
[Bug] Words overlapping on tic-tac-toe game card

### ISSUE THREAD

**Issue by siddhant-dalvi** [ssitvit/Games-and-Go#768]
### Description

Words are overlapping on tic-tac-toe game card

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/93437464/9317922b-7e5f-471c-b4bc-e04d6cf44d53)

**Comment by siddhant-dalvi** [comment]
@panwar8279 assign me this issue under GSSoC' 23

**Comment by panwar8279** [comment]
Hi @siddhant-dalvi , I have assigned this issue to you. Kindly complete your work within a week. Good luck!
