### ISSUE TITLE
[Bug]: COPYRIGHT NOT VISIBLE ON LIGHT MODE 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#769]
### Give a brief about the bug discovered✍

- The copyright text is not visible on Light Mode, it's only visible on Dark Mode.

### What is the expected behavior?

- The text should be changed to black color during the light mode otherwise the copyright wouldn't been seen by the user.

### Screenshots

| DARK MODE | LIGHT MODE |
|  :-----:   | :-----:  |
| ![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/8d1ad3e0-49cd-428b-8aa9-41cb602e9618) | ![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/04123c22-282e-4713-b5d5-6e66abdd0848)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this issue to you. Kindly complete your work within a week. Good luck!
