### ISSUE TITLE
Jump and Run Game 

### ISSUE THREAD

**Issue by Vidhi-44** [ssitvit/Games-and-Go#77]
The Jump and run game will be a fun game . There may be object and there would be hurdles for which it has to Jump the hurdles and run it from there . It will be coded using HTML, CSS and Javascript .

Simple but attractive UI .
Good color combination .
After every hurdle crossed some points will be added .
A Congratulation message in the end.

Please assign me this issue under Gssoc-23

**Comment by raj03kumar** [comment]
Assigning this issue to you. Kindly complete it within 1 week and go through readme and contributing.md for successful merge. Good Luck !!!

**Comment by rv1830** [comment]
please assign this to me

**Comment by Vidhi-44** [comment]
> Assigning this issue to you. Kindly complete it within 1 week and go through readme and contributing.md for successful merge. Good Luck !!!

Yess ... I will do this . Thankyou !
