### ISSUE TITLE
Game On is not visible in light mode

### ISSUE THREAD

**Issue by krutikajichkar** [ssitvit/Games-and-Go#776]
### Description

Game on is not visible in light mode , i want to fix that , please assign me this under gssoc'23

### Screenshots

Dark Mode 

![Screenshot (148)](https://github.com/ssitvit/Games-and-Go/assets/93243210/ac5a13f3-cd02-4cd6-8f00-72309102d17f)

Light Mode

![Screenshot (147)](https://github.com/ssitvit/Games-and-Go/assets/93243210/a3762ab2-57ee-44a0-ab8e-cc2d921657e3)

**Comment by panwar8279** [comment]
Hi @krutikajichkar , I have assigned this issue to you. Kindly complete your work within 3 days. Good luck!
