### ISSUE TITLE
Adding Chatbot  

### ISSUE THREAD

**Issue by SrishtiSonam** [ssitvit/Games-and-Go#777]
### Description

The chatbot will allow the user to explore the website fully.
* It will answer the frequently asked questions. [FAQ]
* Show the best use of the website for the user.
* ### Suggest the game - which suits best according to user choice. 

**An User Interacting Feature.**

### Additional information

Assign me under Gssoc'23.

**Comment by panwar8279** [comment]
Hi @SrishtiSonam, i have assigned this task to you. Kindly complete your work within a week. Good luck!
