### ISSUE TITLE
[FEATURE] : Add Reunion Game

### ISSUE THREAD

**Issue by Durgesh4993** [ssitvit/Games-and-Go#779]
### Description

Two friends are lost and the path between them is broken. Build the path by filling up broken parts with falling pieces and help them to reunite.

Screenshot:
![image](https://github.com/ssitvit/Games-and-Go/assets/98798977/75173808-0e25-42b6-9174-17aeda59ceb0)

### Screenshots

Demo vedio:

https://github.com/ssitvit/Games-and-Go/assets/98798977/5ddb7604-cfed-4d12-bb66-d32c6b9d5280

### Additional information

@panwar8279 @cleveranu please assign this task to me

**Comment by panwar8279** [comment]
Hi @Durgesh4993 , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!

**Comment by Durgesh4993** [comment]
@panwar8279 This game is in javascript, Can i send a PR

**Comment by Durgesh4993** [comment]
Thank you
