### ISSUE TITLE
[New Game] Classic Chess Game

### ISSUE THREAD

**Issue by mahendraDew** [ssitvit/Games-and-Go#786]
### Description

Chess is a board game for two players. Chess is a game played between two opponents on opposite sides of a board containing 64 squares of alternating colors. Each player has 16 pieces: 1 king, 1 queen, 2 rooks, 2 bishops, 2 knights, and 8 pawns. The goal of the game is to checkmate the other king.

This is a multiplayer game, two player should be there to play this game;

### Screenshots

![Chess_Game](https://github.com/ssitvit/Games-and-Go/assets/98692513/3bddec98-bc42-401f-a71c-142f32a1d3b6)

### Additional information

This game is completely based on HTML, CSS, and Javascript with some cool sound effects.

I wish to contribute towards the above mentioned issues in under GSSOC'23.

**Comment by panwar8279** [comment]
Hi @mahendraDew, I have assigned this task to you. Kindly complete your work within a week. Male sure you will make your game in react because it's react based repository. Good luck!
