### ISSUE TITLE
Whack-a-mole Game

### ISSUE THREAD

**Issue by Mansi1236** [ssitvit/Games-and-Go#79]
In this game players have to earn points by clicking on randomly appearing moles.
I would like to work on this issue under GSSoC'23, kindly assign this to me.

**Comment by raj03kumar** [comment]
Assigning this issue to you. Kindly complete it within 1 week and go through the instructions in readme and contributing.md for successful merge.

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
