### ISSUE TITLE
[FEATURE] <description> Number Guessing Game

### ISSUE THREAD

**Issue by DhananjayGoyalGL** [ssitvit/Games-and-Go#792]
### Description

A game in which user has to guess a number, and will get a response as the number is less, more or correct along with an option to reset.

**Comment by panwar8279** [comment]
Hi @DhananjayGoyalGL ,  I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!

**Comment by DhananjayGoyalGL** [comment]
> Hi @DhananjayGoyalGL ,  I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!

Surely I will do it. Can I use Vanella JavaScript?

**Comment by DhananjayGoyalGL** [comment]
Hi @panwar8279, I have raised a pull request. It works fine on my side but fails deployment, can you please check the issue..
