### ISSUE TITLE
[New Game]: Cubula cube matching game

### ISSUE THREAD

**Issue by jaivsh** [ssitvit/Games-and-Go#794]
### Description

```In this game, the view of a cube is given which consists of 27 (3x3x3) smaller cubes. Each of them is either black or white (dark or light). The cubes are semi-transparent: If the player looks at a position where all cubes are white then it looks white, white and black cubes together look gray and a position where all cubes are black looks black. The view (from all 6 sides) of the large cube is displayed on the right side. The player's task is to find out the colors of the smaller cubes. First they would choose a color by interacting with the game UI and after that click on the fields which (the player thinks) has the same color. If the player makes a mistake, then the game is over. The game is solved when the colors of all fields are found out.```

### Screenshots

<img width="1470" alt="Screenshot 2023-07-15 at 2 37 24 AM" src="https://github.com/ssitvit/Games-and-Go/assets/93859359/9e50624c-7ffd-458b-a96f-079571e396a8">

**Comment by jaivsh** [comment]
@panwar8279 please assign me this!

**Comment by panwar8279** [comment]
Hi @jaivsh , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!
