### ISSUE TITLE
Pong game remove

### ISSUE THREAD

**Issue by BhartiNagpure** [ssitvit/Games-and-Go#795]
### Description

I want to remove pong game as  it not set the proper route.
It shows 404 page.

### Screenshots

![Screenshot 2023-07-15 063215](https://github.com/ssitvit/Games-and-Go/assets/104631882/9d76a74f-bab4-41f2-88c4-fd44443d5370)

**Comment by panwar8279** [comment]
Hi @BhartiNagpure , you have to find the root of this game and fix 404 error. Remove game from repository is not the solution.

**Comment by BhartiNagpure** [comment]
> Hi @BhartiNagpure , you have to find the root of this game and fix 404 error. Remove game from repository is not the solution.

Ok

**Comment by BhartiNagpure** [comment]
@panwar8279 Pong game is build by using HTML,CSS, JavaScript that's  why it not route properly .
Can I remove it .
Actually some projects are built in web development and that's why it is not deployed in main project so can I remove them.

**Comment by panwar8279** [comment]
Hi @BhartiNagpure , I have assigned this task to you. Kindly complete your work within a week. Good luck
