### ISSUE TITLE
BUG: TEXT OVERLAPPING ON CARD DURING HOVER 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#796]
### Description

- The text is like behaving like a layer during Hover state of the card, this makes the card look horrible.
- This is simply because flipping the both sides each other without proper style manipulation.

### Screenshots

https://github.com/ssitvit/Games-and-Go/assets/92252895/009469bc-89b5-4209-9af8-eed957333956

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this issue to you. Kindly complete your work within  2 days. Good luck!
