### ISSUE TITLE
[FEATURE]: ACCESSIBLE SOCIAL ANCHORS 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#797]
### Description

- This feature is about adding `aria-label` for social anchors (links like Github) which are placed inside the `footer` element

- it is important to note that we want to add the `title` attribute also. This is because the `title` attribute is intended to provide additional information to screen reader users.

- The `aria-label` attribute is a way more important for providing accessibility information to screen reader users. The `aria-label` attribute is an Accessible Rich Internet Applications (ARIA) attribute that can be used to provide a label for an element. This label is then read aloud by screen readers, providing additional information about the element to the user.

- In general, the `aria-label` & `title` attributes are preferred for providing accessibility information to screen reader users.

- You can consider to assign this issue to me to make the site accessible for screen readers

### Screenshots (Going to make changes on these elements)

![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/6b9e6789-6019-443b-a359-55c10455f389)

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assignment assigned this task to you. Kindly complete your work within 2 days. Good luck!
