### ISSUE TITLE
[REVAMP]: FONT TYPO FOR ABOUT SECTION 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#800]
### Description

- Current Font Typo seems like a bit outdated style, it doesn't matches the site's gaming theme
- We need to update the Font's style so that it can give a fresh look.

### Screenshots

| CURRENT STATE | DESIRED STATE |
|  :-----:   | :-----:  |
| ![](https://github.com/ssitvit/Games-and-Go/assets/92252895/114f80ec-ae67-446d-bf3f-87cf0a81d327) |![](https://github.com/ssitvit/Games-and-Go/assets/92252895/e67526a2-d1c0-456e-acb2-8f278fd8f171)  |

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this task to you. Kindly complete within 4 days. Good luck!
