### ISSUE TITLE
[GSSoC'23] [Adding New project] Simon Game

### ISSUE THREAD

**Issue by BhumicaPG** [ssitvit/Games-and-Go#801]
### Description

Get ready to exercise your brain!
The Simon game is an exciting⚡game of
lights  and sounds  in which players must repeat
random sequences of lights by pressing the colored 
Boxes in the correct order. Repeat the patterns
and advance to higher levels.

### Screenshots

<img width="1077" alt="2018-11-03_20-37-03-f8e9648fddd7236558c739afef017710" src="https://github.com/ssitvit/Games-and-Go/assets/95531637/d890de04-f378-47bc-969c-3b1bfe22a70f">

###
![2018-11-23_09-49-03-527fa36bbbe4e89b5237b5ab4066023e](https://github.com/ssitvit/Games-and-Go/assets/95531637/f075654d-1084-4a05-8dde-a3642028f18f)

###
![2018-11-22_12-17-15-9e39ea8dd319de8b5a113e444a0d4262](https://github.com/ssitvit/Games-and-Go/assets/95531637/f5b65ce1-a2f7-4d6f-b447-a5bd558e3682)

### Additional information

• Classic Simon gameplay!
• Follow lights and sounds!
• Suspense builds as sequences get longer!

**Comment by panwar8279** [comment]
Hi @BhumicaPG , I have assigned this task to you. Kindly complete within a week. Make sure you will make your game in react because it's react based repository. Good luck!
