### ISSUE TITLE
[GSSoC'23][Adding new project] Memory Card game

### ISSUE THREAD

**Issue by BhumicaPG** [ssitvit/Games-and-Go#802]
### Description

- Memory Game, also known as the Concentration card game or Matching Game, is a classic card-flipping game where players test their memory skills by matching cards. The game aims to flip over two cards at a time and find all the matching pairs within the specified number of moves.

### Screenshots

![Screenshot 2023-07-15 103704](https://github.com/ssitvit/Games-and-Go/assets/95531637/4b4919dd-3c68-4426-95e4-48232aee3b9f)

###
![Screenshot 2023-07-15 103721](https://github.com/ssitvit/Games-and-Go/assets/95531637/9593a434-df70-48c9-8665-6632a3f80c30)

### Additional information

Functionalities:
- You will start by flipping over one card
- If the next card you flip matches, both the cards will stay flipped and moves increases by 1. 
- If the next card you flip does not match, the cards flip back.
- The game continues until you match all the cards on the board.
- Timer will be running for 5 minutes, after this the game ends.move

**Comment by panwar8279** [comment]
Hi @BhumicaPG ,I have assigned this task to you. Kindly complete within a week. Make sure you will make your game in react because it's react based repository. Good luck!

**Comment by BhumicaPG** [comment]
I've completed the task and sent a pull request, I hope it gets merged soon.
Thank you ☺️
