### ISSUE TITLE
[FEATURE] Adding falling dots game

### ISSUE THREAD

**Issue by sunayana-01** [ssitvit/Games-and-Go#806]
### Description

In this game, the user needs to tap on the balls that are falling down.

- The user can control the speed of dots falling down.
- High score is awarded for smaller dots tapped.
- The higher score is awarded if speed is maximum.
- Game ends once the ball falls down and hits the boundary.
- Hitting/Tapping red balls results in the reduction of points.

Dots appear randomly and are of random colors.

### Screenshots

<img width="536" alt="image" src="https://github.com/ssitvit/Games-and-Go/assets/79215056/ec4da914-63c6-4a74-b27d-660dd8ebe7f7">

### Additional information

Please assign me this issue to work under GSsoc'23.

**Comment by panwar8279** [comment]
Hi @sunayana-01 , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!
