### ISSUE TITLE
Flip card front width and height is not correct (not same as flip card back)

### ISSUE THREAD

**Issue by adityakmrmishra** [ssitvit/Games-and-Go#807]
### Description

Hi , @cleveranu ,i visited your site and observed that the  _**Flip card Front is not of  proper width and height  .
The card is out of border.**_
This is due to incorrect css .

This can be clearly seen in the below screen shot:-

### Screenshots

![Screenshot 2023-07-15 161808](https://github.com/ssitvit/Games-and-Go/assets/105539123/3a8a414d-07ba-426c-9369-a5f9b318b07d)

### What is the expected behavior?

It can be fixed and the expected behavior of this should be like below screen shot 
![Screenshot 2023-07-15 161950](https://github.com/ssitvit/Games-and-Go/assets/105539123/358756bb-9f99-4417-ad95-904164d27996)

### Additional information

_It can be correct by changing some css in 
Flip Card Front homepage.css_

some how like below css  :-

.flip-card-front {
  background-color: rgba(255, 255, 255, 0.1);
  width: 216px;
  height: 10.9rem;
  color: black;
  padding: 13px;
}

_

The last issue i solved was the Play button hidden issue

_ 

**_I want to work on this .
Please assign this to me_**

**Comment by 0xabdulkhalid** [comment]
There's no such things as you depicted on your first screenshot.

Make sure to try once again, take a look here there's no problems with card's width and height.

Thank you.

https://github.com/ssitvit/Games-and-Go/assets/92252895/5a8a1e5b-e3f3-4e5c-8e06-2406d1ef59a7

**Comment by Adityamishra9719** [comment]
There is a confusion it is fine at [SSIT LIVE](https://games.ieeessitvit.tech/) here but my branch is upto date and I think that the deployed version is fine but the git hub code is not fine .
