### ISSUE TITLE
[Feature Request]: social media logos

### ISSUE THREAD

**Issue by krutikajichkar** [ssitvit/Games-and-Go#809]
### How would you like to enhance the existing project.

Social media logos should be white in dark theme as they are black now , please assign me this under gssoc'23

![Screenshot (163)](https://github.com/ssitvit/Games-and-Go/assets/93243210/c24526de-badb-4c70-880f-6cb159ee361d)

### Describe breifly how would you implement the same.

i will give white color to the icons in dark theme

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @krutikajichkar , i have assigned this issue to you. Kindly complete within 4 days. Good luck!
