### ISSUE TITLE
Adding pacman game

### ISSUE THREAD

**Issue by anan262** [ssitvit/Games-and-Go#81]
Adding pacman would be a good choice to a retro kinda website and I'm confident in implementing the same

**Comment by TUSHARGOTHWAL** [comment]
Heyy I would like to add PacMan in this amazing project!!!
looking forward to it.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete the work in a week and also go through the readme and contributing.md for successful merge. All the best to your work Tushar... !!!

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
