### ISSUE TITLE
[FEATURE]: SOUND EFFECT FOR THEME TOGGLE BUTTON 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#810]
### Description

- We need to add sound effects while the user toggles the theme.
- There will be two types of sound effects one for Light mode toggle and another one for Dark mode toggle.
- This feature will be give an active feedback to the users which improves the user experience.

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this task to you. Kindly complete within 4 days. Good luck!
