### ISSUE TITLE
[BUG]: INCORRECT PADDING FOR GAMES CONTAINER 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#811]
### Description

- The container which holds all the games is just have incorrect padding values, so that the container measurement itself looks imbalanced.
- We want to solve this issue by providing right values so that the container would attain a balanced padding to improve the user interface.

### Screenshots

| CURRENT | DESIRED |
| :---: | :---: |
| ![Before](https://github.com/ssitvit/Games-and-Go/assets/92252895/acadffe1-52f3-4628-bc3f-2bd54808f4f5) |![After](https://github.com/ssitvit/Games-and-Go/assets/92252895/086cdb09-3676-4367-962e-c029e8dc425c) |

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this issue to you. Kindly complete within 3 days. Good luck!
