### ISSUE TITLE
[Feature Request]: About Section Alignment 

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#814]
### How would you like to enhance the existing project.

Alignment of the content of the 'About' section from left-aligned to centered-aligned.

**Screenshot**

Current Design
![game-and-go (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/7fefa3e8-9b90-4e85-9825-3e165eec4fcf)

Expected Updated Design
![game-and-go (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/897f8f06-50e3-4d31-a938-1d71482d6a51)

### Describe breifly how would you implement the same.

Alignment of the content in center.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly assign me this issue.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this issue to you. Kindly complete within 4 days. Good luck!

**Comment by akankshabach** [comment]
I want to solve this issue please assign me .
Thank you!

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
The pull request related to this issue has been merged. Kindly close this issue.
