### ISSUE TITLE
[FEATURE] Word Scramble

### ISSUE THREAD

**Issue by pavitrachavda97** [ssitvit/Games-and-Go#815]
### Description

A word is given to player with random position of character and player have to guess that word and if player will guess it correctly then player score will increase and if player guess it wrong then there are only 8 guesses and then game will start again. Level will increases according to player points.
**Game points**
if user will guess correct then score will increase
else score will decrease
if score will be at some point according to level score requirement then level will increase and word length will also increase accordingly.
If player can not guess word in given attempt then game will end and start again

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/91004608/dd84ee91-6260-462f-beef-422429844751)

**Comment by panwar8279** [comment]
Hi @pavitrachavda97 , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!
