### ISSUE TITLE
[FEATURE] Whack-a-mole

### ISSUE THREAD

**Issue by pavitrachavda97** [ssitvit/Games-and-Go#816]
### Description

The game starts with a grid of holes, representing the mole's hiding spots.
Moles randomly pop up from their hiding spots at different intervals.
The player's goal is to quickly react and hit the moles back down into their holes using a virtual mallet.
Each successful hit earns the player points
Tech stack: HTML, CSS, JavaScript

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/91004608/4ac33228-9817-410e-b4ac-3dfe28b94f19)

**Comment by panwar8279** [comment]
Hi @pavitrachavda97 , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!
