### ISSUE TITLE
Adding ping pong game

### ISSUE THREAD

**Issue by anan262** [ssitvit/Games-and-Go#82]
I have already created one during my first year at college and would like to contibute here..I have pretty good ideas and want to implement the same here

**Comment by raj03kumar** [comment]
Can you elaborate on this with illustrations or any demo video

**Comment by anan262** [comment]
Hey!
So yeah,I plan to implement using python3 with sound possibly and this
works in such a way that each player has a racket which will be like the
image I have attached with a ball circulating as shown and the scores will
be displayed on the same screen. We can improve the UI of this too. This is
the basic prototype and the scores will increment as the other player loses
the ball and so on..we can add more features in the rule too such as
penalty game and tie breaker rounds.

[image: image.png]

**Comment by raj03kumar** [comment]
It's good that u implemented it in python. But this repo uses for ReactJS, so if u can implement the same using ReactJS then u r welcome with your work.

**Comment by anan262** [comment]
Yeah will try to do the same

**Comment by anan262** [comment]
I'm confident with React too as I have expereince in that one too

**Comment by raj03kumar** [comment]
Take your Time Ananya. Assigning this issue to you. Kindly try to wrap up everything in 10 days and go through readme and contributing.md as well. All the best with your work...!!!

**Comment by anan262** [comment]
Thank you!

**Comment by Swapnil-2503** [comment]
I want to work on making pong game, are you still doing it or shall i start working on it

**Comment by Swapnil-2503** [comment]
@raj03kumar can you assign this work to me.
@anan262 are you still working on it

**Comment by anan262** [comment]
Yeahh,I'm working on it

**Comment by Swapnil-2503** [comment]
ok 👍
