### ISSUE TITLE
[Feature Request]: Want to edit the about section in the website

### ISSUE THREAD

**Issue by anshulsoni4** [ssitvit/Games-and-Go#822]
### How would you like to enhance the existing project.

Enhancement - the current about looks very dull, i want to update it to more like a retro gaming perspective and align some ui elements

### Describe breifly how would you implement the same.

Solution_steps - i will be making the about heading bigger and giving some space to other elements

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @anshulsoni4 , I have assigned this task to you. Kindly complete within a week. Good luck!

**Comment by anshulsoni4** [comment]
> Hi @anshulsoni4 , I have assigned this task to you. Kindly complete within a week. Good luck!

thanks @panwar8279

**Comment by anshulsoni4** [comment]
pls check the PR @panwar8279

**Comment by anshulsoni4** [comment]
completed
