### ISSUE TITLE
[Feature Request]: 'Games' Description Alignment Correction

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#825]
### How would you like to enhance the existing project.

The alignment of the description of each game from left-aligned to the center-aligned in order to improve the overall design of the game section.

**Screenshot**

Current Alignment
![ip (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/73fa1355-820b-4e13-85d1-70af628b8ebd)

Expected Updated Alignment
![ip (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/95b94ba9-abf0-468f-858f-6e8a6fb89538)

### Describe breifly how would you implement the same.

Alignment of the description of each game from left-aligned to the center-aligned.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
@panwar8279 Kindly assign me this issue.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this issue to you. Kindly complete within 2 days. Good luck!

**Comment by akankshabach** [comment]
I want to solve this issue please assign me .
Thank you!

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
The pull request related to this issue has been merged. Kindly close this issue.
