### ISSUE TITLE
[Feature Request]: 'Snake Game' Styling

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#826]
### How would you like to enhance the existing project.

Working on the styling of the snake game to improve its design. 

**Screenshot**

Current Design
![ip](https://github.com/ssitvit/Games-and-Go/assets/115794049/c1aff04c-d26e-4493-b322-269672121f22)

Expected Updated Design
![ip (3)](https://github.com/ssitvit/Games-and-Go/assets/115794049/6ec49020-1542-409f-bb6c-3a16d23f5374)

### Describe breifly how would you implement the same.

Changing few styling properties of this game to improve the overall experience of the game.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
@panwar8279 Kindly assign me this issue

**Comment by iamRabia-N** [comment]
> @panwar8279 Kindly assign me this issue

@panwar8279

**Comment by panwar8279** [comment]
Hi @iamRabia-N , please make different design because it's not too good.

**Comment by iamRabia-N** [comment]
Sure


> Hi @iamRabia-N , please make different design because it's not too good.

Sure
