### ISSUE TITLE
[FEATURE] Memory Matching Game(Gssoc'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [ssitvit/Games-and-Go#834]
### Description

Memory Matching Game to sharpen your memory and match the card with other same card.

**Comment by Bharatpathak08** [comment]
@panwar8279  Can you plz assign this task to me and also mark the level and Gssoc'23 label?

**Comment by panwar8279** [comment]
Hi @Bharatpathak08 , I have assigned this task to you. Kindly complete within a week. Make sure you will your game in react because it's react based repository. Good luck!
