### ISSUE TITLE
[FEATURE] Fruit Ninja Game(Gssoc'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [ssitvit/Games-and-Go#836]
### Description

This project is a clone of 90s classic Fruit Ninja Game. Made with JAVASCRIPT, HTML, and CSS.

**Comment by panwar8279** [comment]
Hi @Bharatpathak08 , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!
