### ISSUE TITLE
[FEATURE] Multi Stack Games(Gssoc'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [ssitvit/Games-and-Go#837]
### Description

This repository contains games built using different tech stacks: web development with HTML, CSS, and Javascript, and terminal games in Python.

**Comment by Bharatpathak08** [comment]
@panwar8279  Can you plz assign this task to me and also mark the level and Gssoc'23 label?

**Comment by panwar8279** [comment]
Hi @Bharatpathak08 ,  I have assigned this task to you. Kindly complete your work within a week. Male sure you will make your game in react because it's react based repository. Good luck!
