### ISSUE TITLE
Social icons not visible in dark mode

### ISSUE THREAD

**Issue by sumitkr2000** [ssitvit/Games-and-Go#838]
### Description

Hey @panwar8279 The social icons present on the footer are not clearly visible in dark mode. Please assign me this issue. Thank you!

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/100675296/d38daa75-e3d8-4fae-b1cd-bc97f7d0b649)

**Comment by krutikajichkar** [comment]
@sumitkr2000 Sorry but this issue was assigned to me before you have raised it.

**Comment by sumitkr2000** [comment]
@krutikajichkar no problem, it's open source. Happy contributing 🥳
