### ISSUE TITLE
ARROW MOVING OUT OF CIRCLE 

### ISSUE THREAD

**Issue by sumitkr2000** [ssitvit/Games-and-Go#839]
### Description

Hey, @panwar8279 the arrow present in the scroll to top button is moving out of the circle and not looking good. Please assign me this issue. Thnk you!

### Screenshots

![Screenshot (895)](https://github.com/ssitvit/Games-and-Go/assets/100675296/bd0c5914-d5a7-4f26-9d95-f3aee082015d)

**Comment by panwar8279** [comment]
Hi @sumitkr2000 , I have assigned this issue to you. Kindly complete within 2 days. Good luck!
