### ISSUE TITLE
[FEATURE] Adding a Play button instead of the text play now text

### ISSUE THREAD

**Issue by Akanksha-202** [ssitvit/Games-and-Go#846]
### Description

Replace the existing 'Play Now' text with a clickable Play button to enhance user experience and improve accessibility.

### Screenshots

![a-play-button-retro-style-old-video-games-play-button-screen-button-137243114](https://github.com/ssitvit/Games-and-Go/assets/100708686/0a78b683-d97a-4ef1-9b51-28c2f29422aa)

### Additional information

Assign this issue to me under GSSoC'23 label :)

**Comment by panwar8279** [comment]
Hi @Akanksha-202 , I have assigned this issue to you. Kindly complete your work within 2 days. Good luck!
