### ISSUE TITLE
[Bug]: The search bar displays nothing when gibberish is entered

### ISSUE THREAD

**Issue by Akanksha-202** [ssitvit/Games-and-Go#847]
### Give a brief about the bug discovered✍

The search bar does not show any results when gibberish or non-matching prompts are entered, resulting in an empty display.

![Screenshot 2023-07-21 110806](https://github.com/ssitvit/Games-and-Go/assets/100708686/1dd53aca-c437-45dd-ab59-496b5c5dfdad)

### What is the expected behavior?

When gibberish or non-matching prompts are entered in the search bar, random games should be displayed to provide users with a fun and engaging experience.

### Give a brief description to get the expect behaviour.

Update the search functionality to generate random games when the user enters gibberish or non-matching prompts to ensure an enjoyable user experience.

Willing to work over this issue.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Akanksha-202 , i have assigned this issue to you. Kindly complete within 2 days. Good luck!
