### ISSUE TITLE
[FEATURE Want to add hover effect on the icons and social icons

### ISSUE THREAD

**Issue by HimanshuNarware** [ssitvit/Games-and-Go#848]
### Description

I Want to add hover effect on the icons and social icons

### Screenshots

![107](https://github.com/ssitvit/Games-and-Go/assets/83147410/a59ec16b-c7b1-49a7-b80d-a0f1dcd5733b)

**Comment by panwar8279** [comment]
Hi @HimanshuNarware , I have assigned this issue to you. Kindly complete within 2 days. Good luck!
