### ISSUE TITLE
Tetris Game

### ISSUE THREAD

**Issue by meihu-ganesh** [ssitvit/Games-and-Go#85]
I want to add the legendry old game Tetris, where the canvas is filled by joining the shapes that come from up, and by filling a row completely we will get the points and that row will be eliminated, the game continues till the whole canvas get filled, and the highest score is recorded.
![image](https://github.com/ssitvit/Games-and-Go/assets/100460284/63df87e4-bfd1-4784-af88-855f77cfd39e)

**Comment by meihu-ganesh** [comment]
I want to work on this issue of adding this new game, please assign this to me

**Comment by raj03kumar** [comment]
Mention the tech stacks used so that we can proceed further with you.

**Comment by meihu-ganesh** [comment]
I had seen someone else had been assigned this game, no problem, can you please assign me the brick breaking game where I had mentioned the tech stacks I am going to use i.e. React JS and HTML Canvas. You can close this issue. Thank you
