### ISSUE TITLE
[FEATURE]Falling Ball Game

### ISSUE THREAD

**Issue by khushimarothi** [ssitvit/Games-and-Go#850]
### Description

I want to add a ball game in the list.
a ball falls down continuously user can mover it left or right, so that it can cross the hurdle row.

please assign under gssoc

**Comment by khushimarothi** [comment]
@panwar8279 @Shreyaar12 please assign

**Comment by panwar8279** [comment]
Hi @khushimarothi ,  I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!

**Comment by khushimarothi** [comment]
> Hi @khushimarothi , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!

Please assign appropriate label. I have to create the game from scratch
