### ISSUE TITLE
[Feature Request]: Shoot the Target!

### ISSUE THREAD

**Issue by uzmaansari23** [ssitvit/Games-and-Go#852]
### How would you like to enhance the existing project.

Enhancement
I will add the simple and interesting game based on HTML and CSS .
Player has to start the game by clicking on insert coin, aim and shoot the target before you miss it!!!

### Describe breifly how would you implement the same.

Uploading shoot the target.mp4…

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @uzmaansari23 , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!
