### ISSUE TITLE
[FEATURE]: MAKE SEARCH BAR ACCESSIBLE 🔍

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#860]
### Description

- This feature is about making the Search bar Accessible using `label`.
- We need to properly link the `label` to the `input` element with attributes like `name`, `id` & `for` to make it accessible to screen readers like devices.
- Additionally we can add screen reader only styles to the `label`, So that the `label` will be visually hidden but it can be visible to screen readers.
- This will results in making a perfect accessible search bar which can used by every users around the world!

### Screenshots

![Screenshot 2023-07-23 at 08-28-52 Games-And-Go](https://github.com/ssitvit/Games-and-Go/assets/92252895/591ac3c2-1077-482b-8d02-e0a5d8c8a2a3)

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , i have assigned this task to you. Kindly. Complete your work within 2 days. Good luck!
