### ISSUE TITLE
Want to contribute new game 

### ISSUE THREAD

**Issue by NomikaGajula** [ssitvit/Games-and-Go#861]
### Description

I want to contribute a new game that i worked on it's 2048 game where the users will add the block of the same number to double it and it goes on. it's a cooler game to make math lovers as well as other get attracted to this

**Comment by NomikaGajula** [comment]
please let me add this game @panwar8279

**Comment by panwar8279** [comment]
Hi @NomikaGajula , I have assigned this task to you. Kindly complete your work within a week. Make sure your will make your game in react because it's react based repository. Good luck!

**Comment by NomikaGajula** [comment]
Hi thank you for assigning me this
i added the game
i guess the label of issue is level 2 right as i have observed that if
someone wants to add new game then it is given label 2
