### ISSUE TITLE
[Feature Request]: make the corners rounded, the forms and not uniform

### ISSUE THREAD

**Issue by anshulsoni4** [ssitvit/Games-and-Go#862]
### How would you like to enhance the existing project.

Enhancement
will make the corners round so that it looks uniform and appealing

### Describe breifly how would you implement the same.

Solution_steps
as mentioned above we will make the corners rounded

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by anshulsoni4** [comment]
@panwar8279 can you assign me this

**Comment by panwar8279** [comment]
Hi @anshulsoni4 , I have assigned this task to you. Kindly complete within 3 days. Good luck!

**Comment by anshulsoni4** [comment]
> Hi @anshulsoni4 , I have assigned this task to you. Kindly complete within 3 days. Good luck!

sure, thanks

**Comment by anshulsoni4** [comment]
done
