### ISSUE TITLE
[FEATURE]: CODEQL WORKFLOW ✨

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#864]
### Description

- The repository contains code for React, But it does not have a workflow for scanning the code.
- I want to add the codeql workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code.
- It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions.

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this task to you. Kindly complete your work within a week. Good luck!
