### ISSUE TITLE
[Feature Request]: change the navigation button a and b 

### ISSUE THREAD

**Issue by avishka45** [ssitvit/Games-and-Go#866]
### How would you like to enhance the existing project.

the navigation bar is too big, i just want it little small 

### Describe breifly how would you implement the same.

i will make nav button smaller 

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @avishka45 , I have assigned this task to you. Kindly complete your work within a week. Good luck!
