### ISSUE TITLE
Want To Add My Game Called : Catch Me If You Can 

### ISSUE THREAD

**Issue by sujitmemane** [ssitvit/Games-and-Go#87]
Hello, Maintainer! 👋🏼

I am [Sujit Memane](https://thesujitmemane.vercel.app/), a front-end React developer with expertise in creating visually stunning user interfaces. I have a strong portfolio that showcases my past work, highlighting my skills and abilities in designing attractive UIs.

I want to add Catch Me If You Can add the game to your game hub 

Looking forward to the opportunity!

Portfolio Link : https://thesujitmemane.vercel.app/
Catch Me If You Can Game : [https://catch-me-theta.vercel.app](https://t.co/CuwNduqjpB)

**Comment by raj03kumar** [comment]
Explain the game rules...

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete the task within a week and go through readme and contributing.md for successful merge. All the best to your work Sujit... !!!

**Comment by sujitmemane** [comment]
Thank You very much
