### ISSUE TITLE
[Bug]: Margin, Padding, visibility of Text related bugs/issues in Some Games Main Dashboards

### ISSUE THREAD

**Issue by NarendraKoya999** [ssitvit/Games-and-Go#879]
### Give a brief about the bug discovered✍

Description:
- `Margin, Padding, visibility of Text related bugs/issues in Some Games Main Dashboards`

### What is the expected behavior?

Description:
- Proper maintainance  needs for Game Main Dashboards like Design-Padding, Margin, Visuality Font Design.
- This is missed in Some Games Main Dashboards .
- I want to resolve that bugs/issues to Improve UI for Game Dashboards

### Give a brief description to get the expect behaviour.

Description:
- In every UI of Main Web Pages, Padding, Font, Margin related things are Crucial  . That Means Alignment of Items are properly Positioned and Designed OR Not.
- I want to Rectify that Problems.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by Jyoticharan** [comment]
please assign me this issue

**Comment by panwar8279** [comment]
Hi @NarendraKoya999 , I have assigned this task to you. Kindly complete your work within a week. Good luck!
