### ISSUE TITLE
Add Snake and ladder game.

### ISSUE THREAD

**Issue by Srija-Burugula** [ssitvit/Games-and-Go#88]
Snake and Ladder is a very interesting game that has the potential to attract many users.I would like to add that game. Please assign this project to me under GSSoC'23.

**Comment by raj03kumar** [comment]
Assigned this task to you. Kindly complete it within 10 days and go through the readme and contributing.md for successful merge.  All the best to your work Srija... !!!

**Comment by rahultomarr** [comment]
I'm here to contribute to the GSSOC'23.
Please assign me to do that.

**Comment by Srija-Burugula** [comment]
Thank you @raj03kumar for assigning this task to me. I'll start working on it immediately.

**Comment by Nishant5789** [comment]
i want to add socket.io module so user can share the message or emoji  as well as playing.
