### ISSUE TITLE
[FEATURE] Adding the 90's Super Mario Mini Game.

### ISSUE THREAD

**Issue by Sch476** [ssitvit/Games-and-Go#893]
### Description

I would like to add the classic 90's Super Mario MIni Game to the Game List.

**Comment by panwar8279** [comment]
Hi @Sch476 , i have assigned this task to you. Kindly complete your work within a week. Male sure you will make your game in react because it's react based repository. Good luck!

**Comment by Sch476** [comment]
@panwar8279 can you suggest me someone who is really good in react. I really needed a bit help. The game is made in html,css and js . Have to convert it to React.
