### ISSUE TITLE
 Alignment Issue: Music Button and Dark Mode Toggle Button Misalignment

### ISSUE THREAD

**Issue by rishiofficial** [ssitvit/Games-and-Go#896]
### Description

 Currently, there is an alignment issue where the music button and the dark mode toggle button are not properly aligned with each other on the user interface. The purpose of this issue is to fix the misalignment and ensure that both buttons are visually aligned for a more consistent and polished user experience.

I am in GSSoC'23.

**Comment by panwar8279** [comment]
Hi @rishiofficial , I have assigned this issue to you. Kindly complete your work within a week. Good luck!
