### ISSUE TITLE
[FEATURE]:DICE SHOWDOWN GAME

### ISSUE THREAD

**Issue by rishiofficial** [ssitvit/Games-and-Go#897]
### Description

This Game is an exciting multiplayer game where two players compete to roll the highest number on their dice. Experience the thrill of luck and strategy as you aim to outscore your opponent in this engaging game suitable for players of all ages.

I am in GSSoC'23.

**Comment by panwar8279** [comment]
Hi @rishiofficial , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!
