### ISSUE TITLE
#Create a smash the  balloon game

### ISSUE THREAD

**Issue by vibgyor786** [ssitvit/Games-and-Go#9]
>create a game where user can click on the balloon to increase the points .
>balloon should emerge at some random position each time after 1 second
>you are free to set the time limit .

**Comment by shubham-shinde-442** [comment]
As Contributor in GSSoC"23 , I Would like to Work on This game . Can you Assign me this issue ?

**Comment by priyam212001** [comment]
hey, @vibgyor786  can you assign me this issue? I have experience in reactjs.

**Comment by Shreyaar12** [comment]
@shubham-shinde-442 kindly complete within 10 days

**Comment by shubham-shinde-442** [comment]
Sure

**Comment by Deepanshu0703** [comment]
is it completed or still available

**Comment by AdhiRaj08** [comment]
Please assign me this issue under GSSOC'23
