### ISSUE TITLE
[FEATURE] Homepage Background Styling

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#900]
### Description

Changing the background of the website from white to a dark shade to make its design more attractive as many components are in such a shade that are perfect to go with the dark background.

### Screenshots

_Current Design_

![ip (3)](https://github.com/ssitvit/Games-and-Go/assets/115794049/7c8f8841-ffb7-4552-a7b4-07df27f8cff5)

_Expected Updated Design_

![ip (8)](https://github.com/ssitvit/Games-and-Go/assets/115794049/3484ef6a-50f0-4271-a24a-84faef527a82)

![ip (4)](https://github.com/ssitvit/Games-and-Go/assets/115794049/2bd77e3c-6ebf-4c29-83be-832b92a24b8b)

![ip (7)](https://github.com/ssitvit/Games-and-Go/assets/115794049/74d2ae12-cb83-45b1-adad-b4f4ddca0e26)

### Additional information

None

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly assign me this issue.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this task to you. Kindly complete within 4 days. Good luck!

**Comment by hansupadhyay007** [comment]
Hi @panwar8279  
Kindly assign me this issue ,I will complete it as soon as possible.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
The pull request related to this issue has been merged. Kindly close this issue.
