### ISSUE TITLE
[FEATURE] <description> i have made a new game in which we roll and freeze the selcted dice to make all dice same in minimum time and to beat our best score

### ISSUE THREAD

**Issue by abansal15** [ssitvit/Games-and-Go#902]
### Description

a new game
i have made a new game in which we roll and freeze the selcted dice to make all dice same in minimum time and to beat our best score

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/120590200/f8b4db1f-7045-4cd8-8a3f-52e756b8e6f1)

### Additional information

i has sound also in background

**Comment by panwar8279** [comment]
Hi @abansal15, I have assigned this task to you. Kindly complete your work within a week. Make sure you will make this game in react because it's react project repository. Good luck for you work!

**Comment by abansal15** [comment]
@panwar8279 raised the pr
