### ISSUE TITLE
[FEATURE] <description>rock paper scissor game

### ISSUE THREAD

**Issue by abansal15** [ssitvit/Games-and-Go#903]
### Description

![image](https://github.com/ssitvit/Games-and-Go/assets/120590200/7ed5c0ff-73e8-432e-979c-8c930e0deb41)

**Comment by abansal15** [comment]
please assign it to me

**Comment by panwar8279** [comment]
Hi @abansal15 , I have assigned this task to you. Kindly complete your work within a week. Make sure you will make your game in react because it's react based repository. Good luck!
