### ISSUE TITLE
[FEATURE] <description>TIC TAC TOE GAME made with react

### ISSUE THREAD

**Issue by abansal15** [ssitvit/Games-and-Go#907]
### Description

a tic tac toe game with react

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/120590200/a15a9b8d-4df0-4627-9267-eb7c45ca5fba)

**Comment by abansal15** [comment]
@panwar8279 please assign it to me

**Comment by panwar8279** [comment]
Hi @abansal15 ,I have assigned this task to you. Kindly complete your work within 10 days. Good luck!
