### ISSUE TITLE
[FEATURE] <description>invaders game

### ISSUE THREAD

**Issue by abansal15** [ssitvit/Games-and-Go#908]
### Description

![image](https://github.com/ssitvit/Games-and-Go/assets/120590200/210899d7-88c2-400b-a7a7-ed4002198461)

**Comment by abansal15** [comment]
@panwar8279 please assign it to me

**Comment by panwar8279** [comment]
Hi @abansal15 , I have assigned this task to you. Kindly complete your work within 10 days. Make sure you will make your game in react. Good luck!
