### ISSUE TITLE
Add Wordle game

### ISSUE THREAD

**Issue by pshantanu771** [ssitvit/Games-and-Go#91]
I'd like add a simple yet engaging Wordle Game using where players will have to guess a randomly generated 5 letter word within limited number of attempts. I'll also make the UI responsive.

Features:

- Responsive UI
- Showing which letter are correct and which are wrong if user guesses it wrong
- Also showing if the letter is at correct position or not
- Option to opt for an hint in exchange with 1 reduced attempt
- Showing the correct word if all the attempts are exhausted

Please assign this issue to me under GSSOC'23.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete it within a week and go through the readme and contributing.md for successful merge. All the best to your work Shantanu... !!!

**Comment by Harshvardhan-Dubey-Github** [comment]
Can you please assign me this issue
