### ISSUE TITLE
[FEATURE] <description>BlackJack game in react

### ISSUE THREAD

**Issue by abansal15** [ssitvit/Games-and-Go#910]
### Description

place the bet and win

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/120590200/f670a868-c6ab-477b-8db2-cbb069a4fbc5)

**Comment by abansal15** [comment]
@panwar8279 please assign it to me

**Comment by panwar8279** [comment]
Hi @abansal15 , I have assigned this task to you. Kindly complete your work within 10 days. Make sure you will make your game in react. Good luck!

**Comment by abansal15** [comment]
@panwar8279 raised the pr can you please review it
