### ISSUE TITLE
[Feature Request]: Trivia Game Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#915]
### How would you like to enhance the existing project.

By working on the styling of this game, I can improve its design

### Describe breifly how would you implement the same.

_Current Design_

![ip (6)](https://github.com/ssitvit/Games-and-Go/assets/115794049/39ccda71-01eb-4d49-a51e-8858cf006d71)

_Expected Updated Design_

![ip (5)](https://github.com/ssitvit/Games-and-Go/assets/115794049/516f6d05-69c0-42e4-ab3b-2251e694c95a)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly assign me this issue to improve this game design.

**Comment by hansupadhyay007** [comment]
Hi @panwar8279 
Kindly assign me this issue to improve the design.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this task to you. Kindly complete your work within 5 days. Good luck!

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
The pull request related to this issue has been merged. Kindly close this issue.
