### ISSUE TITLE
[Feature]: Typo Typing Tester Game Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#916]
### How would you like to enhance the existing project.

Working on the styling of this game to improve its design.

### Describe breifly how would you implement the same.

**Screenshots**

_Current Design_

![ip (6)](https://github.com/ssitvit/Games-and-Go/assets/115794049/6314d441-3938-4e6f-aab4-b2b22c034c97)

_Expected Updated Design_

![ip (5)](https://github.com/ssitvit/Games-and-Go/assets/115794049/8b80845c-538b-4e2b-b5cc-92b86e456393)

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly assign me this issue.

**Comment by panwar8279** [comment]
Hi @iamRabia-N ,I have assigned this task to you. Kindly complete your work within 4 days. Good luck!

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
The pull request related to this issue has been merged. Kindly close this issue.
