### ISSUE TITLE
[Feature]:  'Game On' Section Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#922]
### How would you like to enhance the existing project.

Working on the 'Game On' Heading and search area styling to improve their design.

### Describe breifly how would you implement the same.

Adding and adjusting few styling properties to improve their design.

**Screenshot**

_Current Design_

![ip (16)](https://github.com/ssitvit/Games-and-Go/assets/115794049/63bb9393-ec06-4a8b-baa9-269f5f77e53f)

_Expected Updated Design_

![ip (17)](https://github.com/ssitvit/Games-and-Go/assets/115794049/dbd5ed48-4f33-468b-9d4e-e61d6882810a)

However, if you want different color of "Game On" heading, do let me know. I would love to consider your opinion.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly assign me this issue.

**Comment by iamRabia-N** [comment]
> Hi @panwar8279 Kindly assign me this issue.

@panwar8279

**Comment by iamRabia-N** [comment]
Hi @panwar8279
Kindly assign me this issue.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this issue to you. Kindly complete this within 2 days. Good luck!
