### ISSUE TITLE
[Documentation Addition]: Adding proper links in Code of Conduct section

### ISSUE THREAD

**Issue by Viveksati5143** [ssitvit/Games-and-Go#923]
### Also, describe the documentation you want to add. ✍️

Adding proper links like in "Checkout Contributing.md" & more in Code of Conduct section of Readme.md
<img width="960" alt="image" src="https://github.com/ssitvit/Games-and-Go/assets/100852245/7f73d32c-1a28-4fe3-a8cd-8ca67cc8e7bb">

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Viveksati5143 , I have assigned this task to you. Kindly complete within 2 days. Good luck!

**Comment by Viveksati5143** [comment]
Completed @panwar8279 !!
