### ISSUE TITLE
Multiplayer Chess Game

### ISSUE THREAD

**Issue by Iron-Thunder** [ssitvit/Games-and-Go#93]
I want to add a multiplayer chess game. 
![image](https://github.com/ssitvit/Games-and-Go/assets/103611908/b969e6cd-4896-4328-998c-95699e5eba99)

**Comment by Iron-Thunder** [comment]
I want to work in this issue of making this game. Please assign me this issue

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly get it done within a week and go through the readme and contributing.md for successful merge. All the best to your work...

**Comment by sumitkr2000** [comment]
hey @raj03kumar if she is not working on it can I work on this issue? Please assign me this issue. I can work on it quickly.
