### ISSUE TITLE
Drag and Drop Game Design 

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#930]
### Description

The design of drag and drop game is unresponsive for the users. Such design may affect the users in their gaming experience.

### Screenshots

_Current Design_

![ip (12)](https://github.com/ssitvit/Games-and-Go/assets/115794049/7b92942b-6428-43ea-b9f1-f3f1510cb8cc)

_Expected Updated Design_

Small screen
![ip (11)](https://github.com/ssitvit/Games-and-Go/assets/115794049/f94af25a-e8a2-40ab-a00b-55a35dc9a3cc)

Large screen
![ip (10)](https://github.com/ssitvit/Games-and-Go/assets/115794049/008fc09d-99b9-4808-b829-c0f654a2df97)

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly assign me this issue.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this task to you. Kindly complete within 2 days. Good luck!

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
The pull request related to this issue has been merged. Kindly close this issue.
