### ISSUE TITLE
[Feature Request]: Footer is so Fade

### ISSUE THREAD

**Issue by Priyaaa1** [ssitvit/Games-and-Go#935]
### How would you like to enhance the existing project.

The Footer is fade and not readable, icons are barely visible.

![Screenshot (178)](https://github.com/ssitvit/Games-and-Go/assets/105431748/d1ca4d3b-1029-42d0-b60c-31e054830519)

### Describe breifly how would you implement the same.

I would like to work on this issue and make it nice.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Priyaaa1 , I have assigned this issue to you. Kindly complete within 2 days. Good luck!

**Comment by Shahidkhatrii** [comment]
if it's not done then can I work on this ?
