### ISSUE TITLE
[DOCS] Update Readme

### ISSUE THREAD

**Issue by Parul1606** [ssitvit/Games-and-Go#938]
### Description

Current State: -
The Contributing section of the README file requires extra documentation. Some commands that should be applied while contributing to the project are missing.

Desired State: -
I know some small basic steps don't require to be explained. But, I would like to add those extra commands like a repository should be pulled by creating a remote repository(for reference), the first step like creating a folder at your desired location, etc. I have divided the whole process into 17-18 simple steps which will be easy to understand by the contributors. I won't be deleting any part will just modify it in a better way. I have desired image of how it will look after updating the README.
The image attached is just an outlook of how README will be displayed:

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/80768852/e5403626-6164-49fe-882d-1a1b1d311cc4)

**Comment by Parul1606** [comment]
Please assign me this issue I would like to work under gssoc @panwar8279

**Comment by panwar8279** [comment]
Hi @Parul1606 , I have assigned this task to you. Kindly complete within 2 days. Good luck!
