### ISSUE TITLE
[Feature Request]: Adding a contributors List to the website

### ISSUE THREAD

**Issue by Sch476** [ssitvit/Games-and-Go#939]
### How would you like to enhance the existing project.

By adding a contributors list to the website, we can showcase the contributors who worked in this project.

### Describe breifly how would you implement the same.

I would use Github Api to fetch the contributors and use that data in the website and style it using css.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @Sch476 , I have assigned this issue to you. Kindly complete within 2 days. Good luck!

**Comment by Sch476** [comment]
Hey @panwar8279 today only I will make the webpage . But just had a question regarding the level?
