### ISSUE TITLE
Improvements in Tic Tac Toe game

### ISSUE THREAD

**Issue by YashMishra0101** [ssitvit/Games-and-Go#94]
I want to work on following features under GSSoC-2023:
1.Adding background audio when someone clicks the boxes.
2.Playing audio when someone wins.
3.Playing audio when the game is a tie.
4.Improving the user interface (UI)

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete your work within a week and go through the readme and contributing.md for successful merge. All the best to your work Yash... !!!

**Comment by YashMishra0101** [comment]
I am attempting to contribute to this codebase, but I'm facing challenges since I'm unfamiliar with React. I'm eager to learn and improve my understanding of React so that I can actively contribute in the future.

**Comment by raj03kumar** [comment]
Mentors are assigned to this project. They will be taking your issues in few days.

**Comment by raj03kumar** [comment]
> I am attempting to contribute to this codebase, but I'm facing challenges since I'm unfamiliar with React. I'm eager to learn and improve my understanding of React so that I can actively contribute in the future.

Meanwhile you can read contributing.md and get some insights.
