### ISSUE TITLE
Fix Image location of the existing game

### ISSUE THREAD

**Issue by Parul1606** [ssitvit/Games-and-Go#940]
### Description

I would like to fix the image location of the 30th game(Magic memory game)
none of the images are visible on the website
I have added screenshots.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/80768852/5f6907e7-cd73-4a3a-a32a-2763c3656dea)

![image](https://github.com/ssitvit/Games-and-Go/assets/80768852/06aa40a3-43b8-44df-bb87-6d9ae708bcb2)

**Comment by panwar8279** [comment]
Hi @Parul1606 , I have assigned this issue to you. Kindly complete this within 2 days. Good luck!

**Comment by shweta-kush** [comment]
I would like to work on this issue. kindly assign it to me.

**Comment by DASIREDDYCHAITANYA** [comment]
assign me

**Comment by panwar8279** [comment]
Hi @DASIREDDYCHAITANYA , I have assigned this issue to you. Kindly complete this within a week. Good luck!
