### ISSUE TITLE
[New Game]: Connect four multiplayer game 

### ISSUE THREAD

**Issue by Swapnil-2503** [ssitvit/Games-and-Go#941]
### Description

- The game starts with the "red" player.
-  Click on any of the seven columns at the top of the game board to drop a red piece into that column.
-  The red piece will fall to the lowest available row in the selected column. The "red" player's turn is now over.
- The game will automatically switch to the "yellow" player's turn.
- Click on any of the remaining columns to drop a yellow piece into that column.
-  The yellow piece will fall to the lowest available row in the selected column. The "yellow" player's turn is now over.
-  Players take turns dropping their respective colored pieces until one player successfully connects four pieces in a row, column, or diagonal.
-  If a player connects four pieces, an alert will pop up to declare that player as the winner.
- If neither player connects four pieces and the board is full, the game will end in a draw.
- To play again, simply refresh the web page to reset the game board and start a new game.

![Connect-Four](https://github.com/ssitvit/Games-and-Go/assets/89910173/59f509de-268a-4b41-a6ea-552f2edc710f)

**Comment by Swapnil-2503** [comment]
@panwar8279 Can you review this pr 👍

**Comment by panwar8279** [comment]
Hi @Swapnil-2503 , I have assigned this task to you. Make sure you will make your game in react. Kindly complete your work within a week. Good luck!
