### ISSUE TITLE
[Documentation Addition]: Adding links of official documentation

### ISSUE THREAD

**Issue by DivyanshiNarang** [ssitvit/Games-and-Go#942]
### Also, describe the documentation you want to add. ✍️

Official documentation links are not added to these buttons. We can add official documentation links of the respective technologies used so that it will be helpful for new contributors.

<img width="405" alt="image" src="https://github.com/ssitvit/Games-and-Go/assets/74779601/b2fb481c-89a1-49e9-8038-9a176e0616a8">

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @DivyanshiNarang , I have assigned this task to you. Kindly complete your work within 2 day. Good luck!
