### ISSUE TITLE
[Bug]: Footer Visibility and Text Readability

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#943]
### Give a brief about the bug discovered✍

The color of footer text is aligning with the theme of the website thus causing negative impact on the visibility and readability of the text of the footer.

### What is the expected behavior?

Clear footer items and content

### Give a brief description to get the expect behaviour.

By changing the color of the footer items, we can remove this bug.

**Screenshots**

_Current Design_

![i (4)](https://github.com/ssitvit/Games-and-Go/assets/115794049/3b1534d9-cbb7-4b1f-ac26-0083f5ef61db)

_Expected Updated Design_

![i (3)](https://github.com/ssitvit/Games-and-Go/assets/115794049/05e47141-e79c-4cc1-8b9d-57e7d380904a)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
I want to work on this issue. Kindly assign me this issue.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this issue to you. Kindly complete your work within 3 days. Good luck!
