### ISSUE TITLE
[Bug]: 'Arkanoid' Game Errors

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#947]
### Give a brief about the bug discovered✍

Many factors in the design of this game are creating bad experience for user. The most prominent is that the ball hiter and the heading are colliding thus text of heading is not visible. Besides that, color and other designing of the game can also be improved by working on styling.

### What is the expected behavior?

Clear design of the game.

### Give a brief description to get the expect behaviour.

By working on the styling of the game, I can remove these bugs and improve its design.

**Screenshots**

_Current Design_

![ip (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/53cd7cf7-2515-4979-b142-05e74e4950b6)

_Expected Updated Design_

![ip (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/e356c887-24b5-4753-a96c-a8f8c7c51564)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
@panwar8279

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this issue to you. Kindly complete within 2 days. Good luck!
