### ISSUE TITLE
[Bug]: 'MineSweeper' Game Wrong Color Selection and Difficult Text Readability

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#948]
### Give a brief about the bug discovered✍

The color selected for the heading and color theme of the website is creating difficulty in reading the text of the game.

### What is the expected behavior?

Clear design of the game and prominent text.

### Give a brief description to get the expect behaviour.

By working on the styling of this game, I can correct these bugs and improve this game's design.

**Output Screenshot**

_Current Design_

![ip (3)](https://github.com/ssitvit/Games-and-Go/assets/115794049/648a6569-3417-40ce-a9a9-459253cce48f)

_Expected Updated Design_

![ip (4)](https://github.com/ssitvit/Games-and-Go/assets/115794049/0be3fe9b-041a-4e3d-b64d-b1df8ff6f72c)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279
Kindly assign me this issue.

**Comment by iamRabia-N** [comment]
@panwar8279

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this issue to you. Kindly complete within 2 days. Good luck!
