### ISSUE TITLE
Add 15 puzzle game

### ISSUE THREAD

**Issue by c0mpli** [ssitvit/Games-and-Go#95]
![image](https://github.com/ssitvit/Games-and-Go/assets/72159678/574ead6e-4419-49e1-a7f9-4e48a13fe9a5)

# Description
A puzzle consisting of 15 squares, numbered 1 through 15, which can be slid horizontally or vertically within a four-by-four grid that has one empty space among its 16 locations.

# How to play
Move the empty block horizontally or vertically using arrow keys or by clicking.
The game ends when all the numbers from 1 to 15 are in correct order.

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly complete your work within a week and go through the readme and contributing.md for successful merge. All the best to your work Jash... !!!
