### ISSUE TITLE
[Bug]: Conflict Between Dark/Light mode Button and Music Button on Left Side when Hovering Action Done

### ISSUE THREAD

**Issue by NarendraKoya999** [ssitvit/Games-and-Go#954]
### Description:
- Go To https://games.ieeessitvit.tech/
- **Put Cursor on Music Icon Button.**
- **See Error on Whenever Hovering Action done on Music Button, then That Tooltip Text goes to behind the Dark/Light Theme Mode Button.**

### Screenshots

![gamesandgo-2](https://github.com/ssitvit/Games-and-Go/assets/84512164/7fd57134-9f3f-4615-815b-dd2117c09f78)

**Comment by NarendraKoya999** [comment]
Hi @panwar8279 . Please Review on this Issue as soon as Possible. Thank You !

**Comment by panwar8279** [comment]
Hi @NarendraKoya999 , I have assigned this issue to you. Kindly complete this within 2 days. Good luck!

**Comment by NarendraKoya999** [comment]
Hi @panwar8279 . At the Time Of Assigned this Issue To me . After that, Checking on Our Website, Even No Tooltip Appears on Respective Music Icon. So, I want to add that Tooltip on Both Night/Dark Theme and Music Icon. Otherwise Please Close this Issue. Whole Decision is Your Side. Thank You !

**Comment by NarendraKoya999** [comment]
> Hi @panwar8279 . At the Time Of Assigned this Issue To me . After that, Checking on Our Website, Even No Tooltip Appears on Respective Music Icon. So, I want to add that Tooltip on Both Night/Dark Theme and Music Icon. Otherwise Please Close this Issue. Whole Decision is Your Side. Thank You !

@panwar8279 . Please Look at My Quote.
