### ISSUE TITLE
[FEATURE] <description> new puzzle game

### ISSUE THREAD

**Issue by abansal15** [ssitvit/Games-and-Go#956]
### Description

i want to add this amazing puzzle game

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/120590200/6eb98116-106a-44c0-91da-191ef6ea500f)

**Comment by abansal15** [comment]
@panwar8279 please assign this to me

**Comment by panwar8279** [comment]
Hi @abansal15 ,  I have assigned this issue to you. Kindly complete this issue within 10 August. Make sure this game is in react. Good luck!

**Comment by abansal15** [comment]
@panwar8279 please review it i have raised the pr

**Comment by shreyaspathak11** [comment]
Hi @panwar8279 assign me please
