### ISSUE TITLE
[Feature Request]: Updating the previous PR #918

### ISSUE THREAD

**Issue by jaibhedia** [ssitvit/Games-and-Go#957]
### How would you like to enhance the existing project.

Added working flappy bird game and removed glitchy snakes game

### Describe breifly how would you implement the same.

I have written the fresh code to fix my issue.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by jaibhedia** [comment]
@Shreyaar12 Please assign me this update.

**Comment by jaibhedia** [comment]
and kindly mark it as GSSoC23

**Comment by panwar8279** [comment]
Hi @jaibhedia , I have assigned this issue to you. Kindly complete this issue within 10 August. Make sure this game is in react. Good luck!
