### ISSUE TITLE
[FEATURE] highway car race

### ISSUE THREAD

**Issue by SimranLahrani842** [ssitvit/Games-and-Go#960]
### Description

Divided into levels like hard and medium and easy..
Car race having red car have to compete with other cars and win the race.

**Comment by panwar8279** [comment]
Hi @SimranLahrani842 , I have assigned this issue to you. Kindly complete within 10 august. Good luck.

**Comment by SimranLahrani842** [comment]
> Hi @SimranLahrani842 , I have assigned this issue to you. Kindly complete within 10 august. Good luck.

Yes mam
Thankyou for immediate response .👍❤️
