### ISSUE TITLE
[FEATURE] bird shooter game 

### ISSUE THREAD

**Issue by SimranLahrani842** [ssitvit/Games-and-Go#961]
### Description

Shoot the birds and a notification will appear that bird is killed.
The score will increase as soon as the bird is killed.
Kill as many birds as possible within a time limit.

**Comment by panwar8279** [comment]
Hi @SimranLahrani842 , I have assigned this issue to you. Kindly complete this issue within 10 August. Make sure this game is in react. Good luck!
