### ISSUE TITLE
BUG: PLAY ICON VISIBILITY 🙅🏻❌ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#962]
### Description

- The current state of Play icon is on dark color, so the icon is not properly visible to the user.
- We need to fix this bug otherwise the user could not able to see the icon properly.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/0b68f5a3-423f-4849-8bc9-cb2d3a731554)

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this issue to you. Kindly complete within 2 days. Good luck!
