### ISSUE TITLE
[Feature Request]:  Adding Commit Lint and Husky for Code Quality Improvement ✨

### ISSUE THREAD

**Issue by Nishitbaria** [ssitvit/Games-and-Go#970]
### How would you like to enhance the existing project.

Enhancement

As a developer, I would like to enhance our project's code quality by adding commit linting and Husky hooks. This will help us enforce consistent commit message formats and run pre-commit checks, ensuring that our codebase stays clean and maintainable.

### Describe breifly how would you implement the same.

Solution_steps

**Implementation Steps:**

To implement commit linting and Husky in our project, follow these steps:

**Step 1: Install Commit Linting Dependencies**
- Open a terminal or command prompt and navigate to your project's root directory.
- Run the following command to install the necessary dependencies:

```
npm install --save-dev @commitlint/{config-conventional,cli}
```

**Step 2: Configure Commit Lint**
- Create a file named `commitlint.config.js` in the root directory of your project.
- Define your preferred commit message format rules using the conventional commits format or any custom format that suits your project. For example:

```javascript
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // Add any additional rules or customize the existing ones as per your project's requirements
  },
};
```

**Step 3: Integrate Husky**
- Run the following command to install Husky as a dev dependency:

```
npm install --save-dev husky
```

**Step 4: Create Pre-Commit Hook**
- Open your project's `package.json` file.
- Add the following configuration to set up Husky to run the pre-commit hook:

```json
"husky": {
  "hooks": {
    "pre-commit": "npm run lint:pre-commit && npm run test" // Add any other pre-commit checks you want to run here
  }
}
```

**Step 5: Define Pre-Commit Checks**
- In your `package.json`, add scripts to define the pre-commit checks you want to run. For example:

```json
"scripts": {
  "lint:pre-commit": "commitlint --from=HEAD~1",
  "test": "npm run lint && npm run unit-test" // Add any other test-related scripts here
}
```

**Step 6: Documentation**
- Update the project's README or documentation to include information about the new commit linting and Husky integration.
- Explain the commit message format rules and provide examples of valid commit messages.

**Step 7: Test and Verify**
- Before pushing your changes to the main development branch, create a feature branch and test the new commit linting and Husky setup thoroughly.
- Ensure that Husky prevents commits with invalid commit messages and that the pre-commit checks run successfully.

**Step 8: Merge and Communicate**
- Once you have verified that everything works as expected, merge your feature branch into the main development branch.
- Communicate this enhancement with the rest of the team, providing instructions on how to use commit linting and Husky effectively.

By following these steps, you'll successfully implement commit linting and Husky in your project, leading to improved code quality and a more streamlined development process. If you encounter any issues or have questions during the implementation, don't hesitate to seek help from your team or the community.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by Nishitbaria** [comment]
Hey @panwar8279  Please assign me this issue

**Comment by panwar8279** [comment]
Hi @Nishitbaria , I have assigned this task to you. Kindly complete this within  2 days. Good luck!
