### ISSUE TITLE
[Feature Request]: Validation for non-numeric input in script.js in guessing number

### ISSUE THREAD

**Issue by tamannaaaaa** [ssitvit/Games-and-Go#972]
### How would you like to enhance the existing project.

In the checkGuess() function, you check if the guessedNumber is a valid number between 1 and 100. However, you don't handle cases where the input is not a number at all. When the user enters a non-numeric value (e.g., letters or symbols) in the input field, the parseInt() function will return NaN, and the game will not provide a useful error message. You may want to add validation to handle non-numeric input gracefully.

### Describe breifly how would you implement the same.

To fix the validation issue, you can modify the checkGuess() function. This change ensures that the player receives an error message when they input non-numeric values. Additionally, I've moved the attempts++ statement to all branches of the conditional statement to ensure the attempts are incremented appropriately.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by panwar8279** [comment]
Hi @tamannaaaaa , I have assigned this task to you. Kindly complete this within 2 days. Good luck!

**Comment by tamannaaaaa** [comment]
Hi @panwar8279 . I have done it it's the PR #1003 .
