### ISSUE TITLE
[BUG]: Found Duplicate Issue templates for Documentation 🙅🏻❌ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ssitvit/Games-and-Go#977]
### Description

- Currently there are two issue templates regarding Documentation.
- Having both of them is considered as duplication, Since one issue template is enough for each corresponding issue.
- The first Documentation issue template `Documentation or README.md issue report` has not structured like the second one `📄 Documentation issue`.
- So we need to remove the first Documentation issue template to maintain repository's integrity and maintainability. 

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/e450d07a-e950-4626-aa51-14f18c5da758)

**Comment by 0xabdulkhalid** [comment]
Hey there @panwar8279 👋🏻 

Please make sure to assign this issue to me to make the work done!

**Comment by panwar8279** [comment]
Hi @0xabdulkhalid , I have assigned this issue to you. Kindly complete this within 2 days. Good luck!
