### ISSUE TITLE
Adding Rock Paper and Scissors game.

### ISSUE THREAD

**Issue by gaurisharma1122** [ssitvit/Games-and-Go#98]
I want to add a Rock Paper and Scissors game to the project. It will be a user v/s computer game. Kindly assign me this task.

![rock-paper-scissors](https://github.com/ssitvit/Games-and-Go/assets/54466622/c6d70d6b-3c70-4d61-adc2-177aabe5498c)

**Comment by raj03kumar** [comment]
Assigned this issue to you. Kindly get it done within a week and go through the readme and contributing.md for successful merge. All the best to your work Gauri... !!!
