### ISSUE TITLE
[FEATURE] Making the contributors section dynamic.

### ISSUE THREAD

**Issue by Viveksati5143** [ssitvit/Games-and-Go#982]
### Description

Making the contributors section dynamic in Readme.md

### Screenshots

The gif will look something like this with limit upto 54 contributors & will move from right to left.
<img width="960" alt="image" src="https://github.com/ssitvit/Games-and-Go/assets/100852245/26465caa-f089-40c8-861c-8ba429b08232">

**Comment by Viveksati5143** [comment]
@panwar8279 Can I work on this issue?

**Comment by panwar8279** [comment]
Hi @Viveksati5143 , I have assigned this to you. Kindly complete within 2 days. Good luck!

**Comment by Viveksati5143** [comment]
Done @panwar8279
