### ISSUE TITLE
[FEATURE] - Content of About Section Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#991]
### Description

Currently, the style of about section content is very simple. As an about section in the game website, it should be more intense and  deep enough to give users more advance experience.

### Screenshots

**Current Design**

![i (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/17241ea0-9d86-4b29-a6a7-36d38e7fa982)

**Expected Updated Design**

![i (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/9846fa4c-88a8-4f6d-8108-035ba95781af)

### Additional information

No

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly enlarge each screenshot to clearly see the difference in font styling.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this task to you. Kindly complete this within 2 days. Good luck!

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly close this issue as the pull request related to this issue has been merged.
