### ISSUE TITLE
[Bug]: 'ALPHABET GAME' Design Errors

### ISSUE THREAD

**Issue by iamRabia-N** [ssitvit/Games-and-Go#994]
### Give a brief about the bug discovered✍

The design of this game contains many bugs i.e. coloring of text, positions of the buttons, oversizing of buttons, invisibility of text in each box etc. creating difficulty for users to play this game. 
**_The oversize boxes are causing the users to scroll to right in order to continue the game._**

### What is the expected behavior?

Clear, user-friendly design of the game.

### Give a brief description to get the expect behaviour.

By working on the styling of the game, I can solve this error.

### Screenshots

**Current Design**

![i (1)](https://github.com/ssitvit/Games-and-Go/assets/115794049/7ad46bb6-61c8-4ef5-9ac9-a8b30b589efe)

**Expected Updated Design**

![i (2)](https://github.com/ssitvit/Games-and-Go/assets/115794049/5014160e-eec3-4f7f-8561-5ffc7a4a4dbe)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/ssitvit/Games-and-Go/blob/main/Contributing.md) of this project.

**Comment by iamRabia-N** [comment]
Hi @panwar8279 
Kindly assign me this issue.

**Comment by panwar8279** [comment]
Hi @iamRabia-N , I have assigned this issue to you. Kindly complete within 2 days. Good luck!
