### ISSUE TITLE
[GSSoC'23] Text not visible on search box

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ssitvit/Games-and-Go#997]
### Description

- Text is not visible on searching anything it.

### Screenshots

![image](https://github.com/ssitvit/Games-and-Go/assets/114330097/104c20c5-d7de-4974-9f08-3a62c220646a)

### Additional information

I would like to work on it
- Adding a hovering effect with neon light effect.
- Adding a closed and open able search bar.
- Adding a font of game type for the search box.

**Comment by Avdhesh-Varshney** [comment]
@admindebu @panwar8279 @Shreyaar12 please assign this task to me to work on it under GSSoC'23

**Comment by panwar8279** [comment]
Hi @Avdhesh-Varshney , I have assigned this task to you. Kindly complete within 2 days. Good luck!
